Gopkg.lock, drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/nodeWiper.yaml, drivers/storage/portworx/testspec/nodeWiperPKS.yaml, drivers/storage/portworx/testspec/nodeWiperWithWipe.yaml, drivers/storage/portworx/testutils.go, drivers/storage/portworx/uninstall.go, pkg/controller/storagecluster/storagecluster.go, pkg/util/k8s/k8s.go, vendor/github.com/libopenstorage/openstorage/pkg/dbg/log.go, vendor/github.com/libopenstorage/openstorage/pkg/dbg/profile_dump.go
- Wipe metadata only if UninstallAndWipe strategy is selected
- Use k8s client for controller-runtime instead of sched ops in uninstall.go
- Do not error out in storagecluster controller if cluster object is already deleted
- Add unit tests for uninstall/delete workflows in portworx driver
=> Add missing volumes mounts for node wiper

deploy/olm-catalog/portworx/portworxoperator.package.yaml, deploy/olm-catalog/portworx/portworxoperator.v1.0.5.clusterserviceversion.yaml
Copying the 1.0.3 CSV file to 1.0.4 and only changing the default Portworx image to 2.1.2 instead 2.1.2-rc1
Moving the 1.0.4 CSV contents to 1.0.5
=> Point portworx package to v1.0.4

pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go
The service update breaks if the service had node ports before and the
type was changed to ClusterIP
=> Should allow changing service type to cluster ip

drivers/storage/portworx/portworx.go, drivers/storage/storage.go, pkg/controller/storagecluster/storagecluster.go, pkg/mock/storagedriver.mock.go
- Pass on this information to the driver through the new UpdateDriver API.
- The UpdateDriver API can be used to keep updating the Driver with information that the controller has.
=> Detect cloud provider and zone/instances information in controller loop.

drivers/storage/portworx/cloud_storage.go, drivers/storage/portworx/cloud_storage_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/storage.go, pkg/apis/core/v1alpha1/storagecluster.go, pkg/apis/core/v1alpha1/zz_generated.deepcopy.go, pkg/cloudstorage/manager.go, pkg/controller/storagecluster/storagecluster.go, pkg/mock/storagedriver.mock.go
- Update StorageCluster CRD to include CapacitySpecs in CloudStorageSpec. …
- Regenerate code.
- Change the Portworx driver to handle CapacitySpecs.
- Invoke the CloudStorage API to get per node drive config.
- Parse the storage distribution returned by cloudops into arguments.
- UTs for CapacitySpecs
=> Handle CapacitySpecs in Portworx Driver

Gopkg.lock, build/Dockerfile, drivers/storage/portworx/cloud_storage.go, drivers/storage/portworx/cloud_storage_test.go, drivers/storage/portworx/deployment.go, pkg/cloudstorage/manager.go, vendor/github.com/libopenstorage/cloudops/specs/decisionmatrix/azure.yaml, vendor/github.com/libopenstorage/cloudops/specs/decisionmatrix/doc.go
- Package libopenstorage/cloudop's storage distribution yamls into operator container.
- Added a new API CreateStorageDecisionMatrix in CloudManager.
- Read the cloud provider specific yamls packaged in the operator
and create a config map if it does not exist.
- Added UTs for the new API.
=> Package storage distribution yamls

build/Dockerfile, deploy/crds/core_v1alpha1_storagecluster_crd.yaml, deploy/crds/core_v1alpha1_storagenode_crd.yaml, deploy/olm-catalog/portworx/core_v1alpha1_storagecluster_crd.yaml, deploy/olm-catalog/portworx/core_v1alpha1_storagenode_crd.yaml, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go
- In OLM based deployments the CRD are registered using the CRD yamls that are bundled with the operator CSV. Currently in code we were registering the basic CRD objects for non OLM deployments. To keep it consistent, bundling the same CRDs in the operator container and using those to register the objects.
- Adding descriptions and missing fields in the CRD yaml validation section. Adding description will help self explain the object with `kubectl explain`
=> Register CRD from yaml files in code

build/Dockerfile, drivers/storage/portworx/deployment.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/manifest/testspec/portworx-releases.yaml, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/portworx-releases.yaml, manifests/portworx-releases.yaml, pkg/apis/core/v1alpha1/storagecluster.go, pkg/client/clientset/versioned/clientset.go, pkg/client/clientset/versioned/fake/clientset_generated.go, pkg/client/clientset/versioned/typed/core/v1alpha1/core_client.go, pkg/client/clientset/versioned/typed/core/v1alpha1/fake/fake_core_client.go, pkg/client/clientset/versioned/typed/core/v1alpha1/generated_expansion.go, pkg/client/informers/externalversions/core/v1alpha1/interface.go, pkg/client/informers/externalversions/generic.go, pkg/client/listers/core/v1alpha1/expansion_generated.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/stork.go
- Introduce a hardcoded portworx release manifest with related component versions to go with different portworx versions. In future we will have an online manifest that we can pull before using the hardcoded one. Will make Manifest an interface then.
- By default if portworx image version is changed, other component versions also change based on the release manifest. 
- Introduced `LockImage` boolean in all component specs to disallow default image override from manifest. 
- Release manifest will look something like this - 
```
defaultRelease: 2.1.3
releases:
2.1.2:
stork: openstorage/stork:2.2.5
lighthouse: portworx/px-lighthouse:2.0.4
2.1.3:
stork: openstorage/stork:2.2.5
lighthouse: portworx/px-lighthouse:2.0.4
```
- The portworx version is determined from the tag of `spec.image`. If …
=> Use release manifest to group component versions

Gopkg.lock, drivers/storage/portworx/components.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/storageClassDb.yaml, drivers/storage/portworx/testspec/storageClassDbCloudSnapshot.yaml, drivers/storage/portworx/testspec/storageClassDbCloudSnapshotEncrypted.yaml, drivers/storage/portworx/testspec/storageClassDbEncrypted.yaml, drivers/storage/portworx/testspec/storageClassDbLocalSnapshot.yaml, drivers/storage/portworx/testspec/storageClassDbLocalSnapshotEncrypted.yaml, drivers/storage/portworx/testspec/storageClassReplicated.yaml, drivers/storage/portworx/testspec/storageClassReplicatedEncrypted.yaml, pkg/controller/storagecluster/stork.go, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go, pkg/util/test/util.go
- Adding 4 default storage classes that get installed with portworx and removed when the StorageCluster spec is removed.
- We may not be able to delete these storage classes from operator in the future as they could be used. Also we will not be able to update most of the values as they are immutable.
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
name: px-db
annotations:
params/docs: "https://docs.portworx.com/scheduler/kubernetes/dynamic-provisioning.html"
params/fs: "Filesystem to be laid out: none|xfs|ext4"
params/block_size: "Block size"
params/repl: "Replication factor for the volume: 1|2|3"
params/secure: "Flag to create an encrypted volume: true|false"
params/shared: "Flag to create a globally shared namespace volume which can be used by multiple pods: true|false" …
```
=> Add default storage classes for portworx

deploy/olm-catalog/portworx/portworxoperator.v1.1.0.clusterserviceversion.yaml, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go
- Add status for deleting stages
- Allow all installation modes for the operator to support previous releases
- Remove the defaults from the example spec to keep the StorageCluster spec simple.
=> Use default storage if nothing present

deploy/crds/core_v1alpha1_storagecluster_crd.yaml, drivers/storage/portworx/deployment.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, pkg/apis/core/v1alpha1/storagecluster.go, pkg/apis/core/v1alpha1/zz_generated.deepcopy.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/update.go, pkg/controller/storagecluster/util.go
- If the selector in node specs matches a k8s node, use the storage
configuration from the matching node spec.
- If a partial storage config is used in node spec, populate the rest
of the fields from cluster storage configuration.
A sample list of node specs will look something like below:
```
spec:
storage:
devices:
- /dev/sda
- /dev/sdb
nodes:
- selector:
nodeName: k8s-node-1
storage:
useAll: true
- selector:
labelSelector:
matchExpressions:
- key: drive-type
operator: In
values:
- ssd
- hdd
storage:
devices:
- /dev/xvdf
- selector:
labelSelector:
matchLabels:
storageless: "true"
storage:
devices: {}
```
=> Heterogenous storage configuration using node specs

drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/nodeWiper.yaml, drivers/storage/portworx/testspec/nodeWiperPKS.yaml, drivers/storage/portworx/testspec/nodeWiperWithWipe.yaml, drivers/storage/portworx/uninstall.go
In non-openshift clusters, the portworx service account is removed
as soon as the StorageCluster object is marked for deletion. If the
node-wiper pods have not been started by then, it will never start
as the service account is gone.
Currently the node wiper does not need any k8s permissions, so just
service account without any k8s permissions is enough.
=> Create service account for Portworx node wiper

drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/component/portworx_crd.go, drivers/storage/portworx/component/portworx_sc.go, drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/util/util.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/stork_test.go, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go
- If portworx is disabled, then do not deploy
portworx pods, portworx RBAC, API pods, portworx service, storage classes
- Do not update storage cluster status or create storage node objects
- Do not allow deleting the portworx with any delete strategy
- We should still be able to deploy components using the StorageCluster
=> Allow disabling of storage pods

drivers/storage/portworx/component/monitoring.go, drivers/storage/portworx/testspec/prometheusServiceMonitor.yaml, drivers/storage/portworx/testspec/prometheusServiceMonitorWithInternalKvdb.yaml
This is useful when px central like components deploy their
own prometheus stack in their own namespace.
=> Check portworx service in any namespace for metrics

drivers/storage/portworx/component/prometheus.go, drivers/storage/portworx/testspec/prometheusOperatorClusterRole.yaml, drivers/storage/portworx/testspec/prometheusOperatorDeployment.yaml
- Changed Prometheus operator version from 0.29.0 to 0.35.0(latest stable)
- Added `podmonitors` permissions into Prometheus operator cluster role
=> prometheus operator version change

build/Dockerfile, drivers/storage/portworx/component/portworx_sc.go, drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/nodeWiper.yaml, drivers/storage/portworx/testspec/nodeWiperPKS.yaml, drivers/storage/portworx/testspec/nodeWiperWithWipe.yaml, drivers/storage/portworx/testspec/openshift_runc.yaml, drivers/storage/portworx/testspec/pvcControllerClusterRole.yaml, drivers/storage/portworx/util/util.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/stork_test.go, pkg/controller/storagecluster/testspec/storkSchedDeployment.yaml
Changes included in this PR
- Add a new annotation to allow disabling default portworx storage classes
- Change the default start port for portworx in openshift to 17001
- Change minimum supported k8s version to 1.12
- Change operator's base image to rhel-atomic:7.7
- Update the portworx node-wiper image to 2.1.4
=> Annotation to disable default portworx storage classes

deploy/olm-catalog/portworx/portworxoperator.v1.3.0.clusterserviceversion.yaml, drivers/storage/portworx/component/lighthouse.go, drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/lighthouseClusterRole.yaml, drivers/storage/portworx/testspec/nodeWiperClusterRole.yaml, drivers/storage/portworx/testspec/nodeWiperClusterRoleBinding.yaml, drivers/storage/portworx/testspec/portworxClusterRole.yaml, drivers/storage/portworx/testspec/pvcControllerClusterRole.yaml, drivers/storage/portworx/testspec/pvcControllerClusterRoleBinding.yaml, drivers/storage/portworx/testspec/pvcControllerDeployment.yaml, drivers/storage/portworx/testspec/pvcControllerDeploymentOpenshift.yaml, drivers/storage/portworx/uninstall.go
- Earlier we used to register the SCC from the operator CSV spec. Changing that to register it from the code now.
- Also adding a cluster role for portworx node wipe and adding SCC to that.
=> Fix node wiper security context constraints

drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/component/portworx_proxy.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/testspec/openshift_runc.yaml, drivers/storage/portworx/testspec/pks.yaml, drivers/storage/portworx/testspec/portworxPodCustomPort.yaml, drivers/storage/portworx/testspec/pxProxyClusterRoleBinding.yaml, drivers/storage/portworx/testspec/pxProxyDaemonSet.yaml, drivers/storage/portworx/testspec/pxProxyService.yaml, drivers/storage/portworx/testspec/px_csi_0.3.yaml, drivers/storage/portworx/testspec/px_csi_1.0.yaml, drivers/storage/portworx/testspec/px_kvdb_certs.yaml, drivers/storage/portworx/testspec/px_kvdb_certs_without_ca.yaml, drivers/storage/portworx/testspec/px_kvdb_certs_without_key.yaml, drivers/storage/portworx/testspec/px_kvdb_without_certs.yaml, drivers/storage/portworx/testspec/runc.yaml
- If running outside kube-system namespace and not using 9001 port, we create a proxy service to redirect in-tree driver traffic to portworx nodes.
- Pass PX_NAMESPACE to portworx pods.
=> Create proxy pod and service in kube-system namespace for Portworx volume provisioning

drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/csiDeploymentWithResizerAndOldDriver_1.0.yaml, drivers/storage/portworx/testspec/csiDeploymentWithResizer_1.0.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0.yaml, drivers/storage/portworx/testspec/px_csi_0.3.yaml, drivers/storage/portworx/testspec/px_csi_1.0.yaml, drivers/storage/portworx/util/csi_generator.go, pkg/util/util.go
- Fix the csi-snapshotter image path
- Add quay.io to common registries list, so that the it get's replaced with custom registry if specified
=> Remove extra kubelet path from px container when CSI is enabled

drivers/storage/portworx/component/csi.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/csiDeploymentWithResizerAndOldDriver_1.0.yaml, drivers/storage/portworx/testspec/csiDeploymentWithResizer_1.0.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0.yaml, drivers/storage/portworx/util/csi_generator.go
Also use older csi-snapshotter image for 1.13.*
=> Remove deprecated snapshotter arg from csi-snapshotter

deploy/crds/core_v1alpha1_storagecluster_crd.yaml, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/status.go, pkg/apis/core/v1alpha1/storagecluster.go, pkg/apis/core/v1alpha1/zz_generated.deepcopy.go, pkg/controller/storagecluster/controller_test.go
If users don't have dedicated kvdb nodes, and want to dedicate a kvdb device for all nodes - 
```
spec:
storage:
useAll: true
kvdbDevice: /dev/kvdb
```
If users have dedicated kvdb nodes which can be storage nodes -
```
spec:
storage: # Not needed if using useAll as operator will put that as the default config if none provided
useAll: true
nodes:
- selector:
labelSelector:
matchLabels:
kvdb: "true"
storage:
kvdbDevice: /dev/kvdb
```
If users have dedicated kvdb nodes and want them to be storage less nodes -
```
spec:
storage: # Not needed if using useAll as operator will put that as the default config if none provided
useAll: true
nodes:
- selector:
labelSelector:
matchLabels:
kvdb: "true"
storage:
devices: []
kvdbDevice: /dev/kvdb
```
=> Add support to specify kvdb device

drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/uninstall.go
=> Cherrypick: Use cluster's image pull policy even for node wiper

drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/testspec/portworxPodEnvOverride.yaml, drivers/storage/portworx/util/util.go
- Also override existing default env var values with
user-passed values. Dedup env vars.
=> Give portworx permissions for custom secrets namespace

drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/testspec/portworxPodEnvOverride.yaml, drivers/storage/portworx/util/util.go
- Also override existing default env var values with
user-passed values. Dedup env vars.
=> Cherrypick: Give portworx permissions for custom secrets namespace

drivers/storage/portworx/component/csi.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/manifest/common.go, drivers/storage/portworx/manifest/configmap.go, drivers/storage/portworx/manifest/configmap_test.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/manifest/remote.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/csiDeploymentAlphaDisabledK8s_1_14.yaml, drivers/storage/portworx/testspec/csiDeploymentAlphaDisabledK8s_1_16.yaml, drivers/storage/portworx/testspec/csiDeploymentWithResizerAndOldDriver_1.0.yaml, drivers/storage/portworx/testspec/csiDeploymentWithResizer_1.0.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0.yaml, drivers/storage/portworx/testspec/csiStatefulSet_0.3.yaml, drivers/storage/portworx/uninstall.go, drivers/storage/portworx/util/csi_generator.go, drivers/storage/portworx/util/csi_generator_test.go, pkg/apis/core/v1alpha1/storagecluster.go
- Get CSI images from version manifest instead of hard-coded logic
=> Retrieve version manifest from ConfigMap for airgapped clusters

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/component/component.go, drivers/storage/portworx/component/csi.go, drivers/storage/portworx/component/lighthouse.go, drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/component/portworx_crd.go, drivers/storage/portworx/component/portworx_proxy.go, drivers/storage/portworx/component/portworx_sc.go, drivers/storage/portworx/component/prometheus.go, drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/uninstall.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/stork_test.go, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go
- As per k8s docs - https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/ cross namespace ownership is disallowed. So removing all object ownership on cluster-scoped and other namespace objects.
- Removing ownership on already installed objects 
- Delete all object during cluster deletion. Mostly need to explicitly delete cross namespace objects only because they don't have ownership, but it is easier to deleted all objects once.
- Delete px storageclasses only when portworx is uninstalled
=> Not own cross namespaces objects by storagecluster

deploy/crds/core_v1alpha1_storagecluster_crd.yaml, pkg/apis/core/v1alpha1/storagecluster.go, pkg/apis/core/v1alpha1/zz_generated.deepcopy.go, pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/stork_test.go
Adding a flag under stork section in the StorageCluster spec to toggle host network for stork pods. 
From what I understand, this is needed for px-backup to work in AWS.
```
spec:
stork:
enabled: true
hostNetwork: true
```
=> Add option to run stork in host network

drivers/storage/portworx/component/security.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx_test.go, pkg/util/k8s/k8s.go
- Add ownership on token secrets so they get deleted on
StorageCluster deletion
- Do not add ownership on secret keys to avoid deletion
on StorageCluster deletion
=> Correctly delete security secrets

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/util/util.go, pkg/controller/storagecluster/storagecluster.go
- Operator takes `PORTWORX_ESSENTIALS` env var which tells it to only deploy an essentials cluster
- Pass `-marketplace_name` argument to Portworx (>= 2.5.5) which operator gets from `MARKETPLACE_NAME` env var
- Raise a warning event on StorageCluster object if `px-essential` secret is not present. Do not deploy portworx pods until the secret is created.
Here are some sample error events wrt the secret - 
```
Events:
Type     Reason      Age                   From                       Message
----     ------      ----                  ----                       -------
Warning  FailedSync  60s (x2 over 61s)     storagecluster-controller  pre-install hook failed: secret kube-system/px-essential does not have Essentials Entitlement ID (px-essen-user-id)
Warning  FailedSync  30s (x20 over …
```
=> Add an option to deploy essentials only cluster

cmd/operator.go, pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/stork_test.go, pkg/controller/storagecluster/testspec/storkDeployment.yaml
- Even for stork use the cluster's namespace for leader
election, unless the user explicitly overrides it
=> Use cluster's namespace by default for leader election

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/status.go, drivers/storage/portworx/util/util.go
- If NodeInit condition and NodeState condition have the same  timestamp, then we should use NodeState condition as that  is the latest response from SDK.
Taking latest NodeInit condition causes it to be stuck in  Initializing/Failed state even though node may have a different  status.
- Do not raise warning event on GRPC connection during cluster init. 
As the cluster is initializing the SDK server won't be up. There  is no need to panic the user by raising GRPC connection events.  Once the cluster is up, if the connection is lost, then we should  raise such an event.
- Don't recreate node-wiper if already ran and finished
=> Multiple minor fixes

drivers/storage/portworx/components_test.go, drivers/storage/portworx/manifest/configmap.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/manifest/multiple.go, drivers/storage/portworx/manifest/multiple_test.go, drivers/storage/portworx/manifest/remote.go, drivers/storage/portworx/manifest/remote_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/nodeWiper.yaml, drivers/storage/portworx/testspec/nodeWiperPKS.yaml, drivers/storage/portworx/testspec/nodeWiperWithWipe.yaml, drivers/storage/portworx/uninstall.go, pkg/apis/core/v1alpha1/storagecluster.go, pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
This PR is assuming the spec looks like
```
spec:
autoUpdateComponents:  Always|Once|Never
```
We could change the placement of autoupgrade spec, but the logic would not change.
=> Auto-update components

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go
Starting oci-monitor:2.3.2, we support taking in the image pull
secret name directly in oci-mon.
=> Use REGISTRY_SECRET instead of REGISTRY_CONFIG

deploy/crds/core_v1alpha1_storagenode_crd.yaml, deploy/olm-catalog/portworx/1.4.0/core_v1alpha1_storagenode_crd.yaml, drivers/storage/portworx/status.go
- resource.Quantity does not return true with DeepEqual for the same quantity.
This was causing the storage node to get updated even if there is no change.
=> Use uint64 for size instead of resource.Quantity

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/storage.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/stork_test.go, pkg/controller/storagecluster/testspec/storkDeployment.yaml, pkg/mock/storagedriver.mock.go
- Also remove duplicate env variables before passing to
stork deployment. Give spec.stork.env priority over
build-in env variables, so users can override them.
=> Add STORK-NAMESPACE env variable to stork

drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/util/util.go
In AWS marketplace, portworx has to use a service account associated
with the IAM role so that the metering would work for Portworx.
The users can create that service account and ask the operator to use
that service account instead of the default one.
=> Let users specify the service account to be used by portworx pods

drivers/storage/portworx/manifest/manifest.go
- Also use the new version manifest starting 2.5.7 as the
spec generator changes are now backported to 2.5.7
=> Change the default image for portworx

drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/px_k3s.yaml
FileOrCreate type is not supported for socket file,
starting k8s 1.19
=> Removing FileOrCreate for socket file

drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/component/security.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/util/util.go, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go
Changes:
- Creating pod disruption budgets for portworx storage nodes and internal kvdb nodes
- By default PDBs will be created. Providing an annotation to disable their creation.
- Also waiting for cluster to be up before making SDK calls from PDB and security components. The calls used to fail when cluster was not yet initialized and raise warning events.
=> Create pod disruption budgets for storage and kvdb pods

drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/uninstall.go, drivers/storage/portworx/util/util.go
Create the pod disruption budget looking at the kvdb_cluster_size args
in misc args. If not present, use the default kvdb cluster size of 3.
=> Use kvdb cluster size from misc args, if present

pkg/constants/constants.go, pkg/constants/metadata.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagenode/storagenode.go, pkg/controller/storagenode/storagenode_test.go, pkg/util/k8s/node.go, pkg/util/k8s/node_test.go
Keep the default delay of 2 min before we start creating the pods again. 
Also adding an annotation to overwrite the default delay of 2 minutes.
=> Delay creation of deleted pods on cordoned nodes

drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/openshift_runc.yaml
* adding a pre-exec rule to fix protection on cached px-configs
=> PWX-17604: fix OpenShift upgrades

drivers/storage/portworx/component/prometheus.go, drivers/storage/portworx/testspec/prometheusInstanceWithRemoteWriteEndpoint.yaml
From pxcentral-api server side, install module api will take care of adding http or https based on either ssl is required/enabled in cortex endpoint.
=> Removed http from remote write endpoint url

test/integration_test/Dockerfile, test/integration_test/operator-test-pod.yaml
Remove copy of the whole test dir from Dockerfile to reduce the size of test container. Will be using git source management instead.
=> PTX-2938 Remove copy of the whole test dir from Dockerfile

drivers/storage/portworx/component/podsecuritypolicies.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/privilegedPSP.yaml, drivers/storage/portworx/testspec/restrictedPSP.yaml, drivers/storage/portworx/util/util.go, pkg/util/test/util.go
Disable PSPs by default. Expose an annotation to enabled the operator created PSPs.
OPERATOR-279
=> Annotation to toggle pod security policies

drivers/storage/portworx/component/podsecuritypolicies.go, drivers/storage/portworx/testspec/privilegedPSP.yaml
This is needed by the node-wiper container as it writes its
done status in a file under /tmp
=> Allow writing to root file system inside the container

drivers/storage/portworx/testspec/nodeWiper.yaml, drivers/storage/portworx/testspec/nodeWiperPKS.yaml, drivers/storage/portworx/testspec/nodeWiperWithWipe.yaml, drivers/storage/portworx/uninstall.go
operator uses `px-node-wiper`
`px-node-wiper` uses `pxctl`, which needs access to Unix DS
on `/var/lib/osd/driver`
related to https://github.com/portworx/talisman/pull/114
=> OPERATOR-264: need to mount /var/lib/osd/driver

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/component/component.go, drivers/storage/portworx/component/csi.go, drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/component/lighthouse.go, drivers/storage/portworx/component/monitoring.go, drivers/storage/portworx/component/podsecuritypolicies.go, drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/component/portworx_crd.go, drivers/storage/portworx/component/portworx_proxy.go, drivers/storage/portworx/component/portworx_sc.go, drivers/storage/portworx/component/prometheus.go, drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/component/security.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx.go
We should install certain components like PSP, security
before other components start to resolve run time
dependencies.
=> Reconcile components in order of their priority

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/testspec/ccmconfig.yaml
This will help remove confusion since PX has no concept of appliance
Closes #
=> OPERATOR-256 rename appliance ID to cluster UUID

pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/stork_test.go
add `AllowVolumeExpansion` flag to `stork-snapshot-sc` storageclass, tested result shown as:
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
creationTimestamp: "2021-04-14T20:57:39Z"
managedFields:
- apiVersion: storage.k8s.io/v1
fieldsType: FieldsV1
fieldsV1:
f:allowVolumeExpansion: {}
f:provisioner: {}
f:reclaimPolicy: {}
f:volumeBindingMode: {}
manager: operator
operation: Update
time: "2021-04-14T20:57:39Z"
name: stork-snapshot-sc
resourceVersion: "2486"
selfLink: /apis/storage.k8s.io/v1/storageclasses/stork-snapshot-sc
uid: 4154fd84-179b-46d2-b4b9-dbf26811d3ec
provisioner: stork-snapshot
reclaimPolicy: Delete
volumeBindingMode: Immediate
```
Closes # …
=> [OPERATOR-311] Allow volume expansion for stork-snapshot-sc storageclass

pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/testspec/storkSchedClusterRole.yaml
Signed-off-by: Rohit-PX <rohit@portworx.com>
For k8s version 1.21 and greater stork scheduler needs more permissions
Closes #
=> Update cluster role for stork-scheduler

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go
* will collect the OSImage before generating template (i.e. "Bottlerocket OS 1.0.8" or "Ubuntu 18.04.5 LTS")
* based on OSImage, turns on Bottlerocket AMI customizations
Closes # OPERATOR-304
=> OPERATOR-304: Add BottleRocket AMI support

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/testspec/ccmconfig.yaml
The flag was missing in the config map.
Closes #
=> OPERATOR-256 Add no_rel_cert_enabled true to CCM config map

drivers/storage/portworx/component/csi.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/openshift_runc.yaml, drivers/storage/portworx/testspec/pks.yaml, drivers/storage/portworx/testspec/portworxPodCustomPort.yaml, drivers/storage/portworx/testspec/portworxPodEnvOverride.yaml, drivers/storage/portworx/testspec/px_kvdb_certs.yaml, drivers/storage/portworx/testspec/px_kvdb_certs_without_ca.yaml, drivers/storage/portworx/testspec/px_kvdb_certs_without_key.yaml, drivers/storage/portworx/testspec/px_kvdb_without_certs.yaml, drivers/storage/portworx/testspec/px_master.yaml, drivers/storage/portworx/testspec/runc.yaml, drivers/storage/portworx/util/feature.go, drivers/storage/portworx/util/util.go
* Installs CSI by default unless explicitly disabled.
* Fixes many unit tests that assumed CSI was disabled by default.
n/a
n/a
=> [CSI] Install by default when Portworx is enabled

Makefile, deploy/olm-catalog/portworx/1.4.5/portworxoperator.v1.4.5.clusterserviceversion.yaml, deploy/olm-catalog/portworx/1.5.0/portworxoperator.v1.5.0.clusterserviceversion.yaml, deploy/olm-catalog/portworx/2.0.0/core_v1_storagecluster_crd.yaml, deploy/olm-catalog/portworx/2.0.0/core_v1_storagenode_crd.yaml, deploy/olm-catalog/portworx/2.0.0/portworxoperator.v2.0.0.clusterserviceversion.yaml, deploy/olm-catalog/portworx/portworx.package.yaml, deploy/operator.yaml
This PR includes following changes. Not all changes will be required when we cut a branch from master every time.
- Adding 2.0.0 CSV (required so master can point to new operator version)
- Updating everywhere to point to portworx/px-operator image
- Cherrypick from 1.4.5 for released image update
Closes #
=> Adding ClusterServiceVersion (CSV) for 2.0.0

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/testspec/ccmconfig.yaml
Needed as per CCM change: https://jira.purestorage.com/browse/CLOUD-58502
This allows CCM to just use the appliance ID (cluster uuid for PX) for subscription
and does not require to specify it again in the spec
Closes #
=> OPERATOR-256 Add subscription section to use appliance ID

drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/openshift_runc.yaml, drivers/storage/portworx/testspec/pks.yaml, drivers/storage/portworx/testspec/portworxPodCustomPort.yaml, drivers/storage/portworx/testspec/portworxPodEnvOverride.yaml, drivers/storage/portworx/testspec/px_csi_0.3.yaml, drivers/storage/portworx/testspec/px_csi_1.0.yaml, drivers/storage/portworx/testspec/px_k3s.yaml, drivers/storage/portworx/testspec/px_kvdb_certs.yaml, drivers/storage/portworx/testspec/px_kvdb_certs_without_ca.yaml, drivers/storage/portworx/testspec/px_kvdb_certs_without_key.yaml, drivers/storage/portworx/testspec/px_kvdb_without_certs.yaml, drivers/storage/portworx/testspec/px_master.yaml, drivers/storage/portworx/testspec/px_pks_with_csi.yaml, drivers/storage/portworx/testspec/px_telemetry-with-location.yaml, drivers/storage/portworx/testspec/px_telemetry.yaml, drivers/storage/portworx/testspec/runc.yaml
pxctl fails when running on oci-mon pod because Unix DS at `/var/lib/osd/driver/pwx-legacy.sock` is not available. Solution is to mount `/var/lib/osd' on the oci-mon pod.
Why not mount `/var/lib/osd/driver`? Because px-runc already mounts `/var/lib/osd` to the runc container and also mounts any mounts from oci-mon pod, causing illegal overlapping mounts. Adding `/var/lib/osd` to oci-mon is fine because px-runc de-dups them.
See github.com/portworx/porx/cmd/px-runc/px-runc.go
```
pxDefaultMounts = [][]string{
{"/dev", ""},
{"/var/lib/osd", "", "shared"},
```
Closes #
PWX-19004
** This is dependent on https://github.com/portworx/px-installer/pull/998 merging before it can …
=> Mount Unix DS location on oci-mon pod

.github/workflows/on-pr.yml
Removes github_api_url variable - seems like this action was either misconfigured or they removed this variable.
Has no effect other than removing a warning from the logs.
n/a
n/a
=> Remove github_api_url from labeler action

drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/px_telemetry.yaml
Signed-off-by: Paul Theunis <ptheunis@purestorage.com>
Add Memory limitations to the CCM pod.
Closes #OPERATOR-305
CPU limitations did not work. Will continue testing
=> OPERATOR-305: Add memory limits and requests

drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/px_telemetry.yaml
Signed-off-by: Paul Theunis <ptheunis@purestorage.com>
Co-authored-by: Paul Theunis <ptheunis@purestorage.com>
Cherry-pick from 1.5.0  master image doesn't work for me with 2.8 so development happened on 1.5.0
Adds limits to the memory of the container
=> OPERATOR-305: Add memory limits and requests (#316)

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/component/csi.go, drivers/storage/portworx/component/lighthouse.go, drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/component/portworx_proxy.go, drivers/storage/portworx/component/prometheus.go, drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/uninstall.go, pkg/constants/metadata.go, pkg/controller/storagecluster/stork.go, pkg/util/test/util.go, pkg/util/util.go, pkg/util/util_test.go
https://portworx.atlassian.net/browse/OPERATOR-240
Closes #
=> OPERATOR-240 [Mastercard] Unable to set image urls when using operator in air gapped environment

drivers/storage/portworx/component/csi.go, drivers/storage/portworx/components_test.go, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go
Updates CSIDriver object to v1 for k8s 1.18+. The CSI Driver object is v1 for k8s 1.18+:
https://kubernetes-csi.github.io/docs/csi-driver-object.html
In future k8s versions, v1beta1 CSI driver will be removed. 
Closes #
I've tested this change on K8s 1.17 and 1.20. Specifically, I've tested the upgrade path from operator 1.4.5 to my dev image with this change.
I've also delete and re-recreated the CSIDriver object to make sure the right CSIDriver object version is created.
=> [CSI] Update CSIDriver to v1 for k8s 1.18+

drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/components_test.go
https://portworx.atlassian.net/browse/OPERATOR-349
Closes #
use different port for aks so customers do not need to configure it in storagecluster.
=> OPERATOR-349 AKS crash due to port conflict

drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/px_telemetry-with-location.yaml, drivers/storage/portworx/testspec/px_telemetry.yaml
Per Brian Pan, the default is 8 but 2 should suffice and it reduces memory usage by 40MB
Pasting slack thread
```
bpan There will be 2 changes you should make on your side:
Add an environment variable export controller_sn=123
Add a parameter to the docker run command: -Dserver.rest_server.core_pool_size=2
11:54 AM
-Dserver.rest_server.core_pool_size=2 reduces the resources used for listening on 1970.
11:56 AM
Harsh Desai 
export controller_sn=123
yup, we already did this and it works great !
Add a parameter to the docker run command: -Dserver.rest_server.core_pool_size=2
didn't know about that. let me do that today.
11:56 AM
reduces the resources used for listening on 1970.
by how much?
11:59 AM
bpan Pool defaults to 8 which is what is used for FA. I saw 2 saving up to 40MB.
12:01 PM
In …
```
=> CLOUD-59607 restrict server core pool size to 2

drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/px_telemetry-with-location.yaml, drivers/storage/portworx/testspec/px_telemetry.yaml
Per Brian Pan, the default is 8 but 2 should suffice and it reduces memory usage by 40MB
Closes #
=> [cherry-pick] CLOUD-59607 restrict server core pool size to 2 (#332)

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/components_test.go
Slack thread
```
11:30 AM
I am seeing an issue where after removing all staging config, on a fresh install, CCM is still talking to staging arcus
11:30 AM
what is the default?
12:39 PM
Harsh Desai 
2021-06-09 19:38:54.851 [taskScheduler-2] ERROR com.purestorage.core.transport.HttpClient Received error response from <REDACTED>. Status code: 400, request_uuid: 692d835c-f02e-48a4-81a0-c06c6bdda9b8.
12:40 PM
But you can try changing CCM to ‘external’.
Is this required? I was assuming that if location is not specified, the default would be external
1:51 PM
bpan If the array_loc is set, CCM will use it. If it’s not set, CCM will try a DNS lookup to preflight-rest.purestorage.com. In our VPN, that DNS resolves to 127.0.0.1 so CCM will cache …
```
=> PWX-20490 default to external location for arcus

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go
Fixing security settings for BottleRocket AMI deployments:
* replaced "privileged" flag with specific capabilities
* activating `super_t` SELinux type
Have to use slightly different security for BottleRocket v1.1.1:
* explicitly setting SELInux context, to activate `super_t` SELinux type
* using `prvileged: true` will strip the `super_t` SELinux type, so have to use capabilities instead
Closes # PWX-20544 , OPERATOR-362
Note that one still needs the pvc-controller to run on BottleRocket AMI, e.g.
```
metadata:
annotations:
portworx.io/pvc-controller: "true"
```
However, the determination if PVC-controller is needed …
=> PWX-20544-pt2 / OPERATOR-362: BottleRocket v1.1.1 support

drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/components_test.go, pkg/util/k8s/k8s.go
To access encryption secrets, we create role and rolebinding
in the encryption secrets namespace. We used to add storagecluster
as the owner for these objects. K8s does not like having cross-
namespace owner references. If done so it garbage collects
all the objects owned by the StorageCluster when the garbage
collector restarts.
Closes # https://portworx.atlassian.net/browse/OPERATOR-368
=> Remove cross-namespace ownership

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/testspec/ccmconfig.yaml
For 2.8.0, we only support on-demand and on-crash. No scheduled cadence
Closes #
=> PWX-20585 disable scheduled log uploader

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/testspec/ccmconfig.yaml
For 2.8.0, we only support on-demand and on-crash. No scheduled cadence
Closes #
=> [cherry-pick] PWX-20585 disable scheduled log uploader (#344)

pkg/util/k8s/k8s.go
Our input object does not set the fs group policy but
k8s will set it on the object. This fails the diff check
we use to decide whether to call the update or not.
Closes #
=> Avoid updating CSI driver object repeatedly

deploy/olm-catalog/portworx/1.6.0/portworxoperator.v1.6.0.clusterserviceversion.yaml, deploy/olm-catalog/portworx/2.0.0/portworxoperator.v2.0.0.clusterserviceversion.yaml
- After this, openshift UI shows a 'Create StorageCluster' button immediately after operator installation is complete. This will directly take the user to portworx cluster creation.
- Remove the autopilot disabling section as it is not longer needed.
- Making the 2.0.0 CSV similar to the 1.6.0
Closes # [OPERATOR-418](https://portworx.atlassian.net/browse/OPERATOR-418)
=> Adding 'Create StorageCluster' button on operator creation in openshift UI

drivers/storage/portworx/portworx.go, drivers/storage/storage.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/update.go, pkg/mock/storagedriver.mock.go
Previous we only look at storage pod to decide number of unavailable storage nodes, this is inaccurate because at some point we may think storage pod should not exist (due to node taint, affinity etc). the fix is to also look at storage node status to decide number of unavailable storage nodes. this number is used to do rolling update.
Closes #
Unit tests added, also verified on OCP cluster.
=> OPERATOR-377 fix portworx quorum loss issue during openshift upgrade

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go
This PR adds the automatic support for RKE2 clusters
* the latest Rancher RKE2 has switched to using K3s distribution
* based on the K8s version (e.g. `1.21.4+rke2r2`), we will automatically add the K3s mounts and turn on the CSI support -- same as we do w/ our K3s installs
Closes # OPERATOR-439
Parallel fix for YAML generator @ https://github.com/portworx/px-installer/pull/1119
**Testing notes**:
Using hybrid RKE2 cluster (different host-types):
```
NAME    STATUS   ROLES                       AGE   VERSION          INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION                CONTAINER-RUNTIME …
```
=> OPERATOR-439: Adding RKE2 support

deploy/crds/core_v1_storagecluster_crd.yaml, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, pkg/apis/core/v1/storagecluster.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/update.go
**What this PR does / why we need it**: Add resource requirements to portworx container in storage cluster pods
Closes # [OPERATOR-378](https://portworx.atlassian.net/browse/OPERATOR-378)
=> [OPERATOR-378] Allow adding portworx container resources requirements

pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/stork_test.go, pkg/controller/storagecluster/testspec/storkSchedVersionedDeployment.yaml
Pin the stork-scheduler version to 1.21.0 for k8s versions >= v1.22.0
Closes # https://portworx.atlassian.net/browse/OPERATOR-449
=> OPERATOR-449 For k8s versions >= v1.22.0, pin stork-scheduler to 1.21.0

drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/portworxKVDBService.yaml, drivers/storage/portworx/testspec/portworxService.yaml, drivers/storage/portworx/testspec/pxProxyService.yaml, drivers/storage/portworx/util/util.go
**What this PR does / why we need it**: Add portworx-kvdb-service for internal kvdb monitoring
Closes # [OPERATOR-440](https://portworx.atlassian.net/browse/OPERATOR-440)
=> [OPERATOR-440] Add portworx-kvdb-service for internal kvdb monitoring

deploy/olm-catalog/portworx/1.5.2/portworxoperator.v1.5.2.clusterserviceversion.yaml
Openshift 4.9 will use Kubernetes 1.22 which does not support
CRD v1beta1. We are adding support for 4.9 in operator 1.6.0.
Closes #
=> Set max supported openshift version to 4.8

drivers/storage/portworx/component/auth.go, drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
Closes # https://portworx.atlassian.net/browse/OPERATOR-443
=> OPERATOR-443 Close portworx sdk connection on uninstall

Makefile, drivers/storage/portworx/testspec/prometheusRule.yaml, pkg/util/test/util.go, test/integration_test/basic_test.go, test/integration_test/common_test.go, test/integration_test/fafb_config_test.go, test/integration_test/fafb_config_util.go, test/integration_test/fafb_matrix_test.go, test/integration_test/node_affinity_test.go, test/integration_test/operator-test-pod.yaml, test/integration_test/test-deploy.sh, test/integration_test/upgrade_test.go
This adds a functional testing framework that will test various `StorageCluster` specs and validate that Portworx does (or doesn't) come up successfully. It also adds some framework improvements to detect when Portworx fails to start, rather than always starting successfully, enabling for negative testing.
**Notes for your reviewer**:
Most tests are commented out right now, I have just one test enabled. I will uncomment more as I validate they work as expected, either in this PR or in future PRs.
=> Added FlashArray/FlashBlade matrix tests

Makefile, drivers/storage/portworx/component/csi.go, drivers/storage/portworx/component/prometheus.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/prometheusClusterRole.yaml, drivers/storage/portworx/testspec/prometheusOperatorClusterRole.yaml, drivers/storage/portworx/testspec/prometheusOperatorDeployment_v0.50.0.yaml, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go
**What this PR does / why we need it**: Upgrade Prometheus operator and related images to newer version and allow operator to create required CRDs for k8s 1.22 and above
Closes # [OPERATOR-454](https://portworx.atlassian.net/browse/OPERATOR-454)
=> [OPERATOR-454] Upgrade prometheus operator to a newer version

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/update.go
- Don't need to check for pods on k8s nodes where the
storage node is not supposed to run. Only check if the
SDK is showing the node is up to continue the upgrade.
Closes # https://portworx.atlassian.net/browse/OPERATOR-467
=> OPERATOR-467 Continue upgrade if all storage nodes are up

cmd/operator.go, pkg/constants/metadata.go, pkg/controller/storagecluster/storagecluster.go, pkg/migration/migration.go, pkg/migration/migration_test.go, pkg/util/util.go
- Adds a basic migration workflow. When the operator starts, it starts a goroutine for migration. The migration routine, will first create an equivalent StorageCluster object and wait for the user to approve the migration. 
- The actual migration code is not in the scope of this PR or ticket.
- This covers the migration of just the portworx daemonset. The components are not yet reflected in the StorageCluster object.
- Unit tests and functional tests will be added to this PR soon. 
Closes # https://portworx.atlassian.net/browse/OPERATOR-457
=> OPERATOR-457 Create equivalent storagecluster object for existing PX

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, pkg/constants/metadata.go, pkg/constants/migration.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/update.go, pkg/migration/migration.go, pkg/migration/migration_test.go, test/integration_test/migration_test.go, test/integration_test/testspec/migration/simple-daemonset.yaml, test/integration_test/utils/constants.go
*Does handle:*
- Migration of portworx daemonset pods, assuming daemonset pods were in healthy state already
- Allows skipping nodes if user knows the issue and is okay with it 
- Handles restarts of operator during migration
- Handles daemonset placement constraints
- Logs states and errors
*Does not:*
- Does not raise events on failures
- Does not update status of the StorageCluster
- Does not migrate components
- No provision for rollback
Closes # https://portworx.atlassian.net/browse/OPERATOR-459
=> OPERATOR-459 Migrate portworx daemonset pods

Makefile, go.mod, go.sum, vendor/modules.txt
This reverts commit 6aaa70eda2d472c14b73c716f90684aba2b1f547.
**What this PR does / why we need it**: Revert to use the latest staticcheck as the issue has been fixed. https://github.com/dominikh/go-tools/issues/1129#issuecomment-970056524
Closes #
=> Revert "Fix Travis CI staticcheck issue"

test/integration_test/basic_test.go, test/integration_test/fafb_test.go, test/integration_test/main_test.go, test/integration_test/migration_test.go, test/integration_test/types/testcase.go, test/integration_test/utils/constants.go, test/integration_test/utils/fafb_config.go
**What this PR does / why we need it**: print a test report block after run
```
--- PASS:
--- SKIP:
--- FAIL:
```
Closes #
**Special notes for your reviewer**: sample output
```
--- PASS: TestStorageClusterBasic (170.98s)
--- PASS: TestStorageClusterBasic/NodeAffinityLabels (170.98s)
=== RUN   TestFAFBPositiveInstallation
Source config not present, skipping
--- SKIP: C55130 [C55130]
Source config not present, skipping
--- SKIP: C55129-C56414-C56411-C55003 [C55129 C56414 C56411 C55003]
Source config not present, skipping
--- SKIP: C55133 [C55133]
Source config not present, skipping
--- SKIP: C56412 [C56412]
Source config not present, skipping
--- SKIP: C56413 [C56413]
--- PASS: TestFAFBPositiveInstallation (0.00s)
=== RUN   TestMigrationBasic
--- …
```
=> [OPERATOR-495] Add test report after run

test/integration_test/basic_test.go, test/integration_test/main_test.go, test/integration_test/types/testcase.go, test/integration_test/utils/constants.go, test/integration_test/utils/px_operator.go, test/integration_test/utils/storagecluster.go
**What this PR does / why we need it**: Check the px-operator version and skip tests
Closes #
=> [OPERATOR-502] Add support to check portworx-operator version

drivers/storage/portworx/deployment.go, drivers/storage/portworx/util/util.go, pkg/migration/generate.go, pkg/migration/migration.go, pkg/migration/migration_test.go
- Created a separate file for StorageCluster spec generation code as the file was getting big. Have added only the new code to it to make it easier for review. Will move the rest of the StorageCluster creation code in a separate PR later.
Closes # https://portworx.atlassian.net/browse/OPERATOR-505
=> OPERATOR-505 Add spec fields for components during migration

pkg/util/test/util.go, test/integration_test/basic_test.go, test/integration_test/utils/constants.go, test/integration_test/utils/storagecluster.go
Stork basic regression test and various improvements for validation of Stork components and images
* Added Autopilot basic regression test that covers multiple Autopilot test cases
Autopilot - Validate Autopilot is not enabled by default
Autopilot - Deploy Autopilot with enabled set to true
Autopilot - Validate Autopilot serviceaccount, clusterrole, clusterrolebindings and configmap when Autopilot is Enabled 
Autopilot - Validate Autopilot serviceaccount, clusterrole, clusterrolebindings and configmap are deleted when Autopilot is Disabled or is nil
Autopilot - Delete Autopilot pod and validate it get re-deployed 
Autopilot - Disable Autopilot by setting enabled to false 
Autopilot - Delete Autopilot all together by removing autopilot block/object or setting it to nil 
Autopilot - …
=> PTX-2758 Autopilot validation and basic regression test

pkg/migration/generate.go
- Do not assume that monitoring APIs are registered. If they are
not then it means the monitoring components are not present
at all. So no need to add anything to the StorageCluster spec.
Closes # https://portworx.atlassian.net/browse/OPERATOR-527
=> OPERATOR-527 Check if the monitoring APIs are registered

pkg/util/test/util.go, test/integration_test/basic_test.go, test/integration_test/utils/storagecluster.go
PVC Controller basic regression test and various improvements for validation of PVC Controller components and images
* Added PVC Controller basic regression test that covers multiple PVC Controller test cases
Validate PVC Controller annotations are missing by default
Enable portworx-pvc-controller in StorageCluster annotations and validate PVC Controller pods are created
Disable portworx-pvc-controller in StorageCluster annotations and validate PVC Controller pods are deleted 
Validate portworx-pvc-controller deployment and pods 
Delete PVC Controller pods and validate pods get re-deployed 
Set custom PVC Controller secure-port in StorageCluster annotations and validate
Delete custom PVC Controller secure-port in StorageCluster annotations and validate ports are changed to default
* Added …
=> PTX-4514 PVC Controller validation and basic regression test

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/testspec/ccmconfig.yaml, drivers/storage/portworx/testspec/px_telemetry_with_proxy.yaml, drivers/storage/portworx/util/util.go
**What this PR does / why we need it**: mount PX_HTTP(S)_PROXY as a configmap to ccm container
Closes # [OPERATOR-438](https://portworx.atlassian.net/browse/OPERATOR-438)
**Special notes for your reviewer**: will add unit tests once verified the functionality manually.
=> [OPERATOR-438] Add portworx proxy support for telemetry ccm container

drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, test/integration_test/testspec/migration/daemonset-with-all-components.yaml
Signed-off-by: pault84 <paul@portworx.com>
OPERATOR-529: CCM 3.0.3 has a big security hole regarding certificates.
3.0.4 fixed this but pushing image to latest for other addressed fixes.
Goes together with a daemon set fix in px-installer.
=> OPERATOR-529: Bump ccm service image

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/testspec/openshift_runc.yaml, drivers/storage/portworx/testspec/pks.yaml, drivers/storage/portworx/testspec/pks_2.9.1.yaml, drivers/storage/portworx/testspec/portworxPodEnvOverride.yaml, drivers/storage/portworx/testspec/px_csi_0.3.yaml, drivers/storage/portworx/testspec/px_csi_1.0.yaml, drivers/storage/portworx/testspec/px_disable_telemetry.yaml, drivers/storage/portworx/testspec/px_k3s.yaml, drivers/storage/portworx/testspec/px_kvdb_certs.yaml, drivers/storage/portworx/testspec/px_kvdb_certs_without_ca.yaml, drivers/storage/portworx/testspec/px_kvdb_certs_without_cert.yaml, drivers/storage/portworx/testspec/px_kvdb_certs_without_key.yaml, drivers/storage/portworx/testspec/px_kvdb_without_certs.yaml, drivers/storage/portworx/testspec/px_master.yaml, drivers/storage/portworx/testspec/px_pks_with_csi.yaml, drivers/storage/portworx/testspec/px_telemetry-with-location.yaml, drivers/storage/portworx/testspec/px_telemetry.yaml, drivers/storage/portworx/testspec/px_telemetry_with_proxy.yaml, drivers/storage/portworx/testspec/runc.yaml, drivers/storage/portworx/testspec/runc_2.9.1.yaml
oci-monitor 2.9.1 has a fix to allow /var/lib/osd mounted as a shared directory,
when the container runtime is cri-o.
Without the oci monitor change, mounting /var/lib/osd is not very useful as it
is not getting mounted as a shared mount. So keeping the old behavior for older
px releases, while mounting /var/lib/osd for 2.9.1 and above.
Closes #
=> OPERATOR-519 Mount /var/lib/osd directly only for px > 2.9.1

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/testspec/metricsCollectorDeployment.yaml, test/integration_test/testspec/metricsCollectorDeployment.yaml
**What this PR does / why we need it**: https://portworx.atlassian.net/browse/OPERATOR-535
Closes #
=> [OPERATOR-535] fix kubectl logs permission issue of metrics collector container

drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/pks_2.9.1.yaml
- For backward compatibility using the `/var/lib/osd` host path even for PKS.
- Continuing to mount `/var/lib/osd/log` from the `/var/vcap/store/lib/osd/log` directory like before.
- As Zoran suggested, mounting `/var/lib/osd` before `/var/lib/osd/log` to keep the old behavior.
Closes # https://portworx.atlassian.net/browse/OPERATOR-519
=> OPERATOR-519 Using /var/lib/osd mount even for PKS

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/components_test.go
This ensures that existing customers don't start seeing metrics
collector on their px upgrade.
Closes # https://portworx.atlassian.net/browse/OPERATOR-540
=> OPERATOR-540 Run metrics collector only for px 2.9.1 and above

pkg/util/test/util.go, test/integration_test/pxrepo_test.go
* adding negative (failed install w/o px-repo) + positive (fixed install w/ px-repo) tests
* adding `ValidateStorageClusterFailedEvents` that can validate "stuck" installation and check K8s events
* modified `validateStorageClusterPods` to take external "POD readyness" eval function
* this is an integration test for `px-repo` component  (will be productized w/ px-2.10.x)
Closes # OPERATOR-398
=> OPERATOR-398: Adding px-repo integration test

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/components_test.go
=> [OPERATOR-549] remove pure-telemetry-certs on uninstallation

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/components_test.go
* remove pure-telemetry-certs on uninstallation
* resolve comments
Closes #
=> [cherry-pick] [OPERATOR-549] remove pure-telemetry-certs on uninstallation (#489)

drivers/storage/portworx/component/portworx_proxy.go, drivers/storage/portworx/components_test.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/update.go
- When running in storage disabled mode, which is mostly used by
PX Central, the operator used to delete the portworx-service
created by the daemonset spec. We specially handle this by ignoring
the deletion of the service when storage is disabled.
- Ignore the GetStorageNodes call when storage is disabled.
Closes # https://portworx.atlassian.net/browse/OPERATOR-301
=> OPERATOR-301 Do not remove portworx-service

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/components_test.go
=> [OPERATOR-549] do not remove pure-telemetry-certs when telemetry is disabled

deploy/crds/core_v1_storagecluster_crd.yaml, go.mod, pkg/apis/core/v1/storagecluster.go, pkg/util/util.go, pkg/util/util_test.go
This is to stop GetImageURN from swallowing part of the image tag when
setting a customImageRegistry with a / in it. Original behaviour is,
when a registry of `example.io/public` is used with an image of
`portworx/oci-monitor`, for the image to become
`emaple.io/public/oci-monitor`. Setting this to true will preserve the
full path and the image will be `example.io/public/portworx/oci-monitor`
Remediates Pure portal ticket #01194532
=> Add preserveFullCustomRegistry to not swallow part of image

deploy/olm-catalog/portworx/1.7.1/core_v1_storagecluster_crd.yaml, deploy/olm-catalog/portworx/1.7.1/core_v1_storagenode_crd.yaml, deploy/olm-catalog/portworx/1.7.1/portworx-certified.clusterserviceversion.yaml
Couple of changes that are in this bundle compared to the 1.7.0 - 
- Added back the v1alpha1 version back to both the CRDs
```
- name: v1alpha1
served: false
storage: false
subresources:
status: {}
schema:
openAPIV3Schema:
type: object
x-kubernetes-preserve-unknown-fields: true
```
- Changed the CSV to skip 1.7.0 as clusters who have used v1alpha1 in the past fail to upgrade because v1alpha1 is still part of the CRD's `status.storedVersions`. OLM should have removed it but it is not doing so.
```
annotations:
+     olm.skipRange: '=1.7.0'
```
Closes # https://portworx.atlassian.net/browse/OPERATOR-579
=> Adding CSV for 1.7.1

deploy/crds/core_v1_storagecluster_crd.yaml, drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/components_test.go, pkg/apis/core/v1/storagecluster.go, pkg/apis/core/v1/zz_generated.deepcopy.go, pkg/util/k8s/k8s.go, pkg/util/test/util.go, pkg/util/util.go, pkg/util/util_test.go, test/integration_test/basic_test.go, test/integration_test/utils/px_operator.go
**What this PR does / why we need it**: To pass custom labels to portworx-api service
Closes # [OPERATOR-543](https://portworx.atlassian.net/browse/OPERATOR-543)
=> [OPERATOR-543] Allow adding custom labels to portworx-api service

pkg/util/test/util.go
Fix AlertManager when object is <nil>
=> PTX-5398 Fix AlertManager when object is <nil>

drivers/storage/portworx/component/auth.go, drivers/storage/portworx/components_test.go, pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/testspec/storkSchedDeployment.yaml, pkg/controller/storagecluster/testspec/storkSchedVersionedDeployment.yaml, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go
For OPERATOR-596: The pod template was using 'name: stork-scheduler' labels in 
the pod antiaffinity, but we were not setting that label. Adding the label now for new
installs only. For existing installs, users will have to delete the scheduler
deployment manually.
Closes # 
https://portworx.atlassian.net/browse/OPERATOR-482
https://portworx.atlassian.net/browse/OPERATOR-596
=> OPERATOR-482, OPERATOR-596 Skip security secrets from PX backup

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, test/integration_test/utils/px_operator.go
**What this PR does / why we need it**: When only node level cloudStorage specs are provided, operator shouldn't set default cluster level storage spec
Closes # [OPERATOR-561](https://portworx.atlassian.net/browse/OPERATOR-561)
=> [OPERATOR-561] Don't initialize default storage spec when only node level cloud storage spec is specified.

drivers/storage/portworx/component/csi.go, drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/components_test.go, pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/stork_test.go, pkg/util/k8s/node.go, pkg/util/k8s/node_test.go, pkg/util/test/util.go, pkg/util/util.go, pkg/util/util_test.go, test/integration_test/basic_test.go, test/integration_test/utils/node.go
**What this PR does / why we need it**: Add pod topology spread constraints to csi, pvc controller, stork and stork scheduler pods.
Closes # [OPERATOR-560](https://portworx.atlassian.net/browse/OPERATOR-560)
=> [OPERATOR-560] Add pod topology spread constraints to stork, pvc and csi pods

drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/util/util.go, pkg/controller/storagecluster/storagecluster.go, pkg/util/k8s/pod.go
**What this PR does / why we need it**: when using Metro DR, operator should exclude storage nodes from other clusters when calculating the pod disruption budget.
Closes #[OPERATOR-562]
=> [OPERATOR-562] Fix pod disruption budget spec issue when using Metro DR

pkg/migration/backup.go, pkg/migration/backup_test.go, pkg/migration/migration.go
backup portworx components that are deployed by daemonset method, if migration to operator fails we can rollback.
https://portworx.atlassian.net/browse/OPERATOR-507
Closes #
=> [OPERATOR-507] - implement daemonset backup

pkg/migration/generate.go, pkg/migration/migration.go, pkg/migration/migration_test.go
-  The 'portworx' secrets namesapce needs to be explicitly added to the storage
cluster during migration. As most daemonset clusters have been using portworx
namespace to store secrets by default. If a secrets namespace is provided
explicitly then we honor that.
-  Some env variables are added by the operator to the portworx pod directly. We
don't need to copy them to the storage cluster.
Closes # https://portworx.atlassian.net/browse/OPERATOR-538
=> OPERATOR-538 Add default secrets namespace if not provided

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/update.go
Fixes case where PX pods were bouncing due the following conditions:
1. Operator was on version 1.7.0
2. STC had CSI enabled w/ featureGate
3. Operator was upgraded to 1.8.0 with CSI.Enabled flag
4. PX pods bounced we noticed a new spec.CSI.Enabled flag, but did NOT check what the feature gate was set to. Unfortunately, we'll always still need check for the previous feature gate value.
OPERATOR-603
I was able to repro this by upgrading from 1.7.0 -> 1.8.0.
Did a manual test w/ upgrading operator 1.7.0 to an image with this change, and the pods were not bounced.
A new unit test also covers the case that I missed …
=> OPERATOR-603: Fix CSI case where op 1.7.0 to 1.8.0 bounced PX pods

drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
Add desired snapshot controller image when empty
OPERATOR-613
=> [CSI] Add desired snapshot controller image when empty

drivers/storage/portworx/manifest/manifest.go
This reverts commit 8afbd3c21fb1aec50bb8490dcd9099f21cb7b129.
2.10.0 wiper is failing due to an issue still to be root caused. I've repushed 2.5.0 as the previously working image.
Closes #
=> Revert "PWX-22998 bump px-node-wiper to 2.10.0 (#542)"

pkg/migration/generate.go, pkg/migration/migration_test.go, test/integration_test/migration_test.go
- 'auto' journal device is supported for both storage and cloud storage. It is a special word treated by portworx. As it does not start with a `/` like a normal device it was getting put in the cloud storage section.
Closes # https://portworx.atlassian.net/browse/OPERATOR-629
=> OPERATOR-629 Fix migration with auto journal device

drivers/storage/portworx/manifest/manifest.go
This reverts commit 93b934c16b65e0464ad16d50d3052d8096e29a03.
node wiper 2.10.0 is fixed now and re-pushed.
Closes #
=> Revert "Revert "PWX-22998 bump px-node-wiper to 2.10.0 (#542)""

pkg/migration/backup.go
the configmap will be update after operator migration, and has ownerRef to storagecluster. If migration fails and user deletes storage cluster, the configmap will be deleted as well. hence we need to backup it.
=> backup px-telemetry-config configmap

drivers/storage/portworx/util/util.go
**What this PR does / why we need it**: pass IPv6 endpoint in format of [ip]:port instead of ip:port
Closes # [OPERATOR-616]
=> [OPERATOR-616] Fix IPv6 endpoint format passed to PX gRPC server

pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/testspec/storkSchedDeployment.yaml, pkg/controller/storagecluster/testspec/storkSchedVersionedDeployment.yaml
In a 3 node cluster, the stork scheduler upgrades were getting stuck because of
the pod anti-affinity policy. The new 4th pod was going in a Pending state and
waiting for one of the existing 3 pods to go down. This was happening because
the default maxUnavailable is 25%. This was preventing the existing pod from
going down, and the pod anti-affinity stopped the new pod from coming up.
Closes # https://portworx.atlassian.net/browse/OPERATOR-666
=> OPERATOR-666 Set maxSurge and maxUnavailable in stork scheduler

go.mod, go.sum, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, vendor/modules.txt
**What this PR does / why we need it**: When recovering to DaemonSet in case of migration failures, migration labels added by operator should be removed.
Closes # OPERATOR-667
=> [OPERATOR-667] Node migration labels should be removed when deleting a StorageCluster.

go.mod, go.sum, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, vendor/modules.txt
=> [OPERATOR-667] Node migration labels should be removed when deleting a StorageCluster

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/deployment.go, pkg/controller/storagecluster/storagecluster.go, pkg/migration/backup_test.go, pkg/migration/dryrun.go, pkg/migration/dryrun_test.go, pkg/migration/migration.go, pkg/migration/migration_test.go, pkg/mock/storagedriver.mock.go, pkg/util/util.go
Dry run capability:
- Validate portworx pod spec before/after migration, raise warning event if the spec is different
- Block migration if k8s version is lower than 1.16
=> [OPERATOR-506] add migration dry-run support

pkg/util/util.go, pkg/util/util_test.go
**What this PR does / why we need it**: Custom registry images could have multiple `:` in them
Closes # OPERATOR-700
=> [OPERATOR-700] Fix wrong csi-external-provisioner args when using custom registries with ports

pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/testspec/storkSchedClusterRole.yaml
Signed-off-by: Luke Pitstick <lpitstick@purestorage.com>
Add update pvc permission to stork so the stork-scheduler can modify the pvc in WaitForFirstConsumer scenario (PWX-23693)
Closes # PWX-23693
=> PWX-23693 Add update pvc permission to stork

pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/testspec/storkSchedClusterRole.yaml
Add update pvc permission to stork so the stork-scheduler can modify the pvc in WaitForFirstConsumer scenario (PWX-23693)
Closes # PWX-23693
=> [cherry pick to 1.9] PWX-23693 Add update pvc permission to stork (#613)

pkg/dryrun/dryrun.go, pkg/dryrun/validation.go, pkg/migration/generate.go
here is the new output of the tool:
```
operator# ksys exec -it portworx-operator-6977cdcbd4-5nzmx -- /dryrun
INFO[0001] k8s version is v1.20.15                      
INFO[0001] Reconciling StorageCluster                    Request.Name=px-cluster-ad6dc338-d754-49a8-ab42-a98ce7488f67 Request.Namespace=kube-system
WARN[0001] Found mountPath conflict for volume containerdsock at /run/containerd, volume will be ignored 
INFO[0001] Operator will deploy 60 objects, saved to folder /tmp/portworxSpecs 
INFO[0003] Got 41 objects from k8s cluster, will compare with objects installed by operator 
INFO[0003] Portworx will be deployed via Pod scheduled by operator (instead of DaemonSet) 
WARN[0003] failed to compare Deployment stork-scheduler, Containers are different: container stork-scheduler is …
```
=> reduce log

pkg/migration/generate.go, pkg/migration/migration_test.go
=> [CP][OPERATOR-651] Set PreserveFullCustomImageRegistry during migration

drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/components_test.go, pkg/util/k8s/k8s.go, pkg/util/util_test.go
**What this PR does / why we need it**: Support custom annotation for services: portworx-service, portworx-api, portworx-kvdb-service
Closes # OPERATOR-726
=> [OPERATOR-726] Add custom annotation support to different portworx services

drivers/storage/portworx/component/lighthouse.go, drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/util/util.go, drivers/storage/portworx/util/util_test.go, pkg/migration/generate.go, pkg/migration/migration_test.go, pkg/util/k8s/k8s_test.go
**What this PR does / why we need it**: Allow to use service type annotation to control multiple services, backward compatible.
Closes # OPERATOR-725
=> [OPERATOR-725] Add granular control over service types

drivers/storage/portworx/component/csi.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s116.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s120_with_topology.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s120_without_snapcontroller.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s123.yaml, test/integration_test/basic_test.go, test/integration_test/pxrepo_test.go, test/integration_test/utils/storagecluster.go
* Enable csi snapshot controller by default
* Scan all pods once on operator start to find if there's a snapshot controller preinstalled
* Skip installing the snapshot controller if found preinstalled controller
* User need to delete existing controller and restart operator to use operator managed controller
Closes #OPERATOR-719
=> [OPERATOR-719] Enable CSI snapshot controller by default

drivers/storage/portworx/component/lighthouse.go, drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/util/util.go, drivers/storage/portworx/util/util_test.go, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go, pkg/util/util_test.go
**What this PR does / why we need it**: Cherry-picked from 1.9.0 branch to 1.8.1. Service type migration change is not added as some dependencies required are not in 1.8.1.
Closes #
=> [CP][OPERATOR-725][OPERATOR-726] Granular service type control and custom service annotations

pkg/util/test/util.go, test/integration_test/azure_disk_test.go, test/integration_test/main_test.go, test/integration_test/operator-test-pod-template.yaml, test/integration_test/test-deploy.sh, test/integration_test/utils/constants.go, test/integration_test/utils/storagecluster.go
disEncryptionSetID can be passed in the StorageCluster deviceSpecs to use the specific key associated with this disk encryption set for encryption in an AKS cluster. With this PR we are adding two test cases to test PX installation with this param.
Closes #PWX-24421
Test [**InstallWithInvalidDiskEncryptionSetID**] : Pass "invalid" diskEncryptionSetID in the device spec and check for NodeStartFailure event from K8.
Test[**InstallWithInvalidDiskEncryptionSetID**] : Pass a valid diskEncryptionSetID using --portworx-device-specs in the integration test param and PX installation should succeed.
=> PWX-24421: Adding azure disk encryption integration test.

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/status.go, drivers/storage/portworx/uninstall.go, drivers/storage/portworx/util/util.go, pkg/migration/generate.go, pkg/migration/migration.go, pkg/migration/migration_test.go
**What this PR does / why we need it**: During migration if the cluster ID in DaemonSet cannot be a valid k8s object name, format the ID and save the original ID to STC annotation, so kvdb path and existing configmap names are not messed up.
Closes #
=> [OPERATOR-816] Handle clusterID with special characters during migration

pkg/util/test/util.go
Operator integration tests were failing on AKS in the function validatePvcControllerPorts with error `14:33:08 2022/08/02 21:28:27 failed to validate secure-port, secure-port is missing from annotations in the StorageCluster, but is found in the PVC Controler pod portworx-pvc-controller-99f55f488-5q79p Next retry in: 20s`
Azure --secure-port get updated to value  AksPVCControllerSecurePort = "10261" in pvc controller irrespective of the StorageCluster annotation.  Updating this function to compare  secure-port against this value in case of AKS.
=> PWX-24825: Check for a specific secure port in pvc controller for AKS.

Makefile, deploy/ccm/ccm.properties, deploy/ccm/config_properties_px.yaml, deploy/ccm/envoy-config-register-customer-proxy.yaml, deploy/ccm/envoy-config-register.yaml, deploy/ccm/envoy-config-rest.yaml, deploy/ccm/phonehome-cluster.yaml, deploy/ccm/registration-service.yaml, deploy/ccm/secret-manager-role-binding.yaml, deploy/ccm/secret-manager-role.yaml, deploy/ccm/stc-reader-role-binding.yaml, deploy/ccm/stc-reader-role.yaml, deploy/ccm/tls_certificate_sds_secret.yaml, deploy/crds/core_v1_storagecluster_crd.yaml, drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/component/telemetry_java.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/util/util.go, pkg/apis/core/v1/storagecluster.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/update.go, pkg/util/k8s/k8s.go, pkg/util/util.go
**What this PR does / why we need it**: telemetry ccm-go integration
Notes:
* ccm go is supported on PX 2.12+ only, older version will install ccm java
* when px upgrade to 2.12, if old ccm java is enabled, operator will upgrade to ccm go automatically , so telemetryProxy image must be available from manifest, otherwise should continue running old ccm java
* when px upgrade to 2.12, if old ccm java is enabled, but image is set explicitly, operator will reset the image and upgrade ccm
* during ccm upgrade, once old ccm components are deleted, operator will start creating new components. However it doesn't wait for all telemetry containers teardown in px pods.
* when disable telemetry, it will try to do a cleanup for both ccm java and ccm go …
=> ccm-go integration

drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/portworxAPIService.yaml, drivers/storage/portworx/testspec/portworxAPIService_pre_29.yaml, drivers/storage/portworx/testspec/portworxService.yaml, drivers/storage/portworx/testspec/portworxService_pre_29.yaml, drivers/storage/portworx/testspec/pxProxyService.yaml, drivers/storage/portworx/testspec/pxProxyService_pre_29.yaml, drivers/storage/portworx/util/util.go
Add TLS ports (default to 9023) to portworx-service and portworx-api to modern px versions
Closes #PWX-17988
=> PWX-17988 - Add TLS port to portworx service

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/component/telemetry_java.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/util/util.go
1. Add missing scc configuration for ocp environment to allow pod creation in custom namespace.
* service account px-telemetry
* cluster role px-telemetry
* cluster role binding px-telemetry
2. Add metrics collector back to ccm-go components
Closes #
=> [PWX-26146][PWX-26177] Add ccm-go missing scc configuration and metrics collector

deploy/ccm/phonehome-cluster.yaml, deploy/ccm/px-telemetry-role-binding.yaml, deploy/ccm/px-telemetry-role.yaml, deploy/ccm/registration-service.yaml, deploy/ccm/secret-manager-role-binding.yaml, deploy/ccm/secret-manager-role.yaml, deploy/ccm/stc-reader-role-binding.yaml, deploy/ccm/stc-reader-role.yaml, drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/component/telemetry_java.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/util/util.go
* use new custom envoy proxy image for telemetry components, which has cert check embedded
* update all telemetry component names to be px specific
* metrics collector upgrade: completely delete old components and deploy new components with new names
* add cert check init container to new metrics collector pod
* combine role/rolebinding used by registration, phonehome and collector into one.
Closes #
sample: all new telemetry components
```
$ kubectl get serviceaccount -n kube-system | grep px-telemetry
px-telemetry                         1         12m
$ kubectl get clusterrole | grep px-telemetry
px-telemetry …
```
=> [PWX-26142][PWX-26222]Use new envoy image in init containers and update all ccm-go component names

deploy/ccm/phonehome-cluster.yaml, drivers/storage/portworx/component/telemetry_java.go
**What this PR does / why we need it**: security context is missing in init container when using ocp
Closes #
=> [PWX-26222] Fix security context in ccm-go init containers

deploy/olm-catalog/portworx/1.9.0/portworx-certified.clusterserviceversion.yaml, pkg/cloudprovider/cloudprovider.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go
A default value for max_storage_nodes_per_zone will be set when
the cluster is created afresh. This change does not effect existing installs
or upgrades.
The value will be determined as follows
________________________________
Zones | Default value | total nodes
______________________________
1   |      3        |   3
2   |      2        |   4
3   |      1        |   3
4   |      1        |   4
Closes #
Testing: Created a new cluster on vSphere, GCE and AWS and verified that it works for 1, 2, 3 & 4 zones
**GCE:
2 zones:
"max_storage_nodes_per_zone": 2,**
root@gke-nrevanna-cluster-2-z-default-pool-0cf395ca-wp2l:/# pxctl status | grep gke-nrevanna| wc -l
4 …
=> PWX-24024: Default value for max_storage_nodes_per_zone

drivers/storage/portworx/component/csi.go, drivers/storage/portworx/components_test.go
**What this PR does / why we need it**: If `installSnapshotController` is true in stc spec, during operator upgrade it will treat the existing operator deployed snapshot controller as external one, then remove it from px-csi-ext deployment.
Closes #
=> [PWX-26670] Filter out px-csi-ext pods when scanning pre-installed snapshot controllers

drivers/storage/portworx/component/csi.go, drivers/storage/portworx/components_test.go
=> [1.9.1][PWX-26670] Filter out px-csi-ext pods when scanning pre-installed snapshot controllers

test/integration_test/utils/storagecluster.go
Hardcode maxStorageNodesPerZone to 5 for CloudStorage to pass DeepEquals validation until we have a better method to do this
=> PTX-12727 Hardcode maxStorageNodesPerZone for CloudStorage

deploy/ccm/ccm.properties, deploy/ccm/config_properties_px.yaml, deploy/ccm/envoy-config-collector-custom-proxy.yaml, deploy/ccm/envoy-config-collector.yaml, deploy/ccm/envoy-config-register-custom-proxy.yaml, deploy/ccm/envoy-config-register.yaml, deploy/ccm/envoy-config-rest-custom-proxy.yaml, deploy/ccm/metrics-collector-deployment.yaml, deploy/ccm/phonehome-cluster.yaml, drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/component/telemetry_java.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/ccmGoCollectorConfigMap.yaml, drivers/storage/portworx/testspec/ccmGoCollectorDeployment.yaml, drivers/storage/portworx/testspec/ccmGoCollectorProxyConfigMap.yaml, drivers/storage/portworx/testspec/ccmGoPhonehomeConfigMap.yaml, drivers/storage/portworx/testspec/ccmGoPhonehomeDaemonSet.yaml, drivers/storage/portworx/testspec/ccmGoRegisterConfigMap.yaml, drivers/storage/portworx/testspec/ccmGoRegisterDeployment.yaml, drivers/storage/portworx/util/util.go, pkg/migration/cleanup.go, pkg/migration/migration_test.go
* rewrite metrics collector V2 code and don't reuse V1
* port shifting issue fixed
* configmap and deployment content validation added in unit tests
* metrics collector now use shifted ports based on px start port, and support custom proxy
* make phonehome envoy port configurable
Closes #
passed automation https://jenkins.pwx.dev.purestorage.com/view/Newstack%20Dashboard/job/Operator/job/operator-integration-basic-dev/1/console
=> [PWX-26381][PWX-26696][PWX-26768] Add custom proxy and port shifting support for metrics collector

pkg/cloudprovider/cloudprovider.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go
* PWX-24024: Default value for max_storage_nodes_per_zone
A default value for max_storage_nodes_per_zone will be set when the cluster is created afresh. This change does not effect existing installs or upgrades.
The value will be determined as follows Zones | Default value | total nodes ------------------------------------
1   |      3        |   3
2   |      2        |   4
3   |      1        |   3
>4   |      1        |  >4
Closes #
Cherry-picking from master.
=> PWX-24024: First Install: Default value for max_storage_nodes_per_zone (#711)

pkg/apis/core/v1/storagecluster.go
Planning to add automatic crd manifest generation so that we don't have to update both the golang object and crd schema. Going to use controller-tools to do that. Will add the generation in a later PR.
Closes #
=> Add missing json labels for manifest generation

test/integration_test/basic_test.go, test/integration_test/migration_test.go, test/integration_test/utils/constants.go, test/integration_test/utils/storagecluster.go
Reduced test execution time by 50%
1. dedupe BasicInstallWithAllDefaults (tested with upgrade test cases)
2. avoid uninstall and reinstall px in very test function
3. reduce interval when waiting for desired status.
=> improve functional test performance

pkg/migration/generate.go, pkg/migration/migration_test.go
* truncate cluster id and store the original one in annotation
Closes #
=> [PWX-27219] Truncate clusterID during migration if longer than 63 chars

test/integration_test/test-deploy.sh
When adding GKE support we are using google/cloud-sdk container which is a Debian image. Operator test container assumes this container image to be Alpine. 
Closes #PWX-24830
These changes were removed in the following commit https://github.com/libopenstorage/operator/pull/234/files
=> PWX-24830: Adding apt-get to support debian container test image.

drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/component/telemetry_java.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/pvcControllerClusterRole.yaml, drivers/storage/portworx/testspec/pvcControllerDeployment_k8s_1.24.yaml, pkg/util/test/util.go
[PWX-27353] Update PVC controller deployment and cluster role on k8s 1.24+
[PWX-27401] Disable metrics collector if it's not already running
Closes #
[PWX-27353]: https://portworx.atlassian.net/browse/PWX-27353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PWX-27401]: https://portworx.atlassian.net/browse/PWX-27401?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PWX-27353][PWX-27401] PVC controller fix and disabling metrics collector

drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/component/portworx_crd.go, drivers/storage/portworx/component/portworx_proxy.go, drivers/storage/portworx/manifest/remote.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/status.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/update.go, pkg/util/k8s/k8s.go, pkg/util/k8s/node.go, pkg/util/k8s/pod.go
We will make operator use info level by default, hence these log entries need to be info in order to show up in operator log. the criteria for using info log instead of debug is it wont generate lot of log entries.
=> PWX-26741 adjust some logs from debug to info

pkg/util/util.go, pkg/util/util_test.go
k8s will move from k8s.gcr.io to registry.k8s.io, add this new registry as common registry, so if an image has the prefix it's handled correctly when replacing with custom registry. this is just a proactive change. at this moment we may not have any image in the new registry yet.
=> PWX-27538 add registry.k8s.io as common registry

drivers/storage/portworx/component/csi.go, drivers/storage/portworx/testspec/csiDeploymentAlphaDisabledK8s_1_14.yaml, drivers/storage/portworx/testspec/csiDeploymentAlphaDisabledK8s_1_16.yaml, drivers/storage/portworx/testspec/csiDeploymentWithPKS.yaml, drivers/storage/portworx/testspec/csiDeploymentWithResizerAndOldDriver_1.0.yaml, drivers/storage/portworx/testspec/csiDeploymentWithResizer_1.0.yaml, drivers/storage/portworx/testspec/csiDeploymentWithResizer_1_17.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s116.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s120.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s120_with_topology.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s120_without_snapcontroller.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s123.yaml, drivers/storage/portworx/util/util.go, pkg/util/util.go, pkg/util/util_test.go
When CSI is enabled  PVC provisioning goes through px-csi-ext-* pods which is a deployment of 3 replicas. If these 3 PX nodes go offline none of the PVC creations would succeed even if the PX cluster is operational. In such cases we need to move the px-csi-ext pods to other nodes in the cluster.
This change will make Stork as the default scheduler for px-csi-ext-* pods. Change will be made in Stork to detect px-csi-ext pods are running on an offline PX node such that it can delete the csi-ext pod and schedule them on the online nodes.
Closes #https://portworx.atlassian.net/browse/PWX-27563
* Refer to …
=> PWX-27563: Setting stork as the default scheduler for px-csi-ext pods

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/util/util.go
The previous default of 3 storage nodes did not fit for all cluster
sizes. This change will pick a default value during install based on
1. If portworx.io/node-type=storage is specified, total number of
storage nodes will be used to calculate maxStorageNodesPerZone
2. If label is not specified, total nodes in the cluster will be the
number of storage nodes
maxStorageNodesPerZone = (total storage nodes)/ (number of zones)
Signed-off-by: Naveen Revanna <nrevanna@purestorage.com>
Closes #
Testing: Tests added
=> PWX-27591: Default value for maxStorageNodesPerZone

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/util/util.go
* PWX-27591: Default value for maxStorageNodesPerZone
The previous default of 3 storage nodes did not fit for all cluster
sizes. This change will pick a default value during install based on
1. If portworx.io/node-type=storage is specified, total number of
storage nodes will be used to calculate maxStorageNodesPerZone
2. If label is not specified, total nodes in the cluster will be the
number of storage nodes
maxStorageNodesPerZone = (total storage nodes)/ (number of zones)
Signed-off-by: Naveen Revanna <nrevanna@purestorage.com>
Closes #
=> PWX-27591: Default value for maxStorageNodesPerZone (#810)

drivers/storage/portworx/portworx.go, go.mod, pkg/cloudprovider/azure.go, pkg/cloudprovider/cloudprovider.go, pkg/cloudprovider/cloudprovider_test.go, vendor/modules.txt
* PWX-27783: Add more zone labels
In vSphere, we allow customers to tag VMs with zone. Operator needs
to recognize that and base it's decision of maxStorageNodesPerZone
based on that. Currently, the change is in the default cloud
provider. Clouds like GKE, EKS etc don't use that label. Hence we can
have them also check and that will have no effect. This will solve
the problem for vSphere. In a future release we can separate out the
cloud providers.
Signed-off-by: Naveen Revanna <nrevanna@purestorage.com>
Closes #
=> PWX-27783: Add more zone labels (#822)

pkg/migration/migration.go, pkg/util/test/util.go, test/integration_test/migration_test.go, test/integration_test/testspec/migration/simple-daemonset.yaml
* Check external snapshot controller during csi validation
* Add migration node affinity only once
* Add sleep before start migration because node initialization may be in progress 
Closes #
=> [PWX-27886][PWX-27891] DaemonSet migration feature and test improvement

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go
Master nodes are counted towards total nodes while counting default
value for maxStorageNodesPerZOne. This fixes that
Signed-off-by: Naveen Revanna <nrevanna@purestorage.com>
Closes #
Testing:
Verified that maxStorageNodesPerZone is 5 for the below
> kn get nodes
NAME                          STATUS   ROLES                  AGE   VERSION
nrevanna-vms-luminous-foe-0   Ready    <none>                 33d   v1.21.1
nrevanna-vms-luminous-foe-1   Ready    <none>                 33d   v1.21.1
nrevanna-vms-luminous-foe-2   Ready    <none>                 33d   v1.21.1
nrevanna-vms-luminous-foe-3   Ready    control-plane,master   33d   v1.21.1
nrevanna-vms-luminous-foe-4 …
=> PWX-27901: Count accurate number of total nodes

cmd/operator/operator.go, drivers/storage/portworx/component/tls.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/status_test.go, drivers/storage/portworx/util/util.go, drivers/storage/portworx/util/util_test.go, pkg/controller/storagecluster/storagecluster.go
* adding new 'is-auto-tls' annotation
* this annotation initiates automatic SSL setup for porx
* gRPC-dialing now automatically adds K8s CA, since porx APIs will also switch to SSL-mode
* modified access to `portworx-service` to use K8s DNS, rather than ClusterIP
Additional:
* added support for `--trace` logging option
This is adding the support, and setup for "automatic SSL" for Portworx
Closes #  PWX-25288   (part 2)
This change depends on https://github.com/portworx/px-installer/pull/1497 for OCI-Monitor  (<< linked to ClusterIP change)
Unit-tests pending
=> PWX-25288-pt2: Adding support for 'auto-tls'

test/integration_test/Dockerfile, test/integration_test/test-deploy.sh
Modified operator tests to run from container
Closes https://portworx.atlassian.net/browse/PTX-13942
With above changes we don't need any other containers and operator repository. The test run command will look like this:
```
docker run --rm -t -v ${KUBECONFIG_PATH}:/tmp/kubeconfig -e KUBECONFIG=/tmp/kubeconfig --entrypoint /bin/bash px-operator-test:master /test-deploy.sh --operator-test-image px-operator-test:master --log-level debug --short-test true --focus-tests ${FOCUS_TEST} --portworx-spec-gen-url ${URL}/${ENDPOINT} --portworx-docker-username **** --portworx-docker-password ****
```
=> PTX-13942 Modified operator tests to run from container

drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx.go
Adding support for automatic TLS/SSL support for AutoPilot
As a fix, we have to add the `PX_ENABLE_TLS="true"` env-var when [auto] TLS has been enabled.
Closes # PWX-26915  (part 2)
=> PWX-26915_pt2: Fixing AutoSSL for AutoPilot

drivers/storage/portworx/cloud_storage.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, vendor/github.com/libopenstorage/cloudops/aws/storagemanager/aws.go, vendor/modules.txt
* if cloud storage capacity spec is configured on EKS, operator will use that to create cloud drives
Closes # PWX-27588
spec to deploy px on eks
```
spec:
cloudStorage:
capacitySpecs:
- minCapacityInGiB: 300
minIOPS: 3000
maxStorageNodesPerZone: 1
```
pod args generated from decision matrix:
```
- -cloud_provider
- aws
- -s
- type=gp3,size=12,iops=3000
- -s
- type=gp3,size=12,iops=3000
- -s
- type=gp3,size=12,iops=3000
- -s
- type=gp3,size=12,iops=3000
- -s
- type=gp3,size=12,iops=3000
- -s
- type=gp3,size=12,iops=3000
- -s
- type=gp3,size=12,iops=3000
- -s
- type=gp3,size=12,iops=3000
- -max_storage_nodes_per_zone
- "1"
```
pxctl status
```
Status: PX is operational …
```
=> [PWX-27588] Add support for EKS cloud storage capacity based configuration

pkg/util/test/util.go
Fixing stork-scheduler image validation failure
Closes # PWX-28312
opVersion.LessThanOrEqual(opVer1_10_1)  -> "1.10.1".LessThanOrEqual("1.10.1-") check resolves to false. I realized it's better to use minOpVersionForKubeSchedConfig and check for versions lower than this version. 
I tested operator-integration-basic and operator-integration-telemetry test with this and they are passing 
https://jenkins.pwx.dev.purestorage.com/job/Operator/view/Operator%20Release%20Dashboard/job/operator-integration-basic/489/console
https://jenkins.pwx.dev.purestorage.com/job/Operator/view/Operator%20Release%20Dashboard/job/operato …
=> PWX-28312: Fix stork-scheduler image validation failure

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
* use totalCapacity/storageNodesCount to calculate the EKS cloud drive spec, don't use the decision matrix for now
Closes # PWX-27588
spec:
```
spec:
cloudStorage:
capacitySpecs:
- minCapacityInGiB: 500
options:
type: gp3
maxStorageNodesPerZone: 1
```
args
```
- -s
- size=166,type=gp3
```
pxctl status
```
sh-4.4# /opt/pwx/bin/pxctl status
Status: PX is operational
Telemetry: Disabled or Unhealthy
Metering: Disabled or Unhealthy
License: Trial (expires in 31 days)
Node ID: 9cb18810-2b38-447e-99fe-8fa6ad1d987a
IP: 172.31.36.44
Local Storage Pool: 1 pool
POOL	IO_PRIORITY	RAID_LEVEL	USABLE	USED	STATUS	ZONE		REGION
0	HIGH		raid0		166 GiB	8.3 GiB	Online	us-east-1c	us-east-1 …
```
=> [PWX-27588] Calculate EKS cloud drive spec using totalCapacity/storageNodesCount

drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx.go
* manage "PX_ENABLE_TLS=true" env var for both Autopilot and Stork, depending on the TLS-setup
* updated UTs
We need to manage the `PX_ENABLE_TLS=true` environment variable both for Stork and Autopilot components
* refactored code accordingly, updated UTs
* note, the `PX_ENABLE_TLS=true` environment variable for Stork and Autopilot will be managed exclusively by PX-Operator, and it will depend on the global `security: tls: enabled` setting
Closes #  PWX-28189  (part 2)
~This change depends on the update from https://github.com/libopenstorage/openstorage/pull/2169 -- review and go-vendor pending~
* **UPDATE**: the …
=> PWX-28189_pt2: Auto-TLS/SSL support for stork

pkg/util/test/util.go
Increase defaultTelemetryInPxctlValidationTimeout, due to 5 mins is not enough sometimes. Seems sometimes when infra is overloaded, 5 mins is not enough to bounce PX pods and start PX on all nodes.
=> PTX-14810 Increase defaultTelemetryInPxctlValidationTimeout due to 5 mins is not enough sometimes

pkg/util/test/util.go
Fix stork-scheduler pod validation for 1.10.2+
NOTE: Looks like for version formats for operator we need to add `-` at the end
=> PTX-14937 Fix stork-scheduler pod validation for 1.10.2+

pkg/util/test/util.go, test/integration_test/utils/px_operator.go
During PR automation, operator tag such as "1a6a788" and be parsed into "1.0.0-a6a788"
Closes #
=> [PWX-28585] Avoid parsing git sha to valid operator versions in automation

cmd/operator/operator.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/portworx_test.go, pkg/cloudprovider/cloudprovider_test.go, pkg/controller/storagecluster/controller_test.go, pkg/preflight/aws.go, pkg/preflight/aws_test.go, pkg/preflight/preflight.go, pkg/preflight/preflight_test.go
* When AWS credentials are provided in stc env, preflight check will use that to create a client to check cloud permission instead of using privileged instances.
* User can modify specified credentials and retrigger preflight check again.
* Credentials can be passed from string or k8s secret object
Closes #
Test manually:
1. without privileged instances, preflight respond 403 error in the condition list
2. with wrong credentials provided then rerun preflight, got a different 401 error in the condition list
3. update stc to use correct credentials then rerun preflight, px is deployed successfully
4. uninstall and add privileges to node group iam, remove aws credentials, …
=> [PWX-27622] Use provided AWS credentials to run permission check on EKS

README.md, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/util/util.go
Signed-off-by: Shivanjan Chakravorty [schakravorty@purestorage.com](mailto:schakravorty@purestorage.com)
What this PR does / why we need it:
PX Operator allows to pass a non standard kubelet config path and setup the csi sidecars accordingly
Which issue(s) this PR fixes
PX Operator should allow to pass a non standard kubelet config path and setup the csi sidecars accordingly
Closes https://github.com/libopenstorage/operator/pull/879
=> read custom kubelet path from env

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/stork_test.go, pkg/controller/storagecluster/testspec/storkSchedDeployment.yaml
PDB v1 was supported starting k8s 1.21, this PR changed min k8s version from 1.12.0 to 1.21.0 so it throws an error at a lower version than 1.21. 
Closes #
=> [PWX-28134] Update k8s min version for PDB

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/component/telemetry_java.go, drivers/storage/portworx/components_test.go, pkg/controller/storagecluster/stork.go, pkg/migration/backup.go, pkg/util/k8s/k8s.go
* when ccm config got updated during operator upgrade, phonehome doesn't reload the latest config, so restarting all phonehome pods as a workaround for now.
Closes #
=> [PWX-28868] Restart telemetry phonehome DaemonSet when ccm ConfigMap gets updated

pkg/util/test/util.go, test/integration_test/regression_test.go, test/integration_test/testspec/apps/nginx-no-volumes/nginx-no-volumes-app.yaml, test/integration_test/utils/constants.go, test/integration_test/utils/fafb_config.go, test/integration_test/utils/storagecluster.go
Improve validation for PX pods and add automation test case to cover issue that was found in CEE-744
Test case is to restrict from PX pods to be scheduled on a specific node due to resource limit (CPU) and then remove load to unblock CPU limit and validate PX is getting provisioned on the node as expected
Also some validation improvements
=> PTX-15283 Improve validation for PX pods and add automation test case to cover issue that was found in CEE-744

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/component/telemetry_java.go, drivers/storage/portworx/util/util.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go
When storageCluster delete strategy is changed and then uninstalled, telemetry reconcile may not uninstall correctly as reconcile loop needs 30s to reconcile according to delete strategy. hence add the fix in finalizer of storagecluster.
=> PWX-26956 handle telemetry cert owenrRef in storageCluster finalizer

Makefile, build/Dockerfile, drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx.go, test/integration_test/basic_test.go, test/integration_test/utils/px_operator.go
* Enable telemetry by default on PX 2.12+ (ccm-go) if custom proxy not specified or cluster is not air-gapped
* Update telemetry regression test
Closes #
telemetry regression test: telemetry is enabled by default https://jenkins.pwx.dev.purestorage.com/view/Newstack%20Dashboard/job/Operator/job/operator-integration-basic-master/207/console
=> [PWX-26954] Enable telemetry by default on PX 2.12+

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/update.go, pkg/controller/storagenode/storagenode.go, pkg/util/k8s/k8s.go, pkg/util/util.go
…
* During fresh install objects created by operator could be modified by k8s, causing operator failing to update them and raising error "the object has been modified; please apply your changes to the latest version and try again"
* Tolerant error above in operator reconcile loops
* Do a get before updating stc and update the object revision to avoid hitting revision conflicts
* Fixed the issue stc status showing Degraded during fresh install
Closes # PWX-28659
=> [pwx-28659] Get live StorageCluster to update and tolerant revision conflict errors

pkg/client/clientset/versioned/fake/register.go, pkg/client/clientset/versioned/scheme/register.go, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go
* Add annotation to PrometheusRule to enable/disable reconciliation of rule spec.
[Ticket](https://portworx.atlassian.net/browse/PWX-27168)
**Test**
k edit prometheusrule, add annotation:
```
metadata:
annotations:
operator.libopenstorage.org/reconcile: "0"
```
Update alert in rule spec. Save change and wait for a while. 
Verify the alert change is not rolled back by operator.
Then change reconcile flag to "1", verify the alert change is rolled back.
=> [PWX-27168] Add annotation to disable reconciliation of Prometheus alerts

drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/status.go, drivers/storage/portworx/status_test.go, drivers/storage/storage.go, pkg/apis/core/v1/storagecluster.go, pkg/apis/core/v1/storagenode.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/update.go, pkg/controller/storagenode/storagenode.go, pkg/mock/storagedriver.mock.go, pkg/util/util.go, pkg/util/util_test.go
* Add `Updating` status to StorageNode `NodeState` condition
* Compare px pod has with StorageNode hash to check if StorageNode is updated
Closes # PWX-28655
install in progress
```
- lastTransitionTime: "2023-02-28T23:11:53Z"
message: Portworx installation completed on 0/4 nodes, 4 nodes remaining
source: Portworx
status: InProgress
type: Install
```
```
- lastTransitionTime: "2023-02-28T23:16:08Z"
message: Portworx installation completed on 1/4 nodes, 3 nodes remaining
source: Portworx
status: InProgress
type: Install
```
```
- lastTransitionTime: "2023-02-28T23:17:52Z"
message: Portworx installation completed on 4 nodes
source: Portworx
status: Completed
type: …
```
=> [pwx-28655] Add Portworx Install and Upgrade conditions to StorageCluster status

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/component/telemetry_java.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/manifest/remote.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/util/util.go, drivers/storage/portworx/util/util_test.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go
* Fresh install, telemetry will be enabled if
* PX is 2.12+, so ccm-go is supported
* telemetry is not disabled explicitly in the spec
* no PX_HTTP_PROXY or PX_HTTPS_PROXY is specified in stc spec
* no air-gapped, operator can reach to the registration endpoint
* Upgrade case:
* if fresh install conditions above are met during upgrade, telemetry will be enabled by default
* if already using telemetry enabled with proxy:
* using PX_HTTP_PROXY in format of host:port or http://host:port, telemetry will be still enabled. this is the basic http proxy we have verified already, can be turn off at anytime
* using http proxy but with auth, e.g. http://user:pass@host:port , telemetry will be disabled as this format is not supported yet
* using PX_HTTPS_PROXY …
=> [pwx-26954] Disable telemetry if it's enabled with custom proxy

test/integration_test/bluegreen_test.go
Adding cleanup of test volume/snapshot
The tests include decommission of the px-nodes
* however, the test will sporadically fail, if the volume/snapshot has been created on the node we're attempting to decommission
* as a fix, we'll clean up the test volume/snapshot, so decommission should not complain about "destroying unique volumes"
Closes #  PWX-26175 (part 2)
This is a re-post of [now closed] https://github.com/libopenstorage/operator/pull/981
=> PWX-26175-r2: Fixing license extension tests

drivers/storage/portworx/component/csi.go, drivers/storage/portworx/component/lighthouse.go, drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/component/securitycontextconstraints.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/csiClusterRole_k8s_1.11.yaml, drivers/storage/portworx/testspec/csiClusterRole_k8s_1.13.yaml, drivers/storage/portworx/testspec/csiClusterRole_k8s_1.14.yaml, drivers/storage/portworx/testspec/lighthouseClusterRole.yaml, drivers/storage/portworx/testspec/portworxRestrictedSCC.yaml, drivers/storage/portworx/testspec/portworxSCC.yaml, drivers/storage/portworx/testspec/pvcControllerClusterRole.yaml
Add a scc portworx-restricted, and use it for stork, csi, pvc controller, lighthouse.
Ticket: https://portworx.atlassian.net/browse/PWX-27673
**Test**:
Upgrade operator with my test image, and delete one pod of each kind, and verify the pod is back to running state. Confirmed "Updating security context constraints" only show 1 time.
=> Add portworx-restricted scc

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
In disaggregated mode, there could be zones in which no storage nodes
might be present. Such a zone would make the maxSNPZ value to be 0.
CHanging the behavior to ignore 0 nodes in a zone for maxSNPZ
calculation.
Closes #
Testing:
1. Added unit test
2. Manually test on a cluster of 4 nodes. 3 were labelled storage and were labelled to be in a `zone`. The 4th one did not have any zone label or storage/storageless label. Before the fix, maxSNPZ was not set (defaults to 0). After the fix, it was set to 3
```
$kn get stc px-with-fix-7bbc65af-8132-463f-a3fc-9b0dc48546de -oyaml| grep max
maxStorageNodesPerZone: 3
maxUnavailable: 1
```
=> PWX-29409: Ignore zones with no nodes

drivers/storage/portworx/portworx.go, drivers/storage/portworx/preflight.go, pkg/controller/storagecluster/storagecluster.go
Modify operator to execute a pre-flight on each node in the cluster.  This pre-flight will actually be executed by oci-monitor and px-runc installed on the host.   The pre-flight will determine if DMthin can be enabled on the cluster.   We do this by having operator launch a daemonset using the storage config with an extra pre-flight option.  This will cause oci-monitor to run in pre-flight mode which executes checks via px-runc on each node.   The results of the check are passed to oci-monitor via a json file. They are read  in and added to the StorageNode obj and passed to operator.  Once the checks are done this pre-flight daemonset is deleted by the operator.   The operator processes the checks returned in the StorageNode obj to determine if the …
=> PWX-28826: Handle pre-flight check for DMthin 

cmd/operator/operator.go, pkg/apis/portworx/v1/portworxdiag.go, pkg/controller/portworxdiag/controller_test.go, pkg/controller/portworxdiag/portworxdiag.go, pkg/util/test/util.go
- The PR contains just the skeleton of the diags controller without much business logic.
- Register the PortworxDiag CRD if not already registered.
- Added a feature flag to enable diags controller. We will set this to true by default when we are ready to release this feature.
Closes # https://portworx.atlassian.net/browse/PWX-29714
=> PWX-29714 Controller to reconcile PortworxDiag objects

drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/px_k3s.yaml
The px-3.0.0/master OCI-Mon are using upgraded client APIs for ContainerD
* the new client APIs require `/var/lib/containerd` mount (already fixed)
* specifically on RKE2 distros, we'll also need to add `/var/lib/rancher/rke2/agent/containerd` mount
Closes # PWX-30729 (part 2)
NOTE, this fix is mirroring our DaemonSet update @ https://github.com/portworx/px-installer/pull/1721
=> PWX-30729_pt2: RKE2 fix

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go
* adding /var/data/cripersistentstorage mount for IKS clusters  (new containerd requirement)
The px-3.0.0 has updated containerd API version, which now requires extra mounts
* we have already addressed this for generic installs, but
* \[**ISSUE**\] for IKS platform specifically, we must add a new `/var/data/cripersistentstorage` mount
Additionally:
* apart from the "usual" way to identify IKS platform via `portworx.io/is-iks: true` annotation...
*  \[**NEW**\] we are also adding an automatic detection via the Kubernetes version extension (i.e. `Server Version: v1.25.8+IKS`)
- that way, the IKS platform will be automatically recognized, even in cases when customer forget to specify `is-iks` annotation …
=> PWX-30623_pt2: IKS + containerd fix

drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/pks.yaml, drivers/storage/portworx/testspec/pks_2.9.1.yaml, drivers/storage/portworx/testspec/px_pks_with_csi.yaml
* the PKS distro uses `/var/vcap/store/containerd` mount instead of `/var/lib/containerd`
This PR corrects the mounts for the PKS distro using `containerd` container runtimes, and px-3.0.0 
Closes # PWX-30857 (part 2)
NOTE: the equivalent WebSVC fix (part 1) is @ https://github.com/portworx/px-installer/pull/1734
=> PWX-30857_pt2: PKS fix

pkg/util/test/util.go
Validate against new StorageCluster Status design for PX Operator 23.5+
NOTE: This is required to run PX Operator 23.5.0+ which has the new Status design
=> PTX-17408 Validate against new StorageCluster Status design for PX Operator 23.5+

drivers/storage/portworx/components_test.go, pkg/cloudprovider/azure.go, pkg/util/util.go, pkg/util/util_test.go
The `AddDefaultRegistryToImage()` is used to parse all image-URL's specified in `px-versions` CM, but it had issues:
* most URLs will be prefixed w/ `docker.io`  (unless form well-known repos) -- so private registry-servers cannot be used
* no support for IPs (IPv4, IPv6)
As a fix, we'll...
* prefix the URL w/ `docker.io` only if URL does not start w/ hostname or IP
* additionally, append `:latest` if no image-tag was provided
Closes # PWX-29131
See JIRA-ticket for PX-specific test info
=> PWX-29131: container image -url parsing fix

pkg/util/test/util.go
Removing check for alertmanager-operated service as it created by cloud providers.
In Anthos cluster, this service is created by-default and when there were no alertmanager enabled in PX.
Closes # PTX-17518
Minor changes.
=> Removing check for alertmanager-operated service

drivers/storage/portworx/component/securitycontextconstraints.go, drivers/storage/portworx/testspec/portworxSCC.yaml, pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/testspec/storkSchedClusterRole.yaml
Updating Openshift securitycontextconstraint on stork-scheduler clusterrole .
Closes #https://portworx.atlassian.net/browse/PWX-30737
* Stork-scheduler pods were not getting scheduled due to error "unable to validate against any security context constraint"
* scc is  already present for many other components we manage. 
* After doing these changes, Stork scheduler pods are getting scheduled.
* oc get scc portworx -oyaml
```allowHostDirVolumePlugin: true
allowHostIPC: true
allowHostNetwork: true
allowHostPID: true
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: true
allowedCapabilities:
- '*'
allowedUnsafeSysctls:
- '*'
apiVersion: …
```
=> PWX-30737: Updating scc to stork-scheduler clusterrole for OCP 4.11

deploy/crds/core_v1_storagecluster_crd.yaml, drivers/storage/portworx/component/alertmanager.go, drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, pkg/apis/core/v1/storagecluster.go, pkg/controller/storagecluster/stork.go, pkg/migration/generate.go
* adding `pause`, `kube-controller-manager-amd64` and `kube-scheduler-amd64` images override via `px-versions` CM
* adding the override for `pause`, `kube-controller-manager-amd64` and `kube-scheduler-amd64` images via `px-versions`  configmap
Closes # PWX-29505  (part 1)
The part 2 will be fixing install.portworx.com/versions REST endpoint.
For PX-specific test, please see [PWX-29505](https://portworx.atlassian.net/browse/PWX-29505) ticket.
This fix is related to the https://github.com/libopenstorage/operator/pull/1030
[PWX-29505]: https://portworx.atlassian.net/browse/PWX-29505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ …
=> PWX-29505_pt1: adding new images in versions-CM

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/util/util.go
This disables adding the `FACD_TOPOLOGY_ENABLED` flag on existing clusters that don't already have it, only allowing new clusters to start with topology.
This is accomplished by, if this is a new install and the variable is present, adding an annotation to demark this on the STC. Then, in future startups, if this annotation is present we don't raise an error.
=> PWX-30512: Blocks enabling FACD topology on existing clusters

drivers/storage/portworx/component/prometheus.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/prometheusInstance.yaml, drivers/storage/portworx/testspec/prometheusInstanceWithAlertManager.yaml, drivers/storage/portworx/testspec/prometheusInstanceWithRemoteWriteEndpoint.yaml
Currently we observed failure of Prometheus deployment on testing cluster with memory limit of 800Mi as defined previously. And hence after some investigation:
1. current testing cluster needs at least 1.5Gi to stabilize
2. a previous test with cluster of 800-nodes used up to 3.7Gi
3. customers are expected to deploy clusters at least with double the size of the testing cluster in 1
We decided to increase this limit to 4Gi so to cover most of the use case so far. More extensive investigation on whether a better (lower) limit could be specified will be carried out for next release. 
More details described in the ticket itself.
Edited Jun 6, 17:57 : ignore the statement in the description as we made decision to go with unbounded …
=> PWX-30943: removed the memory limit for prometheus

drivers/storage/portworx/component/prometheus.go, drivers/storage/portworx/testspec/prometheusInstance.yaml, drivers/storage/portworx/testspec/prometheusInstanceWithAlertManager.yaml, drivers/storage/portworx/testspec/prometheusInstanceWithRemoteWriteEndpoint.yaml
* make prometheus memory limit unbounded
This is a cherry-pick from [approved master merge](https://github.com/libopenstorage/operator/pull/1061)
Closes #
=> PWX-30943: remove prometheus memory limit

deploy/ccm/config_properties_px.yaml, drivers/storage/portworx/testspec/ccmGoRegisterConfigMap.yaml
Starting from ccm-go 1.0.9, it introduced an extra config field "certStoreType" to differentiate different approach for storing appliance certificate when cloud CA returns it to ccm-go. And in order to accommodate their side of change, we also need to introduce this field into ccm-go's configmap to use the latest image with vulnerabilities fixed. 
More context at this commend (https://portworx.atlassian.net/browse/PWX-31585?focusedCommentId=248697)
Closes #
=> PWX-31585: added new certStoreType kv pair to accommodate changes in latest ccm-go

drivers/storage/portworx/component/csi.go, drivers/storage/portworx/testspec/csiDeploymentAlphaDisabledK8s_1_14.yaml, drivers/storage/portworx/testspec/csiDeploymentAlphaDisabledK8s_1_16.yaml, drivers/storage/portworx/testspec/csiDeploymentWithPKS.yaml, drivers/storage/portworx/testspec/csiDeploymentWithResizerAndOldDriver_1.0.yaml, drivers/storage/portworx/testspec/csiDeploymentWithResizer_1.0.yaml, drivers/storage/portworx/testspec/csiDeploymentWithResizer_1_17.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s116.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s120.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s120_with_topology.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s120_without_snapcontroller.yaml, drivers/storage/portworx/testspec/csiDeployment_1.0_k8s123.yaml, drivers/storage/portworx/testspec/csiStatefulSet_0.3.yaml
Switching security to `privileged:true` for all CSI containers
The latest OCP 4.13 has more restrictive SELinux policies, so the Portworx CSI PODs can no longer access the `csi.sock` file.
**ISSUE**: The SELinux block the access to our `csi.sock` file, and the following line pops up in the audit-log:
```
type=AVC msg=audit(1686023559.076:85637): avc:  denied  { connectto } for  pid=224568 comm="csi-snapshotter"
path="/var/lib/kubelet/plugins/pxd.portworx.com/csi.sock"
scontext=system_u:system_r:container_t:s0:c370,c397
tcontext=system_u:system_r:container_runtime_t:s0
tclass=unix_stream_socket permissive=0
``` 
The permissions (and SELinux label) on the `csi.sock` file is consistent with other (non-PX) CSI modules:
``` …
```
=> PWX-31551: CSI privileged fix

pkg/controller/storagecluster/storagecluster.go
Pre-flight passes new parameters to oci-mon & px so we can only execute pre-flight with PX/OCI 3.0 and above.   Skip pre-flight if the version is lower thank 3.0
Closes #
=> PWX-31739: Pre-flight should only run with PX version 3.0 and above.

deploy/olm-catalog/portworx/23.5.0/portworx-certified.clusterserviceversion.yaml
commit to https://github.com/redhat-openshift-ecosystem/certified-operators/pull/2377 has FAILED due to missing `spec.relatedImages`
So, as a fix, we're adding a dummy `relatedImages` entry, pointing back to the same operator image.
Closes # -
=> Adding relatedImages into clusterserviceversion

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
We have encountered a case where `cloudprovider.GetZoneMap()` returned empty zone-map, and this caused golang panic due to "divide by zero"
As a fix, we will return the appropriate error rather than crashing w/ panic.
Closes # PWX-29398 and PWX-30227
=> PWX-29398,PWX-30227: fix panic when GetZoneMap() returns empty zones

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go
Fixes the image override for `portworx-kvdb`
ISSUE:
* when `cm/px-versions` has `pause: ...` image override, we were supposed to set up all `pause`-PODs with the requested image
* however, the `portworx-kvdb` POD ignored this override, and was still using the default `registry.k8s.io/pause:3.1` image-url
FIX:
* as a fix, we are now correctly overriding the `portworx-kvdb` POD image
Closes # PWX-31634
=> PWX-31634: Fix image override for portworx-kvdb

pkg/controller/storagecluster/storagecluster.go
* PWX-31931: Only execute pre-flight on fresh PX install.
* PWX-31931: Ensure Annotation map exists.
* PWX-31931: If skipping pre-flight only set the annotation to false if its not set or empty.
* PWX-31931: Use Piyush review code.
---------
PWX-31931 
Closes #
This is a cherry-pick of PR: https://github.com/libopenstorage/operator/pull/1084 from px-rel-23.5.1
=> Pwx 31931 preflight on fresh install only (#1084)

drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/pks.yaml, drivers/storage/portworx/testspec/pks_2.9.1.yaml, drivers/storage/portworx/testspec/px_pks_with_csi.yaml, pkg/migration/generate.go
* mounting changing OSD-mount to `-v /var/lib/osd:/var/vcap/store/lib/osd:shared`
* removing offending "pxlogs" (/var/vcap/store/lib/osd/log) mount
* changing `PRE-EXEC` to remove the /var/lib/osd/driver directory
* fixing UTs
ISSUE: the `/var/lib/osd` + `/var/lib/osd/log` mounts were causing the "mounts leak" issue on PKS platform
As a fix, we are:
* we are changing the OSD-mount to `/var/vcap/store/lib/osd`
* removing the `/var/lib/osd/log` mount
* we had to use `PRE-EXEC` to remove /var/lib/osd/driver directory, as the `pwx.sock` file inside causes 2-minute delays for every `pxctl` command
Closes # PWX-31842
=> PWX-31842: PKS mounts-leak fix

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/util/util.go, pkg/controller/storagecluster/storagecluster.go, pkg/preflight/preflight.go, pkg/preflight/utils.go
Using VSPHERE_VCENTER env variable as an indication to say
that it's vsphere provider
Closes #
Manual test:
```Jun 24 06:29:12 ip-10-13-195-103.pwx.purestorage.com portworx[6882]: time="2023-06-24T06:29:12Z" level=info msg="PX-RunC arguments: -b -c px-cluster-49b447d6-dbba-4b89-a35c-0341644148c6 -dedicated_cache -fastpath_enable -fastpath_protocol local -j auto -max_storage_nodes_per_zone 5 -metadata size=64 -s size=50 -s size=50 -s size=100 -secret_type k8s -x kubernetes"```
Unit test:
```
=== RUN   TestPodSpecForVsphere
time="2023-06-24T08:15:20-07:00" level=info msg="telemetry registration endpoint register.cloud-support.purestorage.com is accessible on cluster …
```
=> PWX-31672: Recognize vSphere provider

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
What this PR does / why we need it:
Previously the check would initially pass but the annotation wouldn't be added, resulting in failures down the line. This small restructure fixes it all up and adds the annotation before the pre-flight check, which is also more consistent with the entire code flow. Many thanks to @piyush-nimbalkar  !
Which issue(s) this PR fixes (optional)
PWX-32048
=> PWX-32048: Fixes annotation not being properly added for FACD topology installs

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
Previously the check would initially pass but the annotation wouldn't be added, resulting in failures down the line. This small restructure fixes it all up and adds the annotation before the pre-flight check, which is also more consistent with the entire code flow. Many thanks to @piyush-nimbalkar !
PWX-32048
=> [23.5.1] PWX-32048: Fixes annotation not being properly added for FACD topology installs

pkg/util/test/util.go
Temporary remove validation of cloudStorage spec, doing DeepEquals() is not a good method to do this since operator changes cloudStorage spec due to various events and environments. Will find a better way in PTX-18637
=> PTX-18636 Temporary remove validation of cloudStorage spec

pkg/preflight/utils.go
DMThin default only on EKS.  Add the check so pre-flight only runs on EKS.
Closes #
PWX-32096
=> PWX-32096: Only execute pre-flight if running on EKS.

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/px_telemetry-with-location.yaml, drivers/storage/portworx/testspec/px_telemetry.yaml, drivers/storage/portworx/testspec/px_telemetry_with_proxy.yaml
Need to determine loguploader port using the ccm configmap.   Export the ccm properties config to oci-mon and have it copy the cm to /etc/pwx for use by pxctl.
Closes #
PWX-32051
=> PWX-32051: move default ccm port 9029 and create ccm cm before PX start

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/testspec/px_telemetry-with-location.yaml, drivers/storage/portworx/testspec/px_telemetry.yaml, drivers/storage/portworx/testspec/px_telemetry_with_proxy.yaml
Currently change to introduce telemetry phonehome volume should only be applied to cluster greater than or equal to 3.0, otherwise we'll have regression failure for cluster running with Java CCM when px-telemetry-phonehome configmap is not part of the cluster
Closes #
=> PWX-32127: Only add telemetry phonehome volume if px is at least 3.0

drivers/storage/portworx/util/util.go, pkg/controller/storagenode/storagenode.go, pkg/controller/storagenode/storagenode_test.go
* will remove the terminated kvdb-api pods
We got reports of 2 instances, where Kubernetes stopped recycling a dummy `kvdb-api` POD
* the `kvdb-api` POD is not really running KVDB, it's running a `pause` instead
- we just use it to report the readyness-status of the `kvdb` service running inside Portworx
* this POD uses `restartPolicy: Always` and `terminationGracePeriodSeconds: 30` -- so it normally never terminates, nor will it reach the `Completed` or `Failed` state
- instead, within 30 seconds it is normally garbage-collected and restarted by Kubernetes
ISSUE:
We got two reports from different environments, where `kvdb-api` POD has terminated, and was not restarted by Kubernetes -- it would just terminate, and transition into `Completed` state
* …
=> PWX-31915: kvdb-api pod cleanup

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/preflight.go, drivers/storage/portworx/testspec/px_telemetry-with-location.yaml, drivers/storage/portworx/testspec/px_telemetry.yaml, drivers/storage/portworx/testspec/px_telemetry_with_proxy.yaml, pkg/controller/storagecluster/storagecluster.go, pkg/preflight/utils.go
Missing commits from px-rel-23.5.1
PWX-32096: Only execute pre-flight if running on EKS. (#1107)
Only add telemetry phonehome volume if px is at least 3.0 (#1113)
PWX-32131: Remove ccm-phonehome-config mount.  This is a mount which … (#1112)
Closes #
=> Missing commits 23.7.0

deploy/olm-catalog/portworx/23.5.1/portworx-certified.clusterserviceversion.yaml
=> Update  "replaces" version to 23.5.0 for 23.5.1 release

drivers/storage/portworx/testspec/csiDeployment_1.0_k8s123.yaml, drivers/storage/portworx/util/csi_generator.go
Cherry-pick https://github.com/libopenstorage/operator/pull/1096 to 23.7.0
https://portworx.atlassian.net/browse/PWX-31944
In an airgapped environment, we were including the csi-health-monitor-controller.
We should never start this container by default.
Disabling the csi-health-monitor-controller until further notice.
=> Operator default images should not include csi-health-monitor-controller

drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/preflight.go
* PWX-31971: Make sure pre-flight results are the product of a valid pre-flight run.  Add operator version to env.
* PWX-31971: Revert change made for testing
* PWX-31971: Remove code which adds operator version env variable. Add more pre-flight check results unit tests
* PWX-31971: gofmt fix.
* PWX-31672: Recognize vSphere provider (#1088)
* PWX-31969: Use lowercase chars in -T param. (#1097)
* PWX-32048: Fixes annotation not being properly added for FACD topology installs (#1101)
* PWX-32073: Update csi-provisioner operation timeout from 10s to 5m (#1099)
* PTX-18636 Temporary remove validation of cloudStorage spec (#1108)
* PWX-32051: move default ccm port 9029 and create ccm cm before PX start (#1105)
* PWX-32051: If PX version is 3.0 or greater use 9029 for CCM uploader port.
* …
=> PWX-31971 verify pre-flight results (#1089)

deploy/ccm/envoy-config-collector-custom-proxy.yaml, deploy/ccm/envoy-config-register-custom-proxy.yaml, deploy/ccm/envoy-config-rest-custom-proxy.yaml, drivers/storage/portworx/testspec/ccmGoCollectorProxyConfigMap_proxy.yaml, drivers/storage/portworx/testspec/ccmGoPhonehomeProxyConfigMap_proxy.yaml, drivers/storage/portworx/testspec/ccmGoRegisterProxyConfigMap_proxy.yaml
cherry-picked from approved master [PR](https://github.com/libopenstorage/operator/pull/1118)
Those missing sections have been put in the config for envoy running without proxy but overlooked for the proxied environment. So adding them as fix for current issue
Closes #
=> PWX-32197: added missing http filters config for envoy running with proxy

pkg/controller/portworxdiag/pod.go
Originally I just copied all the same mounts from the Portworx pod. Most of them aren't necessary: we only need `/proc` (to `nsenter` into the host) and `/var/cores` (to clean up old diag files).
Tested by comparing diags before and after and they were a nearly identical size, all files were present, etc.
=> PWX-32179: Reduces volume mounts for PX diag collector pod

pkg/controller/portworxdiag/controller_test.go, pkg/controller/portworxdiag/portworxdiag.go
* Adds support for `Spec.Portworx.NodeSelector.IDs` and `Spec.Portworx.NodeSelector.Labels` in the operator
* Reorganizes a couple methods to make them cleaner
* Adds unit tests for all the substantial methods in the diag controller (I don't unit test front-to-back yet but it gets the critical functionality)
PWX-29716 (node selector)
PWX-32103 (unit tests)
=> PWX-29716, PWX-32103: Implements PortworxDiag NodeSelector, adds unit tests

pkg/controller/portworxdiag/pod.go
Like the last PR, the pod spec was mostly copied from the standard portworx pod spec. This left some extra things like HostNetwork, DNSPolicy, and EnableServiceLinks that we don't need.
I again confirmed it worked by checking the size of a diag before and after the change and they were nearly identical, confirming all the same data is still there.
PWX-32177
=> PWX-32177: Removes unnecessary permissions from diag collector pods

drivers/storage/portworx/component/securitycontextconstraints.go, drivers/storage/portworx/testspec/portworxSCC.yaml
OpenShift does not tolerate both `allowPrivilegedContainer: true` and `allowPrivilegeEscalation: false` SCC setting
* if attempted, the POD startup will be blocked with the following warning:
```
...
Events:
Type     Reason        Age                      From                       Message
----     ------        ----                     ----                       -------
Warning  FailedCreate  5m29s (x746 over 3h29m)  storagecluster-controller  (combined from similar events): \
Error creating: Pod "test-stc-xrfkb" is invalid: spec.containers[0].securityContext: Invalid value: ...: \
cannot set `allowPrivilegeEscalation` to false and `privileged` to true
```
FIX:
* since we need these containers to run as `privileged`, we will also need to enable …
=> PWX-32399: fix PX privileged SCC

deploy/crds/core_v1_storagecluster_crd.yaml, deploy/plugin/nginx-deployment.yaml, deploy/plugin/plugin-deployment.yaml, drivers/storage/portworx/component/plugin.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/nginx-deployment.yaml, drivers/storage/portworx/testspec/plugin-deployment.yaml, pkg/apis/core/v1/storagecluster.go, pkg/migration/generate.go
Added custom Image Registery for px-plugin and px-plugin-proxy pod : 
1. Added DynamicPlugin and Nginxc image in manifest and Desired images
2. Changed deployment creation to use desired image at time of creation
Tests done : 
Tested on air-gapped cluster with CIR "docker.pwx.dev.purestorage.com" , both px-plugin and px-plugin-proxy pods were up and running fine
Events:
Type     Reason          Age    From               Message
----     ------          ----   ----               -------
Normal   Scheduled       7m21s  default-scheduler  Successfully assigned kube-system/px-plugin-proxy-d5c6f65d7-vkfqr to airgap-ocp-w8pqc-worker-2bl5l by airgap-ocp-w8pqc-master-0
Warning  FailedMount     7m21s  kubelet            MountVolume.SetUp failed for volume "nginx-certs" : secret "px-plugin-proxy" …
=> PWX-32147 : add custom image registry support for plugin pod

drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/plugin-deployment.yaml
Updating dynamic plugin pod image for 23.7.0 from portworx/portworx-dynamic-plugin:1.0.0 to portworx/portworx-dynamic-plugin:1.1.0
px-installer changes : https://github.com/portworx/px-installer/pull/1825
=> update dynamic plugin image for 23.7.0 

pkg/controller/storagecluster/storagecluster.go
When upgrading PX to 3.0 with op 23.5.0, storage spec was updated with -T dmthin.   This was bug and was corrected with other fixes however the spec still contained the -T dmthin.   Even though its ignored we should remove it to avoid confusion.
Closes #
PWX-31981
=> PWX-31981: Remove depricated '-T dmthin' misc argument

pkg/controller/storagecluster/storagecluster.go
* PWX-31981: Remove '-T dmthin' from annotation portworx.io/misc-args if it exists.
* PWX-31981: Make sure to update the spec after cleanup.
* PWX-31981: Review suggestions, move regx to global and FindStringSubmatch.
---------
Remove depricated '-T dmthin' misc argument
Closes #
PWX-31981
Cherry-pick from master...
=> PWX-31981: Remove depricated '-T dmthin' misc argument (#1155)

test/integration_test/basic_dmthin_test.go, test/integration_test/cloud_provider/cloud_drive.go
TestStorageClusterBasicDMthin has the same prefix with another test
TestStorageClusterBasic. This is causing the dmthin test to run in
unintended jenkins jobs.
There is an additional way of knowing the provider which is to use
the value from --cloud-provider
Closes #
=> PWX-31962: Fixing up test name and provider logic

drivers/storage/portworx/component/securitycontextconstraints.go, drivers/storage/portworx/testspec/portworxSCC.yaml
* re-enabling the AllowHostPorts, since telemetry uses it
The telemetry DaemonSet uses HostPorts, and the portworx (privileged) SCC was disabling it.
As a consequence the px-telemetry DaemonSet was not getting associated with any SCC:
```
RESOURCE   SERVICE ACCOUNT   ALLOWED BY
```
.. so Kubernetes tried to match it with any/all public SCC's -- and made a huge mess, and a very confusing error (complains about everything...):
```
Warning  FailedCreate  119s (x55 over 3h57m)  daemonset-controller  Error creating: pods "px-telemetry-phonehome-" is forbidden: unable to validate against any security context constraint: [
provider "anyuid": Forbidden: not usable by user or serviceaccount
spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not …
```
=> PWX-32497: fix portworx (privileged) SCC

deploy/ccm/envoy-config-collector-custom-http-proxy.yaml, deploy/ccm/envoy-config-collector-custom-https-proxy.yaml, deploy/ccm/envoy-config-register-custom-http-proxy.yaml, deploy/ccm/envoy-config-register-custom-https-proxy.yaml, deploy/ccm/envoy-config-rest-custom-http-proxy.yaml, deploy/ccm/envoy-config-rest-custom-https-proxy.yaml, drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/testspec/ccmGoCollectorProxyConfigMap_httpproxy.yaml, drivers/storage/portworx/testspec/ccmGoCollectorProxyConfigMap_httpsproxy.yaml, drivers/storage/portworx/testspec/ccmGoPhonehomeProxyConfigMap_httpproxy.yaml, drivers/storage/portworx/testspec/ccmGoPhonehomeProxyConfigMap_httpsproxy.yaml, drivers/storage/portworx/testspec/ccmGoRegisterProxyConfigMap_httpproxy.yaml, drivers/storage/portworx/testspec/ccmGoRegisterProxyConfigMap_httpsproxy.yaml, drivers/storage/portworx/util/util.go, drivers/storage/portworx/util/util_test.go
* added https proxy support
cherry-picked from approved master [PR](https://github.com/libopenstorage/operator/pull/1120)
Closes #
=> PWX-32011: added https proxy support (#1120)

pkg/util/test/util.go
Improving logic for when Telemetry should be enabled/disabled
=> PTX-18831 Improving logic for when Telemetry should be enabled/disabled

pkg/controller/portworxdiag/controller_test.go, pkg/controller/portworxdiag/portworxdiag.go
Implements the ability to select which nodes to collect diags on by providing volume IDs or volume label selectors.
As this is a somewhat intensive operation, I also reorganized things slightly so that we will only run the calculation of which nodes to run on once: after that has been calculated, we just use the list of nodes in the diag object status.
PWX-29715
=> PWX-29715: Implemented volume selector for PortworxDiags

pkg/controller/portworxdiag/portworxdiag.go
- The diag pods are created with controller reference to the corresponding PortworxDiag object.
- The added controller watch will ensure that if there is a change in the diag pods, the diag reconciler is called with the parent PortworxDiag object.
Closes # https://portworx.atlassian.net/browse/PWX-32193
=> PWX-32193 Watch for diag pod changes and reconcile PortworxDiag obj

pkg/controller/storagecluster/storagecluster.go
PWX-32567: pre-flight pods do not run on master so don't create pre-flight storage node entry for master.
Closes #
PWX-32567
=> PWX-32567: merge into 23.7.0

pkg/util/test/util.go, test/integration_test/basic_test.go, test/integration_test/marketplace_test.go, test/integration_test/utils/px_operator.go
Adding workaround for the known Telemetry port issue for specific Operator upgrades
=> PTX-19346 Adding workaround for the known Telemetry port issue for specific Operator upgrades

drivers/storage/portworx/component/plugin.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/testspec/pks.yaml, drivers/storage/portworx/testspec/pks_2.9.1.yaml, drivers/storage/portworx/testspec/px_pks_with_csi.yaml, drivers/storage/portworx/util/util.go, drivers/storage/portworx/util/util_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/migration/generate.go
Merging fixes PWX-32428,PWX-27672 from `master`-branch :
* https://github.com/libopenstorage/operator/pull/1141
* https://github.com/libopenstorage/operator/pull/1181
Closes # PWX-32428, PWX-27672
=> Merge PWX-32428,PWX-27672 fixes into 23.7.0 (#1141) (#1181)

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go
Adding SYS_CHROOT capability into non-privileged deployment
PX deployment with `privileged:false` annotation was failing on the OCP-4.13.
FIX:
* we're adding `SYS_CHROOT` capability into the requested capabilities -- this enables deployment on OCP-4.13
Closes # PWX-32773
=> PWX-32773: OCP-4.13 non-privileged deployment fix

deploy/ccm/envoy-config-collector-custom-https-proxy.yaml, deploy/ccm/envoy-config-register-custom-https-proxy.yaml, deploy/ccm/envoy-config-rest-custom-https-proxy.yaml, drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/testspec/ccmGoCollectorProxyConfigMap_httpsproxy.yaml, drivers/storage/portworx/testspec/ccmGoPhonehomeProxyConfigMap_httpsproxy.yaml, drivers/storage/portworx/testspec/ccmGoRegisterProxyConfigMap_httpsproxy.yaml, drivers/storage/portworx/util/util.go, pkg/util/test/util.go
The previous implementation of using basic auth for https proxy was based on a wrong assumption that this https proxy also needs to be SSL-enabled (with https:// prefix/protocol). 
Removing them because https proxy can also be non-SSL enabled (http://) and also no TLS context is required in envoy config for this case.
Closes #
=> fixup for https proxy with basic authn

drivers/storage/portworx/component/telemetry.go
In order for the telemetry port change to work on 2.13.8, we need to update the version check as in this PR and cherry-pick the change to newer op release branches (23.5.2 and 23.7.0)
Closes #
=> PWX-32976: Backport for 2.13.8

.travis.yml, Makefile, deploy/olm-catalog/portworx/23.7.1/core_v1_storagecluster_crd.yaml, deploy/olm-catalog/portworx/23.7.1/core_v1_storagenode_crd.yaml, deploy/olm-catalog/portworx/23.7.1/portworx-certified.clusterserviceversion.yaml, deploy/olm-catalog/portworx/portworx.package.yaml, deploy/operator.yaml
Closes # https://portworx.atlassian.net/browse/PTX-19443
=> Setting up 23.7.1 branch

test/integration_test/basic_dmthin_test.go, test/integration_test/cloud_provider/cloud_drive.go, test/integration_test/cloud_provider/vsphere.go, test/integration_test/utils/utils.go
Install/Uninstall tests for PX-StoreV2
https://portworx.testrail.net/index.php?/runs/view/6624&group_by=cases:custom_automated&group_order=asc
The above link has a bunch of tests where we try different
combinations of the below to make sure dmthin is installed.
- Journal device
- KVDB device
- Auto Journal
- Metadata Device
- -T px-storev2 option
Two operator integration tests are added to enforce the above
combinations and have 32 tests
Closes #
Testing notes:
Two jenkins jobs were created to run the two tests added
https://jenkins.pwx.dev.purestorage.com/job/3.1.0-dev-jobs/job/vSphere-withDmthinOption-opint/
https://jenkins.pwx.dev.purestorage.com/job/3.1.0-dev-jobs/jo …
=> PWX-32648: Adding Install/Uninstall test cases

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/component/telemetry_test.go
* modified px version check
We're backporting a change to 2.13.8 so that the default telemetry port changes to 9029 and porx can dynamically load and find the port value specified by operator from mounted ccm.properties file
Closes #
=> PWX-32976: need to set telemetry port to 9029 if px >= 2.13.8

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go
previous [PR](https://github.com/libopenstorage/operator/pull/1204) only updated the version check for shifting the port to 9029 when px is 2.13.8, but operator also needs to allow volume mount of ccm.properties file to porx container otherwise oci-mon won't be able to find it and copy to /etc/pwx for porx' diag calls
Closes #
=> PWX-32976: need to mount ccm config for 2.13.8 as well

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go
cherry-picked from master for starting to mount ccm config from px-2.13.8
Closes #
=> PWX-32976: cherry-pick ccm config mount change for 2.13.8

test/integration_test/basic_dmthin_test.go, test/integration_test/utils/utils.go
Building this test over the functions added in PWX-32648, hence basing it on that branch.
This test case verifies that btrfs  datastores stays on upgrade on a
testbed that qualifies for dmthin.
TestStorageClusterDMthinUpgrade upgrades PX to 3.1 from 3.0 and 2.13
over two iterations. It'll also verify that btrfs was installed.
Closes #
https://jenkins.pwx.dev.purestorage.com/job/3.1.0-dev-jobs/job/vSphere-upgrade-dmthin-opint/
```
01:15:48.626 --- PASS: TestStorageClusterDMthinUpgrade (2907.73s)
01:15:48.626     --- PASS: TestStorageClusterDMthinUpgrade/BasicUpgradeStorageClusterDmthinWithAllComponents (2907.73s)
01:15:48.629 PASS
01:15:48.629 …
```
=> Adding Upgrade test

drivers/storage/portworx/testspec/prometheusRule.yaml
Rules have changed in the portworx docs repo. Copied over the new version of the file.
Closes #
=> cherry-pick: Update the prometheus rules used by the test

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go
ISSUE:
* our QA used image-override `3.0.1-ubuntu1604` -- and this BROKE the version-checks
```go
NewVersion("3.0.1-ubuntu1604").GreaterThanOrEqual("3.0.1")  // this evaluates as FALSE!!
```
* note, the "version with extension" (such as `3.0.1-ubuntu1604`), will evaluate similar like `3.0.1.1` (a version _higher_ than `3.0.1`)
FIX:
* as a fix, we're changing the `version.GreaterThanOrEqual("3.0.1")` into `version.GreaterThan("3.0")`
Closes # PWX-32825
=> PWX-32825: Adjusting version triggers for px-3.0.1

deploy/olm-catalog/portworx/23.7.1/portworx-certified.clusterserviceversion.yaml, drivers/storage/portworx/component/windows.go, drivers/storage/portworx/components_test.go
This PR fixes : 
1. https://portworx.atlassian.net/browse/PWX-33085
Operator pod is being scheduled randomly on linux or windows node. The pod should always be scheduled on linux node.
3. https://portworx.atlassian.net/browse/PWX-33086
Windows daemonset should be created for minimum k8s version 1.25 and RH 4.12
Tests done : 
1. Tested on cluster with 2 windows node
2. Tested on cluster with k8s version 1.24 and 1.25
=> PWX-33085, PWX-33086 : Add linux nodeaffinity for operator 

test/integration_test/utils/storagecluster.go, test/integration_test/utils/utils.go
Issue: Upgrade from edge to none edge PX endpoint fails due to PX_RELEASE_MANIFEST_URL is not removed from Env vars
Fix: Remove PX_RELEASE_MANIFEST_URL for PX upgrades from none edge endpoints
Improvement: Remove duplicate env vars during upgrade hops
=> PTX-19673 Remove PX_RELEASE_MANIFEST_URL for PX upgrades from none edge endpoints

deploy/crds/core_v1_storagecluster_crd.yaml, deploy/olm-catalog/portworx/23.7.1/portworx-certified.clusterserviceversion.yaml, deploy/windows/px-csi-node-win.yaml, drivers/storage/portworx/component/windows.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/px-csi-node-win.yaml, drivers/storage/portworx/testspec/px-csi-win-driver.yaml, drivers/storage/portworx/util/csi_generator.go, drivers/storage/portworx/util/util.go, pkg/apis/core/v1/storagecluster.go, pkg/migration/generate.go
This PR fixes : https://portworx.atlassian.net/browse/PWX-33087
1. Changed manifest WindowsCsiDriver tag to match with px-installer tag here : https://github.com/portworx/px-installer/pull/1848
2. Changed storagecluster CRD tag to keep it consistent
Bug fix :
1. Corrected format of nodeaffinity on CSV
2. Corrected toleration on windows pods from 'windows' to 'Windows'
Test : 
Verified on k8s 1.25.8 cluster
**Following is the status of STC :** 
status:
clusterName: px-clusters
desiredImages:
autopilot: portworx/autopilot:1.3.8
csiAttacher: docker.io/openstorage/csi-attacher:v1.2.1-1
csiLivenessProbe: registry.k8s.io/sig-storage/livenessprobe:v2.10.0
csiNodeDriverRegistrar: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.8.0
csiProvisioner: …
=> PWX-33087 : CsiWindowsDriver image is not populating is storagecluster desired images

deploy/crds/core_v1_storagecluster_crd.yaml, drivers/storage/portworx/component/windows.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/px-csi-node-win.yaml, drivers/storage/portworx/util/csi_generator.go, pkg/apis/core/v1/storagecluster.go, pkg/migration/generate.go
Cherrypick https://github.com/libopenstorage/operator/pull/1224 to 23.7.0
Fixes : https://portworx.atlassian.net/browse/PWX-33279
=> cherrypick PWX-33279 : Update windows image's tags

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, pkg/migration/generate.go
* custom mounts can now override the embedded (default) mounts
The mount-overrides were previously just "dropped" with a warning.
* see https://github.com/libopenstorage/operator/pull/585 and https://github.com/libopenstorage/operator/commit/6c8adbad924ca6d7109b42848af22c75466fdbec
As a fix, the user-mounts (custom mounts) can _override_ the original mounts internal to operator.
Closes # PWX-30455
This PR also replaces https://github.com/libopenstorage/operator/pull/1168
Testing notes:
**TEST**: StorageCluster modification using 2 custom-mounts with the same destination (`/var/cores`)
```yaml
apiVersion: core.libopenstorage.org/v1
kind: StorageCluster
spec:
volumes:
- …
```
=> PWX-30455: mounts override fix

deploy/olm-catalog/portworx/portworx.package.yaml
* upgrading to the "latest published" currentCSV: portworx-operator.v23.5.1
Trying to work around the publication failure
* looks like RHEL is reporting that we're trying to "downgrade" their catalogs
> opm registry add...
> [generate-index : generate] Error: [add prunes bundle portworx-operator.v23.4.1 (image-registry.openshift-image-registry.svc:5000/operator-release/portworx-certified-bundle:23.4.1) from package portworx-certified, channel alpha: this may be due to incorrect channel head (portworx-operator.v23.5.1, skips/replaces [portworx-operator.v23.5.0]). Be aware that the head of the channel alpha where you are trying to add the portworx-operator.v23.4.1 is portworx-operator.v23.5.1. Upgrade graphs follows the Semantic Versioning 2.0.0 …
=> Downgrade package CSV

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go
A bunch of dev-branches got renamed on the `porx` project -- so we have to compensate the versions changes in operator code.
Closes # PWX-33418
=> PWX-33418: Compensate for porx-branch renaming

test/integration_test/basic_dmthin_test.go
TestStorageClusterDmthinWithoutPxStoreV2OptionInstallFailed name
conflicts with TestStorageClusterDmthinWithoutPxStoreV2Option and
fails the job. Changing the name to TestStorageClusterIncompatibleNodeDmthin
Closes #
=> PWX-33550: Op-int test name change

drivers/storage/portworx/deployment.go, drivers/storage/portworx/util/util.go
The `rt_opts` (runtime options) were first stashed into a HashMap, then collected into an array before passing them on as the options to the OCI-Monitor
ISSUE:
* since we used the HashMap -> array, the entries in the array will be UNSORTED (sorted randomly)
* this is an issue, since changing the order of parameters passed to the OCI-Monitor can cause `portworx.service` restarts
FIX:
* as a fix, we are _sorting_ the runtime-options array, before adding them into the OCI-Monitor's arguments
Closes # (no ticket)
=> The `-rt_opts` handling cleanup

drivers/storage/portworx/component/windows.go, drivers/storage/portworx/components_test.go
**Issue :** https://portworx.atlassian.net/browse/PWX-33602
When CSI is disabled, operator tries to create px-csi-node-win, px-csi-win-driver pods and px-csi-win-shared StorageClass, None of them should be created when CSI is disabled.
**Resolution:**
If CSI is disabled, windows component should be disabled.
**Tests done :** 
Installation with CSI enabled : px-csi-node-win, px-csi-win-driver pods were scheduled and in Running state, px-csi-win-shared StorageClass was created.
Installation with CSI disabled : px-csi-node-win, px-csi-win-driver pods daemonset were not created, px-csi-win-shared StorageClass was not created.
=> PWX-33602 : Do not enable windows component if CSI is disabled

drivers/storage/portworx/component/windows.go, drivers/storage/portworx/components_test.go
Cherrypick PR for https://github.com/libopenstorage/operator/pull/1257
=> Cherrypick PWX-33602 : Do not enable windows component if CSI is disabled 

drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/testspec/nginx-deployment.yaml
Fixes https://portworx.atlassian.net/browse/PWX-32952
Tested dynamic plugin feature with image nginx-unprivileged:1.23 on OCP cluster
=> PWX-32952 : Update nginx image to nginx-unprivileged:1.25

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
Preflight running in a custom namespace (portworx) failed to start in OCP on a fresh cluster due to OCP security setting missing for the custom namespace.   The setting where missing because they where not being applied until the pre-install of the storage cluster which was done after pre-flight was run.   So now we are installing the security setting during pre-flight also to make sure they exist.
Closes #
PWX-33374
=> PWX-33374:Set Security context for OCP before pre-flight is launched.

drivers/storage/portworx/deployment.go, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/util/util.go, pkg/migration/generate.go
* custom mounts can now override the embedded (default) mounts
drivers/storage/portworx/deployment_test.go
this is a cherry-pick of https://github.com/libopenstorage/operator/pull/1226 into `px-rel-23.10.0` branch
Closes #  PWX-30455 (op-23.10.0)
=> PWX-30455 (op-23.10.0): mounts override fix (#1226)

pkg/util/test/util.go
Test was expecting the deployment labels to match the topology constraints, but this is not always correct.
PWX-33990
Test failure - 
Expected:
expected constraints: [{MaxSkew:1 TopologyKey:topology.kubernetes.io/region WhenUnsatisfiable:ScheduleAnyway LabelSelector:&LabelSelector{MatchLabels:map[string]string{name: portworx-pvc-controller,operator.libopenstorage.org/managed-by: portworx,tier: control-plane,},MatchExpressions:[]LabelSelectorRequirement{},} MinDomains:<nil> NodeAffinityPolicy:<nil> NodeTaintsPolicy:<nil> MatchLabelKeys:[]}]
Actual:
actual constraints:   [{MaxSkew:1 TopologyKey:topology.kubernetes.io/region WhenUnsatisfiable:ScheduleAnyway …
=> PWX-33990: Test for deployment selector labels instead of template

pkg/controller/storagenode/storagenode.go, pkg/controller/storagenode/storagenode_test.go
* will explicitly remove also the failed-due-node-shutdown PODs
This is the extension of https://github.com/libopenstorage/operator/pull/1106 fix
ISSUE:
* turns out we can encounter other PODs stuck in "weird states" -- that will require explicit cleanup
* if such PODs are left in the system, they can interfere with the OCP upgrades
POD-status details:
```
Status:           Failed
Reason:           NodeShutdown
Message:          Pod Pod was rejected as the node is shutting down.
```
Closes # PWX-31915
Note that we still haven't reproduced the original issue --
* we know that it is linked to the OCP upgrade, where OCP will  cordon and restart a K8s-node (also replace K8s …
=> PWX-31915: kvdb-api pod extended cleanup

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/preflight/pks.go, pkg/preflight/preflight.go, pkg/preflight/preflight_test.go, pkg/preflight/utils.go
Prevent preflight from running when using Vsphere and PKS.   Also preflight should only run on Vsphere, Pure, Azure if PX image is >=3.1.0  
Closes #
PWX-32670
Added UTs however and validated this manually verified that with this change pre-flight does not run when using PKS on Vsphere.
=> PWX-32670: Vsphere preflight should not run on PKS

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/preflight/pks.go, pkg/preflight/preflight.go, pkg/preflight/preflight_test.go, pkg/preflight/utils.go
* PWX-34238: Vsphere Preflight should only run on PX image 3.1.0 and above.
* PWX-32670: Detect PKS env using namespace, don't run Vsphere preflight if PKS.  Also don't run pre-flight on Vsphere, pure & Azure unless PX ver >= 3.1.0
---------
Prevent preflight from running when using Vsphere and PKS.  Also Vsphere preflight will only run if PX image is >=3.1.0.  Did not pull in the Pure or Azure checks... they were removed.
Special notes for your reviewer:
Ran UTs for tests
Closes #. PWX-32670
=> PWX-32670: Vsphere preflight should not run on PKS (#1284)

Makefile, build/Dockerfile
Squashed commit of the following:
commit 0662fb8b63686f3285066bb36ff3bb57c2623ff5
Author: Zoran Rajic <zox@portworx.com>
Date:   Tue Oct 17 14:22:27 2023 -0700
Dockerfile `RUN` fixup
commit d28642c8f231c2694e4517c438aedf8995b115de
Author: Zoran Rajic <zox@portworx.com>
Date:   Tue Oct 17 13:30:38 2023 -0700
PWX-34393: JUpdating baseline image
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1299 into `px-rel-23.10.0` image
Closes #  PWX-34393 (23.10.0)
=> PWX-34393 (23.10.0): Updating baseline image  (#1299)

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/stork_test.go, pkg/controller/storagenode/storagenode.go, pkg/controller/storagenode/storagenode_test.go, pkg/util/k8s/node.go, pkg/util/k8s/node_test.go, pkg/util/maps/syncmap.go, pkg/util/maps/syncmap_test.go
* add simple SyncMap implementation
* fixed UTs
We have hit `fatal error: concurrent map read and map write` issue on `Controller.nodeInfoMap`  (see [PWX-34391](https://portworx.atlassian.net/browse/PWX-34391))
As a fix, adding a simplified implementation of `RWMutex`-protected map w/ golang-generics
* note, this map is used sporadically in the production code -- but quite extensively across the unit-tests  (so, lot more changes in the UT-code)
* also, on a small concurrency (i.e. less than 4 parallel goroutines), this locked-map should be faster compared to golang's [sync.Map](https://pkg.go.dev/sync#Map)
Closes # PWX-34391
[PWX-34391]: …
=> PWX-34391: fix concurrent map panic

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/stork_test.go, pkg/controller/storagenode/storagenode.go, pkg/controller/storagenode/storagenode_test.go, pkg/util/k8s/node.go, pkg/util/k8s/node_test.go, pkg/util/maps/syncmap.go, pkg/util/maps/syncmap_test.go
* add simple SyncMap implementation
* fixed UTs
pkg/controller/storagecluster/controller_test.go
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1303 into the `master`-branch
Closes #  PWX-34391 (master)
see https://github.com/libopenstorage/operator/pull/1303
=> PWX-34391 (master): fix concurrent map panic (#1303)

test/integration_test/utils/storagecluster.go
Add retry when updating StorageCluster to avoid `Operation cannot be fulfilled on storageclusters.core.libopenstorage.org "test-stc": the object has been modified; please apply your changes to the latest version and try again`
=> PTX-20173 Add retry when updating StorageCluster

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/testspec/autopilotClusterRole.yaml, drivers/storage/portworx/testspec/autopilotClusterRole_k8s_1.24.yaml
currently autopilot complains about "Failed to watch *v1.PersistentVolumeClaim: unknown (get persistentvolumeclaims)" due to missing of watch permission on pvc and this error is gone on the testing cluster once watch is allowed for autopilot's clusterrole on pvc/pv 
Closes #
=> PWX-34650: allow autopilot to watch pvc

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/testspec/autopilotClusterRole.yaml, drivers/storage/portworx/testspec/autopilotClusterRole_k8s_1.24.yaml
We also need to allow autopilot to watch on configmaps otherwise error logs like 
`level=error msg="Failed to watch on config map: autopilot-config due to: unknown (get configmaps)" file="main.go:439"`
will show up, although it doesn't affect functionality of reloading autopilot when config changes
Closes #
=> PWX-34798: allow autopilot to watch configmap

drivers/storage/portworx/manifest/manifest.go
Updating default (hard-coded) images used by the operator when `install.portworx.com/XX/version` is not reachable, and no `px-versions` configMap present
* also changed the sorting-order of the variables, to match the REST sequence of images
Specifically -- updated to following images @ https://install.portworx.com/version
```
version: 2.13.8
components:
stork: openstorage/stork:23.8.0
autopilot: portworx/autopilot:1.3.11
nodeWiper: portworx/px-node-wiper:2.13.2
csiNodeDriverRegistrar: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.6.2
csiProvisioner: registry.k8s.io/sig-storage/csi-provisioner:v3.3.0
csiAttacher: docker.io/openstorage/csi-attacher:v1.2.1-1
csiResizer: registry.k8s.io/sig-storage/csi-resizer:v1.6.0
csiSnapshotter: …
```
=> PWX-34824: updating default images

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/autopilotClusterRole.yaml, drivers/storage/portworx/testspec/autopilotClusterRole_k8s_1.24.yaml, drivers/storage/portworx/testspec/autopilotDeployment.yaml
In op-23.5.0, usage of podsecuritypolicy for autopilot was removed if deployed on k8s 1.25 beyond, but in OCP in order for autopilot to access directories like /var/cores, we also need to allow its clusterrole to use portworx-restricted scc and also mount this folder from host.
Closes # PWX-34796
Error messages like 
`time="30-10-2023 17:15:34" level=error msg="failed to create debug logs: mkdir /var/cores: permission denied" file="main.go:315"
time="30-10-2023 17:15:34" level=error msg="failed to start custom signal handlers: mkdir /var/cores: permission denied" file="main.go:277"`
are gone from autopilot log on OCP with this change
=> PWX-34796: added scc and vol mnt

pkg/util/test/util.go
Change min operator version for dynamic plugin validation to 23.7.0 due to known image inconsistencies in the previous operator versions that has already been fixed in 23.7.0+
=> PTX-20914 change min operator version for dynamic plugin validation

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/autopilotDeployment.yaml
QA is reporting to observe lots of frequent DEBUG repetitive logs from Autopilot pod. And since customer has the ability to set the log level at storagecluster spec, we'd like to change default to info from autopilot deployment so that only info/warn/error will show up
Closes #
Verified on testing cluster that with this change, by default only info/warn/error logs keep print out and once stc spec is edited with 
```
args:
log-level: debug
```
debug logs also show up
=> PWX-34916: changed the default log level for autopilot from debug to info

drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/testspec/nodeWiper.yaml, drivers/storage/portworx/testspec/nodeWiperPKS.yaml, drivers/storage/portworx/testspec/nodeWiperWithWipe.yaml, drivers/storage/portworx/uninstall.go
* will use `oci-monitor` image for node-wipes on PX-3.1.0 or higher
* also reduced the time till we start checking RedynessProbe
This changes the _DEFAULT_ NodeWiper image, to `oci-monitor`
* if `install.portworx.com/version` provided a distinct image for node-wiper, we'll use the one provided by `/version` -manifest
* change will apply only on px-3.1.0  (or higher)
Closes #  PWX-22131, PWX-34256   (part 3)
=> PWX-22131, PWX-34256 -pt3: oci-mon node-wiper

drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/testspec/nodeWiper.yaml, drivers/storage/portworx/testspec/nodeWiperPKS.yaml, drivers/storage/portworx/testspec/nodeWiperWithWipe.yaml, drivers/storage/portworx/uninstall.go
* will use `oci-monitor` image for node-wipes on PX-3.1.0 or higher
* also reduced the time till we start checking RedynessProbe
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1323 into `px-rel-23.12.0` branch
Closes # PWX-22131, PWX-34256 -pt3 (23.12.0)
=> PWX-22131, PWX-34256 -pt3 (23.12.0): oci-mon node-wiper (#1323)

drivers/storage/portworx/preflight.go
Preflight pod logging disappears after pre-flight pods terminate and we need to preserve logging for diagnostics.   So pass parameter specifying where to save pre-flight logging.  
Closes #
PWX-33232
Tested manually and inspected the output log on the node 
```
root@jose-1:/var/cores# cat px-pre-flight-output.log 
------------------------------------------------------------------------------
time="2023-11-11T01:18:23Z" level=info msg="Started logging into /var/cores/px-pre-flight-output.log"
time="2023-11-11T01:18:23Z" level=info msg="running in pre-flight mode..."
time="2023-11-11T01:18:23Z" level=info msg="Updated arguments: /px-oci-mon -T px-storev2 -c …
```
=> PWX-33232: Save logging from pre-flight pod for diagnostics.

deploy/olm-catalog/portworx/23.10.1/portworx-certified.clusterserviceversion.yaml, drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/util/util.go
The preflight provider name is derived from the k8s node.spec.provider
field. These values don't necessarily match with the portworx cloudops
providers. If we blindly set the preflight values to the cloud provider, it
leads to portworx crashing as it does not recognize that cloudops provider.
Reverting back to the old behavior where we only explicitly check for
vsphere. In future, we can either have common cloud providers between preflight
and cloudops or we can do the conversion somewhere before setting the cloud
provider in storagecluster spec.
Openshift operator upgrades happen one version at a time. If users go to
23.10.0, they will hit the bug where operator is incorrectly adding the cloud
provider in the storage cluster spec.
That's why we …
=> PWX-35067 (23.10.1): Don't set the cloud provider from preflight provider name (PR #1339)

drivers/storage/portworx/deployment_test.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/util/util.go
The preflight provider name is derived from the k8s node.spec.provider field. These values don't necessarily match with the portworx cloudops providers. If we blindly set the preflight values to the cloud provider, it leads to portworx crashing as it does not recognize that cloudops provider.
Reverting back to the old behavior where we only explicitly check for vsphere. In future, we can either have common cloud providers between preflight and cloudops or we can do the conversion somewhere before setting the cloud provider in storagecluster spec.
Closes # https://portworx.atlassian.net/browse/PWX-35067
=> PWX-35067 Don't set the cloud provider from preflight provider name

.travis.yml, Makefile, go.mod, test/integration_test/Dockerfile
Security scanners are complaining the `operator` was build via golang-1.20.x
* as a fix, we're upgrading the operator-build to golang-1.21.4  (latest stable)
Closes # PWX-34634
Quick test:
```
$ docker run --rm -it -v /tmp:/tmp --entrypoint bash zoxpx/px-operator:latest
bash-4.4$ cp /operator /tmp/
bash-4.4$ exit
$ go version /tmp/operator
/tmp/operator: go1.21.4
```
+ manual test: the new operator was able to deploy a functional PX cluster successfully.
=> PWX-34634: Upgrade build to golang-1.21

Makefile
* Adding `make tools-check` to check linter-tools versions
Makefile
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1272 into `px-rel-23.12.0` branch
Closes # -
=> Adding `make tools-check` to check linter-tools (#1272)

Makefile, README.md, build/Dockerfile
The security-scans keep raising issues in the base-container (UBI-8)
* as a fix, we're upgrading the base-container to the latest UBI-9jj
Closes # PWX-35044
Tested PX wipe + deployment manually -- PX deployed OK
Also checking the `kubectl cp` -- since this uses `tar` command inside the container:
```
$ kubectl cp portworx-operator-9d45c5c47-vvc9z:/operator /tmp/operagtor-copy
$ ls -al /tmp/operagtor-copy
-rw-r--r-- 1 zox users 65564672 Nov 17 11:56 /tmp/operagtor-copy
```
* this also worked OK
=> PWX-35044: Upgrade base-container to UBI-9

Makefile, build/Dockerfile
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1337 into `px-rel-23.12.0` branch
Closes #  PWX-35044 (23.12.0)
=> PWX-35044 (23.12.0): Upgrade base-container to UBI-9 (#1337)

test/integration_test/Dockerfile
Adding more checks into the `make integration-test-container`
ISSUE:
* the docker-build just downloads 2 executables from the Internet, without checking if they actually downloaded OK
FIX:
* changed `curl` -command flags, so it'll fail with `$? != 0` if download fails, also
* added basic `file`-test on the downloaded binaries
Closes # -
Manual test:
```
...
Sending build context to Docker daemon  78.23MB
Step 1/10 : FROM golang:1.21
---> 4c88d2e04e7d
Step 2/10 : RUN apt-get update &&     apt-get install -y jq file
---> Using cache
---> baf19866c7e8
Step 3/10 : RUN /usr/local/go/bin/go install gotest.tools/gotestsum@latest
---> Using cache
---> 2c432093b512
Step 4/10 : …
```
=> Integration-test image build fix

drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/util/util.go
Currently the storage PDB allows deletion of only one PX pod at any given time. This is to ensure we don't lose volume replica quorum. This allows user to knowingly change the PDB value and run the k8s upgrade faster by upgrading multiple nodes in parallel. The users who will use it understand the risk and we will document accordingly.
Closes # https://portworx.atlassian.net/browse/PWX-34411
=> PWX-34411 Allow overriding the min available value of px-storage PDB

drivers/storage/portworx/testspec/prometheusRule.yaml
**What this PR does / why we need it**: This PR corrects the UTs that fail due to changing the portworx docs in ticket PWX-35016
**Which issue(s) this PR fixes** :Closes # PWX-35138
**Special notes to the reviewer**: Initially, prometheus alerts - PXKvdbNodeViewUnhealthy and PXKvdbClusterViewUnhealthy used the metric label "{$labels.node_id}" to identify nodes which was not valid. The docs website was modified to change the prometheus-rules yaml to use "{$labels.node}" instead. This change has been verified in the prometheus UI as well.
=> Modifying UTs for docs change in PWX-35016

pkg/util/test/util.go
**What this PR does / why we need it**: Fixes incorrect validation for csi-node-driver-registrar inside portworx-api pods instead of oci-mon pods for older operators. PR-1334 is breaking automation as the changes made in the integration tests do not apply to older versions of operator. Hence temporarily the test has been changed to validate  csi-node-driver-registrar inside portworx-api pods only for master version - 99.9.9. This operator version needs to be modified when the fix in PR-1334 is to be released.
Closes # PTX-21234
=> PTX-21234: Fix incorrect validation for csi-node-driver-registrar inside portworx-api pods instead of oci-mon pods for older operators

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/preflight.go
Secrets are not setup when pre-flight is run so if security is enabled disable it for pre-flight pod so pre-flight checks can be run.   
Closes #
PWX-32111
Tested by enabling security on my k8s cluster and pre-flight ran fine.   Will retest on Rohits setup before merging in.
=> PWX-32111: Disable security when running pre-flight.

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/testspec/autopilotClusterRole.yaml, drivers/storage/portworx/testspec/autopilotClusterRole_k8s_1.24.yaml
Currently autopilot fails to generate AROs on OCP due to the lack of update permission of AR finalizer in its own clusterrole definition. Solution is to add such when the cluster is found to be on OCP. 
Closes #
After manually editing autopilot clusterrole to add "update" on "autopilotrules/finalizers", the error message of "_failed to insert watcher event due to: autopilotruleobjects.autopilot.libopenstorage.org \"pvc-e836c495-0eab-4a63-b9e8-1aa4481bee37-volume-resize\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" file="statehandlers.go:696_" is gone and ARO shows up correctly …
=> PWX-35255: add AR finalizers to clusterrole for autopilot on OCP

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/testspec/autopilotClusterRole.yaml, drivers/storage/portworx/testspec/autopilotClusterRole_k8s_1.24.yaml
* add autopilotrule finalizers permission to cluster role for all platform deployment
cherry-pick from [merged PR](https://github.com/libopenstorage/operator/pull/1368) in master
Closes #
=> PWX-35255: add AR finalizers to clusterrole for autopilot on OCP (#1368)

pkg/constants/constants.go
**What this PR does / why we need it**: During a Kubernetes node upgrade, the node is cordoned and drained of all pods. The operator uses an exponential backoff strategy, delaying the restart of the PX pod by 5s initially, and then increasing the delay with each deletion during the drain process. This approach ensures proper draining of applications using PX volumes, particularly CSI applications relying on the node's registration as a CSI node. After change in ticket PWX-34360, CSI node registrar container becomes a part of the portworx-api pod instead of Portworx pod. So portworx pod can be down.
This change increases the default restart delay of the portworx pod in a cordoned node to 5 minutes against the previous value of 5 seconds. Exponential backoff logic is continued with the …
=> PWX-35282: Do not restart portworx pod for 5m when the node is cordoned

pkg/constants/constants.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/update.go
**What this PR does / why we need it**: Before in ticket - PWX-34360, the csi-node-driver-registrar container was moved from px pods deployment to px-api daemonset. Change was also made such that every time stc was updated, the px-api pod of the corresponding px pod node will also be deleted. This was done so that csi driver will be reregistered. The deletion of px-api pods in update stc logic had a flaw as mentioned in ticket PWX-35173. This PR moves the deletion of px-api pods to happen during the creation of the px-pods. This will take care of edge cases.
Closes # PWX-35173
**Testing notes**:
a) During update of storage cluster
1) Storage cluster and older version of operator are running
2) Update the operator version to one with this change …
=> PWX-35173: Move the deleting of portworx-api pod for re registering csi driver from update stc logic to create px-pod logic

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/components_test.go, pkg/apis/core/v1/storagecluster.go, pkg/apis/core/v1/zz_generated.deepcopy.go
[PR830](https://github.com/libopenstorage/operator/pull/830) was supposed to add gitops support to autopilot through stc configuration. But it fails to do so due to the fact that wrong type of defaultReviewers parameter is processed (expected array but got string). This bug will cause operator to go down and couldn't generate anticipated autopilot configmap with gitops config definition
Closes #
Before the change, operator breaks down if in stc spec we have definition of gitops like:
`    autopilot:
args:
log-level: debug
min_poll_interval: "10"
enabled: true
gitops:
params:
baseUrl: https://bitbucket-staging.dev.purestorage.com
branch: master
defaultReviewers:
- …
=> PWX-35330: fixed gitops spec definition

pkg/util/test/util.go
Do not expect PX pods to be deployed on infra nodes during validation, this is needed for ROSA clusters
=> PTX-21227 Do not expect PX pods to be deployed on infra nodes during validation

drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go
The `manifest.GetVersions()` was not working correctly for intermediate test-builds and test image-tags
* (i.e. `portworx/oci-monitor:c2bb2a0_14e4543` instead of `...oci-monitor:3.1.0`)
FIX:
* we are adding a failback in case the correct px-version could not get extracted from the image-tag
PWX-22131,PWX-34256 -- part 4
NOTE: this fixes the _"nodewiper via oci-monitor"_ feature that got introduced in `px-3.1.0`
Please expedite the review, since this fix is for both operator:23.10.2 and porx:3.1.0
=> PWX-22131,PWX-34256_pt4: Version parsing fix

drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1383 into `px-rel-23.10.2` branch
PWX-22131,PWX-34256_pt4 (px-rel-23.10.2)
=> PWX-22131,PWX-34256_pt4 (px-rel-23.10.2): Version parsing fix (#1383)

drivers/storage/portworx/uninstall.go, drivers/storage/portworx/util/util.go, drivers/storage/portworx/util/util_test.go
Adding custom user-volumes to the node-wiper spec
The portworx-install can be customized using user-volumes
* i.e. ~/opt/pwx~ -> `/usr/local/portworx` by adding `spec.Volume` -override
```yaml
kind: StorageCluster
apiVersion: core.libopenstorage.org/v1
spec:
volumes:
- name: custom-opt
mountPath: /opt/pwx
hostPath:
path: /usr/local/portworx
```
However, in such customized installs, for the cleanup to work correctly, we have to provide the same custom user-volumes to the node-wiper image
* note, the new node-wiper is smart enough to detect the install-dir overrides, and can perform the cleanup/wipe correctly --  but it'll need the correct user-volumes setup
Closes # PWX-34256
**Special notes for your …
=> PWX-34256: node-wiper fix for custom-dir installs

drivers/storage/portworx/uninstall.go, drivers/storage/portworx/util/util.go, drivers/storage/portworx/util/util_test.go
drivers/storage/portworx/util/util.go
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1388 into `px-rel-23.10.2` branch
Closes #  PWX-34256 (op-23.10.2)
=> PWX-34256_op-23.10.2: node-wiper fix for custom-dir installs (#1388)

deploy/plugin/plugin-deployment.yaml, drivers/storage/portworx/testspec/plugin-deployment.yaml
**What this PR does / why we need it**: The ImagePullPolicy of dynamic-plugin pod is set ti 'IfNotPresent, an upgrade in operator will not pull latest image with same tag for dynamic plugin (same tag might have security fixes) 
Closes # https://portworx.atlassian.net/browse/PWX-35771
=> PWX-35711: Update dynamic-plugin ImagePullPolicy to Always

pkg/preflight/pks.go
The pks distribution string was incorrect and triggered incorrect mounts to be added to the telemetry spec when running on gke install.  Change the the string be 'pks'.
Closes #
PWX-35704
=> PWX-35704: The pks distribution string was incorrect.  Change it from  'gke' to 'pks'

pkg/preflight/pks.go
The distribution string was incorrect for PKS.  Resulting in wrong mounts for 'gke'.   Use the correct string.
Closes #
PWX-35704
=> PWX-35704: Cherry pick correct distribution string for PKS

drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/stork_test.go, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go
This PR fixes the following issues:
* the `kubeControllerManager`, `kubeScheduler`, and `pause` images were not included in `StorageCluster.spec.desiredImages` list, also
* the `kubeScheduler` needs to be _bound_ to the `stork` image - if `stork` is disabled, both `kubeScheduler` and `stork` images should be removed from the `desiredImages` list
* finally, it should be possible to update the `kubeScheduler` image via `px-versions` ConfigMap
Closes # PWX-35007, PWX-35008
Manual testing:
Test1:
* deployed cluster using custom `px-version` ConfigMap, overriding all images to `10.13.1.19/portworx/*`
* also, STORK was NOT enabled
```
status:
clusterName: …
```
=> PWX-35007, PWX-35008: kube-scheduler image updates

drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/components_test.go
**What this PR does / why we need it**: This ticket fixes all issues that were found while running integration tests on px-rel-23.10.3 branch.
Closes # PWX-35865 and PWX-35867
**Testing notes: The following cases were tested manually:**
1) fresh installation of operator with current changes:
i) install px verison <2.13 - no change in current behavior
ii) install px version>=2.13 - px-api pods have csi-registrar containers, oci-monitor pod have only 1 container
iii) px version>=2.13 , csi disabled - both px-api and oci-monitor pods have 1 container each
2) Existing PX installation with older operator image, update operator image first then upgrade px
i) start with px version<2.13, upgrade operator - no change in px api pods
upgrade px version but …
=> PWX-35865 : Fixing moving csi registrar to pc-api pod gaps due to PR #1334

drivers/storage/portworx/component/portworx_api.go, drivers/storage/portworx/components_test.go
**What this PR does / why we need it**: Cherrypick for PR [#1406](https://github.com/libopenstorage/operator/pull/1406)
into px-rel-23.10.3 branch
=> [Cherry-pick] : Resolving bugs for 23.10.3 release

drivers/storage/portworx/component/autopilot.go
Cherrypick https://github.com/libopenstorage/operator/pull/1415
=> [cherrypick] OCP 4.14 : Fix Mount volume to autopilot pod only if secret is created

drivers/storage/portworx/component/autopilot.go
**What this PR does / why we need it**: We should mount token and sertificates to autopilot pod only if autopilot-prometheus-auth secret is created, otherwise autopilot pod will start failing to come up and mounting error.
Extension of PR https://github.com/libopenstorage/operator/pull/1410
=> OCP 4.14 : Fix Mount volume to autopilot pod only if secret is created

drivers/storage/portworx/component/plugin.go, drivers/storage/portworx/components_test.go
**What this PR does / why we need it**: Update imagePullPolicy for px-plugin pods to always, regardless of STC's ImagePullPolicy, to fetch latest security/other fixes on existing tag.
The imagePullPolicy for the pod is now being set to Always, after StorageClusterSetting is applied, so that STC's PullPolicy doesn't override.
Verified that ImagePullPolicy of plugin pod is set to 'Always' if
- ImagePullPolicy in Storagecluster pod is set to 'IfNotPresent'
- ImagePullPolicy in Storagecluster pod is set to 'Always'
=> Update plugin deployment PullPolicy to Always regardless of STC's PullPolicy

pkg/util/test/util.go, test/integration_test/basic_test.go, test/integration_test/utils/storagecluster.go
Fix tests for autopilot changes on OCP 4.14+
* Disabled tests that check and test PX Prometheus if deployed on OCP 4.14+
* Added check for OCP and Operator versions to deploy configmap to make autopilot work with OCP 4.14+ Prometheus instead of PX Prometheus
=> PTX-22144 Fix tests for autopilot changes on OCP 4.14+

pkg/util/test/util.go
Validate PX pods correctly when if portworx.io/run-on-master is passed and is set to True in annotations in the PX StorageCluster
NOTE: This is needed to validated correctly when running `ValidateStorageCluster()` if `portworx.io/run-on-master: true` is passed
=> PTX-22165 Validate PX pods correctly when if portworx.io/run-on-master is passed and is set to True in annotations in the PX StorageCluster

test/integration_test/basic_test.go, test/integration_test/utils/px_operator.go
Disable Alertmanager and Grafana tests for OCP 4.14+ and 23.10.3+
=> PTX-22180 Disable Alertmanager and Grafana tests for OCP 4.14+ and 23.10.3+

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
- Starting OCP 4.14 we recommend using OCP user workload prometheus to be used for Portworx and Autopilot. That is why we will disable prometheus from STC spec if the user enables it on this environment. This will be done only on first/fresh installs. We will not change it again if the user overwrites that back to "enabled".
- We also raise a warning when disabling it so the user knows why we did that.
- Unrelated change: Checking openshift version only if the autopilot providers are not set. That way we don't end up querying the K8s API server repeatedly.
Closes # https://portworx.atlassian.net/browse/PWX-36015
UTs added.
=> PWX-36015 Disable PX-prometheus for OCP 4.14+ on new installs

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
- Starting OCP 4.14 we recommend using OCP user workload prometheus to be used for Portworx and Autopilot. That is why we will disable prometheus from STC spec if the user enables it on this environment. This will be done only on first/fresh installs. We will not change it again if the user overwrites that back to "enabled".
- We also raise a warning when disabling it so the user knows why we did that.
- Unrelated change: Checking openshift version only if the autopilot providers are not set. That way we don't end up querying the K8s API server repeatedly.
Closes # https://portworx.atlassian.net/browse/PWX-36015
UTs added
=> [Cherrypick] PWX-36015 Disable PX-prometheus for OCP 4.14+ on new installs

drivers/storage/portworx/util/util.go
The px-operator should not assume the K8s cluster is running a default domain `.svc.cluster.local`
FIX:
* as a fix, we will use `portworx-api.<namespace>` hostname
* this relies on `/etc/resolv.conf` to supply `search <domain>` statements
Closes #  PWX-32899  (part 1)
Tested manually on a K8s cluster with modified DNS domain -- Px still deploys correctly, and no significant errors observed in operator's log.
Note also that the `plugin` [@.../component/plugin.go](https://github.com/libopenstorage/operator/blob/master/drivers/storage/portworx/component/plugin.go#L325) still uses the `.svc.cluster.local` default DNS domain
* this DNS-domain was not changed, since plugin …
=> PWX-32899_pt1: K8s DNS domain fix

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/testspec/autopilotDeployment_Openshift_4_14.yaml
Our container-mount for Destination:/etc/ssl/certs/ca-certificates.crt was overriding (removing) the system-CA bundle /etc/ssl/certs/ca-bundle.crt (/etc/pki/tls/certs/ca-bundle.crt) inside the container.
since the https://thanos-querier-openshift-monitoring… SSL cert was signed by the issuer: C=US; O=Let's Encrypt; CN=R3 – we needed the original system-CA bundle to verify this SSL certificate chain
We need to change the path where  operator is mounting the certificate currently, as that ovverides existing certificate bundle.
With this change, operator mounts custom-certs at /etc/ssl/px-custom/1  (can also do /etc/ssl/custom/2 , 3, 4 -- if needed)
Closes # https://portworx.atlassian.net/browse/PWX-36029 …
=> [PWX-36029] Update certificate's mountpath in autopilot pod

drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/components_test.go
**What this PR does / why we need it**: As a part of PWX-34411, PDB value for px-storage can be overridden using an annotation, but when the value is greater than or equal to total storage nodes, it prevents upgrades from happening as allowed disruptions becomes 0. This PR ensures than if the annotation value is greater than or equal to total storage nodes, then the default calculation for pdb is used.
Closes # PWX-35633
=> PWX-35633 : Don't allow overriding storage PDB value to more than number of storagenodes

drivers/storage/portworx/components_test.go
Add more UTs for https://github.com/libopenstorage/operator/pull/1410
Added new cases : 
1. test Autopilot install when user workload monitoring is not enabled
2. test Autopilot deployment and Secret after disabling and enabling autopilot
3. test Autopilot default provider URL on OCP 4.14
Existing cases covered : 
1. test if user-workload can be enabled on non-openshift servers for AutoPilot
2. test if user-workload can be enabled on 4.14 version of openshift for AutoPilot
3. test if install can be enabled on 4.13 version of openshift for AutoPilot
4. test Autopilot install and Uninstall on ocp cluster 4.14
5.  Disable prometheus on new install for OCP 4.14+, even if set by the user
6. Do not disable prometheus on existing install if set by the user
=> Add UTs for openshift prometheus on OCP 4.14

drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/components_test.go
**What this PR does / why we need it**: We should not allow PDB value for px-storage to be overridden by annotation to a value such that portworx quorum is lost during the upgrade. This PR ensures than the annotation value will not be utilised if it is lesser than num(storageNodes)/2 +1 . In such cases the default PDB calculated value will be used
Closes # PWX-36258
=> PWX-36258 : Do not allow pdb annotation lesser than px quorum

drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/components_test.go
We got complaints that the PX deployments on OpenShift spin up `portworx-pvc-controller-XXX` PODs
* apparently, in vSphere deployments, this results in spamming vSphere/vCenter with storage tasks
FIX:
* as a fix, we're changing the defaults in which configs will we set up PVC-controller
- we'll SKIP setting up the PVC-controller in OpenShift distros  (unless explicitly turned on via `portworx.io/pvc-controller: "true"`)
* also adding a targeted unit-test
Closes # PWX-31625
Some manual test results:
* confirmed generic Kubernetes deployment in "portworx" namespace still NEEDS PVC-controller when using in-tree driver
- without the PVC-controller, the PVC never gets …
=> PWX-31625: Turning off PVC-Controller on OpenShift

drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/components_test.go
this is a cherry-pick of https://github.com/libopenstorage/operator/pull/1297 into `release-24.1.0` branch
PWX-31625   (24.1.0)
=> PWX-31625_24.1.0: Turning off PVC-Controller on OpenShift (#1297)

deploy/ccm/metrics-collector-deployment.yaml, drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/component/telemetry_java.go, drivers/storage/portworx/manifest/manifest.go
In master, we already reconcile the metrics collector.
This PR
- Remove the reconcile checks for metrics collector
- Updates the metrics collector to the latest version.
PWX-35377
Testing note:
Used local cluster with custom operator image. It successfully created the px-telemetry-metrics-collector pod and has logs with success upload below:
```
{"bytes":3431,"level":"info","metrics_identifier":"portworx","msg":"Forwarding complete","package":"forwarder","response":"{\"context\":{\"request_uuid\":\"a652d72a-938a-4d9a-80b9-494d92a6609c\",\"product_name\":\"portworx\",\"appliance_id\":\"8afc048e-1818-4b17-a41c-0923f49ac2de\",\"component_sn\":\"portworx-metrics-node\"},\"re …
```
=> PWX-35377 Update metrics collector version

drivers/storage/portworx/components_test.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/util/util.go
**What this PR does / why we need it**: This PR is to add support for Openshift Prometheus with Portworx on Redhat Versions greater or equal 4.12. Currently, this is supported on minimum OCP version 4.14.
Closes #  https://portworx.atlassian.net/browse/PWX-36274
=> Support OCP prometheus for OCP versions GTE 4.12

drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/stork_test.go, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1376 into `release-24.1.0` branch
PWX-35007, PWX-35008  (rel-24.1.0)
=> PWX-35007, PWX-35008 _rel-24.1.0: kube-scheduler image updates (#1376)

drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/manifest/manifest_test.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, pkg/controller/storagecluster/stork.go, pkg/controller/storagecluster/stork_test.go, pkg/util/k8s/k8s.go, pkg/util/k8s/k8s_test.go
* PWX-35007: kube-scheduler image handling fix
drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go
drivers/storage/portworx/portworx_test.go
pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/stork_test.go
pkg/util/k8s/k8s.go
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1376 into `release-23.10.4` branch
PWX-35007, PWX-35008  (rel-23.10.4)
=> PWX-35007, PWX-35008 _rel-23.10.4: kube-scheduler image updates (#1376)

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
* the `Status.DesiredImages.{KubeControllerManager,KubeScheduler,Pause}` will get re-validated every time
- portworx version changes, or
- kubernetes version changes, or
- StorageCluster `spec.autoUpdateComponents` is used
The `Status.DesiredImages.{KubeControllerManager,KubeScheduler,Pause}` are the "sticky image versions" which once set, will be preferred when generating K8s deployments and pods
ISSUE:
* however, once these images are set, we never invalidated them (they never changed)
- this means the image did not change when K8s version updated or,
- when PX version for updated, nor
- when `spec.autoUpdateComponents` was used
FIX:
* as a fix, we'll reset the `Status.DesiredImages.{KubeControllerManager,KubeScheduler,Pause}` when K8s or PX …
=> PWX-35007,PWX-36364: fixing re-validation of DesiredImages.Kube*

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
* the `Status.DesiredImages.{KubeControllerManager,KubeScheduler,Pause}` will get re-validated every time
- portworx version changes, or
- kubernetes version changes, or
- StorageCluster `spec.autoUpdateComponents` is used
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1473 into `release-24.1.0` branch
PWX-35007,PWX-36364
=> PWX-35007,PWX-36364_24.1.0: fixing re-validation of DesiredImages.Kube* (#1473)

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
* the `Status.DesiredImages.{KubeControllerManager,KubeScheduler,Pause}` will get re-validated every time
- portworx version changes, or
- kubernetes version changes, or
- StorageCluster `spec.autoUpdateComponents` is used
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1473 into `release-23.10.4` branch
PWX-35007,PWX-36364
=> PWX-35007,PWX-36364_23.10.4: fixing re-validation of DesiredImages.Kube* (#1473)

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/util/util.go, drivers/storage/portworx/util/util_test.go
> Using ca.crt and token doesn't authenticate openshift's Prometheus endpoint on OCP 4.15.
> As per suggestion from Redhat, using ca.crt and token of thanos-ruler-token secret rather than prometheus-user-workload-token secret.
> For other OCP supported versions ( < 4.15) , there will be no change.
Closes # https://portworx.atlassian.net/browse/PWX-35994
**Testing**:
> Tested on vsphere OCP 4.14 and OCP 4.15
=> Support Openshift Prometheus on OCP 4.15

deploy/olm-catalog/portworx/23.10.4/portworx-certified.clusterserviceversion.yaml
Redhat has enforced the presence of following metadata. Their certification pipelines will FAIL for all new operator bundle releases that DO NOT use this metadata format. 
Here's the meaning of each of the fields added
-   **features.operators.openshift.io/disconnected**: Specify whether an Operator leverages the spec.relatedImages CSV field and can run without an internet connection by referring to any related image by its digest.
-   _**_features.operators.openshift.io/fips-compliant_**_: Specify whether an Operator accepts the FIPS-140 configuration of the underlying platform and works on nodes that are booted into FIPS mode. In this mode, the Operator and any workloads it manages (operands) are solely calling the Red Hat Enterprise Linux (RHEL) …
=> [23.10.4] PWX-36428 : Add metadata annotations in CSV for openshift catalog

test/integration_test/bluegreen_test.go
* replacing ..
- "pxctl license extend", with
- "pxctl license expand"
We changed the CLI keyword, and forgot to update the test
Note:
* the `extend` triggers usage, while `expand` keyword works OK
```
Error: Subcommand is missing or invalid. This command requires a valid sub-command.
Usage:
pxctl license [flags]
...
Use "pxctl license [command] --help" for more information about a command.
License expansion status: not active
```
Closes # --
=> BlueGreen license integration test fix  [trivial]

deploy/olm-catalog/portworx/99.9.9/portworx-certified.clusterserviceversion.yaml
Redhat has enforced the presence of following metadata. Their certification pipelines will FAIL for all new operator bundle releases that DO NOT use this metadata format. 
Here's the meaning of each of the fields added
-   **features.operators.openshift.io/disconnected**: Specify whether an Operator leverages the spec.relatedImages CSV field and can run without an internet connection by referring to any related image by its digest.
-   _**_features.operators.openshift.io/fips-compliant_**_: Specify whether an Operator accepts the FIPS-140 configuration of the underlying platform and works on nodes that are booted into FIPS mode. In this mode, the Operator and any workloads it manages (operands) are solely calling the Red Hat Enterprise Linux (RHEL) …
=> PWX-36428 : Add metadata annotations in CSV for openshift catalog

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go
**What this PR does / why we need it**: Previously, default value of maxStorageNodesPerZone was being set before the tolerations were added to the storagecluster. This caused a problem when the annotation to run on master was set. The toleration to noSchedule on master was not added to the storagecluster and thus when setting maxStorageNodesPerZone, it was considered that the master node is not schedulable and hence not counted for setting the value. 
Closes # PWX-36298
**Special notes for your reviewer**: This PR cannot be merged to master as it has diverged
**Testing steps** : 
Testing to see all nodes run portworx
1) In OCP cluster, deploy the operator with this change. 
2) In the storage cluster stc, add annotation - ` …
=> PWX-36298 - Set node tolerations before maxStorageNodesPerZone

Makefile
Fix for build catalog using internal artifactory
Tested locally:
```
[root@maxb-dev operator]# DOCKER_HUB_REPO=pure-artifactory.dev.purestorage.com/px-docker-prod-virtual/portworx DOCKER_HUB_OPERATOR_TAG=36e102b make catalog
Makefile:8: DOCKER_HUB_OPERATOR_IMG not defined, using 'px-operator' instead
Makefile:16: DOCKER_HUB_OPERATOR_TEST_IMG not defined, using 'px-operator-test' instead
Makefile:20: DOCKER_HUB_OPERATOR_TEST_TAG not defined, using 'latest' instead
Makefile:24: DOCKER_HUB_BUNDLE_IMG not defined, using 'portworx-certified-bundle' instead
Makefile:28: DOCKER_HUB_REGISTRY_IMG not defined, using 'px-operator-registry' instead
Makefile:32: BASE_REGISTRY_IMG not defined, using …
```
=> Fix for build catalog using internal artifactory

pkg/util/test/util.go, test/integration_test/main_test.go, test/integration_test/operator-test-pod-template.yaml, test/integration_test/portworx_diag_test.go, test/integration_test/test-deploy.sh, test/integration_test/utils/constants.go
- Allow to pass namespace param where the operator is deployed
- Also improved error handling for PTX-22684
Operator Integration tests always used hard coded "kube-system" as the namespace for operator deployment. With this change, we can pass the namespace as a variable explicitly specifying where the px-operator is deployed and also where the operator-test pod will be deployed. This will be useful when we want to run integration tests along with torpedo tests from a single pipeline job. 
Also this PR improves error handling in cases where operator version might return nil resulting in null pointer exception in util/test/util.go
Closes # PTX-17953, PTX-22684
=> [PTX-17953] Allow to pass namespace param where the operator is deployed

drivers/storage/portworx/component/securitycontextconstraints.go, pkg/controller/storagecluster/storagecluster.go
Cherrypick https://github.com/libopenstorage/operator/pull/1491 to 23.1.0.5
=> [cherrypick 23.10.5] PWX-36460 : Enforce portworx SCC on portworx pods

deploy/crds/core_v1_storagecluster_crd.yaml, deploy/crds/core_v1_storagenode_crd.yaml
**What this PR does / why we need it**: When using [kubeconform](https://github.com/yannh/kubeconform) to validate CRDs, the StorageCluster CRD was being reported as invalid due to the CRD schema definition not possessing the keywords 'kind', 'metadata' and 'apiVersion'. This PR would make the CRD schema definition more complete and allow a more strict validation of the StorageCluster resource.
Closes #
=> Add additional properties to the crd schema definitions

drivers/storage/portworx/component/securitycontextconstraints.go, pkg/constants/metadata.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/update.go
- The `openshift.io/required-scc` was added to the portworx pod during creation. But it was getting removed during updating the custom annotations on the px pod. Fixed this by adding it to known pod annotation so we don't skip it.
- Added UTs for all required-scc changes.
Closes # https://portworx.atlassian.net/browse/PWX-36649
=> PWX-36649 Keep the required-scc annotation if added during creation

drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/testspec/portworxClusterRole.yaml
**What this PR does / why we need it**: There are few error logs seen in Portworx like **cannot get resource \"namespaces\" in API group \"\" in the namespace** , because Portworx Clusterrole does not have namespace resource permission. This PR adds the permission for namespace resource to Portworx Clusterrole.
Closes # https://purestorage.atlassian.net/browse/PWX-36730
- Verified on OCP 4.14 and OCP 4.15
- Verified by creating apps and volume encryption, which hits the code path where it needs namespace resource access.
- No Forbidden error is seen.
=> PWX-36730 : Add namespace resource access permission to Portworx clusterrole

pkg/constants/metadata.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go
**What this PR does / why we need it**:This change is to help in the parallel upgrade feature and is a part of [this](https://purestorage.atlassian.net/browse/PWX-25414) epic. A unique label, in this case kubernetes node name that the portworx pod is running in is added to all the portworx pods.
Closes #  PWX-36170
=> PWX-36170: Adding k8s node name as label to all px pods

drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/util/util.go
**What this PR does / why we need it**: PVC controller is in CrashLoopBackOff when deployed on k3s master node because of  following error.
**failed to create listener: failed to listen on 0.0.0.0:10257: listen tcp 0.0.0.0:10257: bind: address already in use"**
The default ports 10252 and 10257 for PVC are already in use on k3s clusters. This PR chenges the default config, and uses port numbers 10260 and 10261 on k3s deployment.
Closes # https://purestorage.atlassian.net/browse/PWX-36159
- Verified on k3s cluster, with pvc annotation enabled.
-  All 3 PVCs pods are running fine
I0403 12:46:30.728036       1 secure_serving.go:213] Serving securely on 0.0.0.0:10261
=> PWX-36159: Use different port for PVC deployment on k3s

drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/component/securitycontextconstraints.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/testspec/portworxClusterRole.yaml, drivers/storage/portworx/util/util.go, pkg/controller/storagecluster/storagecluster.go
Cherrypick following PRs to 24.1.0
https://github.com/libopenstorage/operator/pull/1510
https://github.com/libopenstorage/operator/pull/1506
https://github.com/libopenstorage/operator/pull/1491
=> [cherrypick] [24.1.0] PWX-36159 , PWX-36730 , PWX-36460

test/integration_test/basic_test.go, test/integration_test/main_test.go, test/integration_test/operator-test-pod-template.yaml, test/integration_test/test-deploy.sh, test/integration_test/utils/aetos/dashboardutil.go, test/integration_test/utils/aetos/log.go, test/integration_test/utils/aetos/restutil.go, test/integration_test/utils/storagecluster.go
This purpose of this PR is to integrate Aétos with operator integration tests.
main_test.go is modified to init the Aetos Dashboard (functions defined under `test/integration_test/utils/aetos`)
run time flags are also modified as constants to beautify the code. No change to parsing logic for these flags.
basic_test.go has 2 additions: testCase `BasicInstallAetosDemo` and test `TestBasicInstall`
We would need to update other testCases as per `BasicInstallAetosDemo` and test `TestStorageClusterBasic` as per `TestBasicInstall` for correct reporting into Aétos. 
storagecluster.go has 2 additions as well: functions `DeployAndValidateStorageClusterAetosDemo` and `UninstallAndValidateStorageClusterAetosDemo`
The reason for putting these Demo functions is that the current implementation for …
=> PTX-16508 Aetos Wrap for Operator Integration Test

pkg/util/test/util.go
Fixing Telemetry output validation with `PX_LOGLEVEL` set to `debug`
=> PTX-23460 Fixing Telemetry output validation with PX_LOGLEVEL set to debug

test/integration_test/utils/marketplace.go
**What this PR does / why we need it**: Increase timeout for waiting for InstallPlan when deploying PX Operator via OCP Marketplace
Closes # https://purestorage.atlassian.net/browse/PTX-23694
=> PTX-23694 Increase timeout for waiting for InstallPlan when deploying PX Operator via OCP Marketplace

drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go
What this PR does / why we need it:
When security is enabled and guest access is disabled, operator fails to make API call to PX service to get KVDB members info with following error : Access denied without authentication token
As a fix, we are using context that uses token for authenticating the request with the SDK server.
Which issue(s) this PR fixes (optional)
Closes # https://purestorage.atlassian.net/browse/PWX-36838
=> PWX-36838 : Failed to validate PX node after StorageCluster update, Access denied without authentication token 

drivers/storage/portworx/component/securitycontextconstraints.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/portworxSCC.yaml, drivers/storage/portworx/testspec/portworxSCC_Openshift.yaml
Cherrypicking https://github.com/libopenstorage/operator/pull/1534 again to 24.1.0, as the commits are lost because of force push to 24.1.0-release branch
=> [cherrypick 24.1.0] PWX-36663 : Remove px-prometheus user from Portworx SCC for OCP 4.12+

drivers/storage/portworx/component/auth.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/status.go, drivers/storage/portworx/status_test.go, drivers/storage/portworx/util/util.go, pkg/controller/portworxdiag/portworxdiag.go
**Issue :** PX Security was not getting disabled even after updating spec.Security.Enabled field from true to false in Storage cluster.
**Reason :**  The change was introduced as part of PWX-25339, where one extra call to Portworx service was added during rolling update to make sure that KVDB does not go out of quorum during rolling updates. 
This introduced an issue when security was disabled from previously enabled value, the update on storagenodes is still not done at the point when this API call made, so even thought security is disabled from STC, storagenode is still not in sync and expects token to be passed by the operator during GRPC call.
**Fix**
As a fix, we are bypassing security enabled check in case of this particular GRPC call
1. …
=> PWX-37153 : Skip security check while fetching KVDB members

pkg/constants/metadata.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/update.go, pkg/controller/storagecluster/util.go
If we have marked the node unschedulable in the previous Reconcile(), we have to pick that node first. Otherwise, we may end up making too many nodes unschedulable.
Also, retry when add/remove of node label fails with conflict error so we don't wait for another 30 seconds.
PWX-34271
=> PWX-34271: pick the pods on unschedulable nodes for update first

deploy/ccm/metrics-collector-deployment.yaml, drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/component/telemetry_java.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/manifest/manifest.go, drivers/storage/portworx/testspec/ccmGoCollectorConfigMap.yaml, drivers/storage/portworx/testspec/metricsCollectorConfigMap.yaml
**What this PR does / why we need it**: Revert https://purestorage.atlassian.net/browse/PWX-35377 from 24.1.0
Reverted PR : https://github.com/libopenstorage/operator/pull/1460
Closes # https://purestorage.atlassian.net/browse/PWX-37237
=> PWX-37237 : Revert PWX-35377 Update metrics collector version and remove metrics-collector

drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/components_test.go, pkg/util/util.go
**What this PR does / why we need it**: As suggested during the TOI presentation, we will add an event in the storagecluster when the user sets the value of minAvailable for px-storage PDB using annotation. An event will be logged if this value is valid, invalid, and everytime the annotated value is changed. It also gets raised once everytime an incorrect value is either changed to default or correct value is given. Here is the list of scenarios and its expected events raised
| Storage cluster state                                           | Event             |
|-----------------------------------------------------------------|-------------------|
| Fresh px install , default PDB                                  | No event          |
| Fresh px install, correct PDB annotation …
=> PWX-37274 : Adding events for setting PDB using annotation

drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/components_test.go, pkg/util/util.go
**What this PR does / why we need it**: Cherrypick of [#1548](https://github.com/libopenstorage/operator/pull/1548) into 24.1.0 release branch
=> [Cherry-Pick]: Cp PWX-37274

pkg/util/test/util.go
**What this PR does / why we need it**: This is a fix for the integration tests where a custom secure port is checked for pvc controller as well for k3s clusters
Closes # PTX-23958
=> PTX-23958: Check custom secure port in k3s for pvcController in tests

drivers/storage/portworx/util/util.go, pkg/controller/storagenode/storagenode.go, pkg/controller/storagenode/storagenode_test.go
**What this PR does / why we need it:**
The PDB value for px-storage is not changing if PX service is stopped on a node by labelling with px/service=stop label.
Reason :
This was happening because when we label our node with px/service=stop , the label storage=true was getting removed from PX pods, since to decide whether node can be storagenode or not, operator checks only status of the storagenode and not rely on any parameter.
The PR fixes this behaviour and uses NonQuorumMember flag to decide storage/storageless node.
- a node will be considered storage node if we PX version is >= 3.1.0 , and the node is a quorum member after Node is not in Initializing state
- a node will be considered storageless node if we PX version is >= 3.1.0 , and the node is not a quorum member after Node is …
=> PWX-37266 : Upgrade should not continue when PDB value is set to 1 and there is already a PX node down

drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/util/util.go, pkg/util/test/util.go
**What this PR does / why we need it**: Similar to [#1510](https://github.com/libopenstorage/operator/pull/1510) , same issue is seen in rke2 cluster. Solution is to check if cluster is k3s or rke2 and add a custom pvccontroller port
Closes # PWX-37366
=> PWX-37366: Add function to check if k3s deployment or rke2

drivers/storage/portworx/component/pvccontroller.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/deployment.go, drivers/storage/portworx/util/util.go
**What this PR does / why we need it**: Cherry-pick of PR [#1555 ](https://github.com/libopenstorage/operator/pull/1555) into 24.1.0
=> [Cherry-Pick]: [24.1.0] Cherry-pick of  PR #1555 

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/kubevirt.go, pkg/controller/storagecluster/kubevirt_test.go, pkg/controller/storagecluster/update.go, pkg/mock/kubevirtmanager.mock.go
When deciding whether a running virt-launcher pod needs to be evicted, we now also check if the VMI
is active on the same node. If VMI says that it is running on a different node and
there is no live-migration in progress, we skip the eviction for that pod since the pod should go
into a completed state on its own.
Also, we now call shouldEvictPod only for the virt-launcher pods on the subset of nodes
due for the update in the current Reconcile() iteration to avoid invoking k8s APIs unnecessarily.
When starting live-migration, we now have an additional check to see if the live-migration
succeeded for the same VM in the same upgrade cycle. If yes, we don't start an additional
live-migration and generate an event instead. We were already doing this for …
=> PWX-37480: avoid starting extra live-migraions for the same VM

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/kubevirt.go, pkg/controller/storagecluster/kubevirt_test.go, pkg/controller/storagecluster/update.go, pkg/mock/kubevirtmanager.mock.go
When deciding whether a running virt-launcher pod needs to be evicted, we now also check if the VMI is active on the same node. If VMI says that it is running on a different node and there is no live-migration in progress, we skip the eviction for that pod since the pod should go into a completed state on its own.
Also, we now call shouldEvictPod only for the virt-launcher pods on the subset of nodes due for the update in the current Reconcile() iteration to avoid invoking k8s APIs unnecessarily.
When starting live-migration, we now have an additional check to see if the live-migration succeeded for the same VM in the same upgrade cycle. If yes, we don't start an additional live-migration and generate an event instead. We were already doing this for …
=> [cherry-pick] PWX-37480: avoid starting extra live-migraions for the same VM (#1560)

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/kubevirt.go, pkg/controller/storagecluster/kubevirt_test.go, pkg/controller/storagecluster/update.go, pkg/mock/kubevirtmanager.mock.go, pkg/util/util.go
If the live-migration is in progress for a VM that we want to evict, do not create another live migration for that VM in the same Reconcile() cycle.
Just before starting a live-migration, check the VMI one more time to verify that the VMI is pointing to the same node as the pod being evicted.
These two extra checks reduce the window in which PX and operator may try to live-migrate the same VM out of the same node. Also, it handles any other unexpected live-migrations that might start.
PWX-37573
=> PWX-37573: tighten the checks for avoiding unnecessary VM live migration

deploy/crds/core_v1_storagecluster_crd.yaml, pkg/apis/core/v1/storagecluster.go
This PR will add a new field to control the PX upgrade behavior. The default behavior would be to have a non-disruptive upgrade. But users should be able to disable that and go back to the old behavior of upgrading nodes in parallel without worrying about the disruption. 
Closes # https://purestorage.atlassian.net/browse/PWX-36509
=> StorageCluster schema changes to support parallel portworx upgrades

drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/util/util.go, pkg/constants/metadata.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go
**What this PR does / why we need it**: Cherrypick of PRs - [#1503](https://github.com/libopenstorage/operator/pull/1503) and [#1508](https://github.com/libopenstorage/operator/pull/1508) into smart and parallel upgrades feature branch
=> [Cherry-pick into feature]: Cherry-pick of all tickets related to Smart and parallel upgrades merged into master

drivers/storage/portworx/component/plugin.go
* note, fixing the remaining use of `.svc.cluster.local` DNS domain in the GUI plugin
* note: the tests are still creating mock host-entries with `.svc.cluster.local` DNS domain in the `/etc/hosts` files -- but this should be OK
The PX deployment should not assume the K8s/OCP cluster is using the default DNS-domain `.svc.cluster.local`
FIX:
* the K8s deployment already fixes the `/etc/resolv.conf` file for all the PODs, such that the host-resolution _without_ the domain works OK
- i.e. both `host px-plugin-proxy.portworx.svc.cluster.local` and `host px-plugin-proxy.portworx` should resolve into IP without problems
Closes #  PWX-36817/PWX-32899   (op-24.1.0 branch) …
=> PWX-36817_PWX-32899_op-24.1.1: Fixing .svc.cluster.local DNS domain

drivers/storage/portworx/component/plugin.go
* note, fixing the remaining use of .svc.cluster.local DNS domain in the GUI plugin
* note: the tests are still creating mock host-entries with .svc.cluster.local DNS domain in the `/etc/hosts` files -- but this should be OK
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1574 into `master` branch
Closes #   PWX-36817/PWX-32899 for master -branch
Please refer to https://github.com/libopenstorage/operator/pull/1574 for tests info
=> PWX-36817_PWX-32899_r2_master: Fixing .svc.cluster.local DNS domain (#1574)

drivers/storage/portworx/portworx.go
**What this PR does / why we need it**: For components like prometheus, alert manager and grafana they do not update desiredImages in the stc when autoUpdateComponents is set to Once or Always. This change will ensure that the component images get updated
Closes # PWX-37760, PWX-37545
**Special notes for your reviewer**: Similar issue was found for dynamic Plugin images and the [fix](https://github.com/libopenstorage/operator/pull/1499) was similar to this PR
=> PWX-37760: Update component images when autoUpdateComponents is set

drivers/storage/portworx/portworx.go
**What this PR does / why we need it**: Cherry of PR [#1587 ](https://github.com/libopenstorage/operator/pull/1587) into release-24.1.1
=> [Cherry-pick]: Cherry-pick of  PR #1587

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/ccmGoRegisterDeployment.yaml
* operator to supply the `env APPLIANCE_ID = <PX_ClusterUUID>` to px-telemetry-registration deployment
The PR adds explicit `env APPLIANCE_ID = <PX_ClusterUUID>` to px-telemetry-registration deployment
* without this env-var, we are triggering some auto-discovery code in Telemetry-PODs --
1. which is "extra work" that is not necessary,
2. it does not always work correctly  (fails when recovering client SSL certs), and also
3. DX team wants to remove this auto-discovery code  (long term)
Closes # PWX-37852
Manual test --
```
apiVersion: v1
kind: Pod
spec:
containers:
- env:
- name: CONFIG
value: config/config_properties_px.yaml
- name: APPLIANCE_ID
value: …
```
=> PWX-37852: add APPLIANCE_ID env to px-telemetry-registration deployment

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/testspec/ccmGoRegisterDeployment.yaml
* operator to supply the `env APPLIANCE_ID = <PX_ClusterUUID>` to px-telemetry-registration deployment
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1588 into `release-24.1.1` branch
Closes #
=> PWX-37852_24.1.1: add APPLIANCE_ID env to px-telemetry-registration deployment (#1588)

README.md, drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/components_test.go, pkg/util/k8s/k8s.go, pkg/util/test/util.go
* adding code to validate (and refresh) Pure1 Telemetry's SSL certificate
ISSUE:
* customer did not properly recycle the px-cluster, so the SSL certificate in Telemetry's secret was pointing to a STALE ClusterUUID
FIX:
* as a fix, operator is now explicitly checking the Telemetry's SSL certificate
* if certificate is invalid, it'll remove the Telemetry's secret, and restart the telemetry-registration POD
Closes # PWX-36928
Adding dedicated Unit-test
Also, manually changed Telemetry's secret with a dummy SSL certificate -- and the PODs are restarting:
```
NAME                                             READY   STATUS        RESTARTS   AGE     IP            NODE …
```
=> PWX-36928: telemetry SSL-cert validation

drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/components_test.go, pkg/util/k8s/k8s.go
* adding code to validate (and refresh) Pure1 Telemetry's SSL certificate
drivers/storage/portworx/component/telemetry.go
pkg/util/test/util.go
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1553 into `release-24.1.1` branch
Closes #  PWX-36928  (for 24.1.1)
=> PWX-36928_24.1.1: telmetry SSL-cert validation (#1553)

drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/components_test.go
There's a global `maxExpirationSeconds` which can be smaller than the token expiration time we set. If this is the case, k8s will silently set the returned token expiration time to the `maxExpirationSeconds`, which will expire earlier than we expected, brining px not having a valid token to talk to k8s.
=> PWX-37982 Use the expiration time returned by k8s api server for px sa token

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/component/prometheus.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/autopilot-auth-token-secret_4_16.yaml, drivers/storage/portworx/testspec/autopilotDeployment_Openshift_4_14.yaml, drivers/storage/portworx/testspec/autopilotPrometheusClusterRoleBinding.yaml, drivers/storage/portworx/util/util.go, go.mod, go.sum, pkg/mock/mockcore/core.ops.mock.go, pkg/util/k8s/k8s.go, vendor/github.com/portworx/sched-ops/k8s/core/serviceaccounts.go, vendor/modules.txt
On OCP 4.16, the thanos-ruler-token secret, which was used to fetch ca.crt and token for prometheus endpoint authentication is removed and the authentication is current user's authentication token is used for the same.
From operator 24.1.1 and OCP 4.16, operator will not use Openshift's secret, rather do following to authenticater Openshift prometheus endopoint.
1. Create **autopilot-prometheus** service account
2.  Create **autopilot-promethues-binding** cluster role binding to created service account with **cluster-monitoring-view** cluster role.
3.  In **autopilot-prometheus-auth** secret, which is already created today, add following to use the secret's ca.crt and token with above permissions.
```
metadata:  
annotations: …
```
=> PWX-37681 : Use service account for prometheus endpoint authentication for OCP 4.16

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/autopilot-auth-token-secret_4_16.yaml
Issue :
Issue with the code was that ca.crt would not get updated during upgrade case of OCP cluster, since secret was already available. The change in the code updates ca.crt everytime token is refreshed. This handles case when pod certidicate is also updated on runtime. The new code flow is like following during every reconcilation loop : 
1. Fetch the secret
2. check if secret requires update, if secret is not present, present but expiry is not set or expiry is set but token is expired, we will create/update the secret.
3. If step 2 says update is required, certificare is fetched from path /var/run/secrets/kubernetes.io/serviceaccount/ca.crt within the pod, and updated in the secret.
This handles fresh install and upgrade case as well.
**Which …
=> PWX-38004 : Update ca.crt in autopilot secret when upgrading from OCP from 4.15 to 4.16

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go
cherry pick PR for https://github.com/libopenstorage/operator/pull/1590
Closes #https://purestorage.atlassian.net/browse/PWX-36251
=> [cherry-pick] PWX-36251 | Delete renamed px-attachdriveset-lock configmap on deletion of storage cluster 

drivers/storage/portworx/component/portworx_basic.go
The target audience of the token is the k8s api server as we are using the token to talk to api server.
With a wrong audience px is not able to start with 
`level=error msg="Could not init boot manager" file="terminate.go:85" component=porx/pkg/util/logs error="Failed to initialize k8s bootstrap: failed to create configmap px-bootstrap-teststc: Unauthorized"` 
and the token validation would return
```
status:
error: '[invalid bearer token, token audiences ["px"] is invalid for the target
audiences ["https://kubernetes.default.svc.cluster.local"]]'
user: {}
```
=> Fix PX ServiceAccount token audience

drivers/storage/portworx/component/telemetry.go
* the telemetry needs to force-delete the invalid pure-telemetry-certs secret  (no owner's check)
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1603 into `release-24.1.1`
Closes #  PWX-38007 (24.1.1)
=> PWX-38007 (24.1.1): Telemetry cert-secret refresh fix (#1603)

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/autopilotDeployment_Openshift_4_16.yaml
This PR is required in addition to autopilot changes done here https://github.com/pure-px/autopilot/pull/262
Since autopilot will read ca.crt from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt within the autopilot pod instead of /etc/ssl/px-custom/ that operator mounts, operator no longer is required to mount the certificate to authenticate prometheus URL.
Closes # https://purestorage.atlassian.net/browse/PWX-38035
- This is specifically for OCP 4.16
- For OCP 4.15 and below, there will be no change
-  E2E testing with Autopilot + operator on OCP 4.16 and OCP 4.15
=> PWX-38035 : Remove ca.crt mount volume from autopilot pod

drivers/storage/portworx/preflight.go, drivers/storage/portworx/preflight_test.go
When FACD pod name is not specified, for example, FACD with dmthin without multitenancy, the auto-added metadata device spec should not have extra comma at the end.
https://purestorage.atlassian.net/browse/PWX-38083
=> PWX-38083 Fix metadata device spec format when FACD pod name doesn't exist

deploy/crds/core_v1_storagecluster_crd.yaml, pkg/apis/core/v1/storagecluster.go
This PR will add a new field to control the PX upgrade behavior. The default behavior would be to have a non-disruptive upgrade. But users should be able to disable that and go back to the old behavior of upgrading nodes in parallel without worrying about the disruption. 
Closes # https://purestorage.atlassian.net/browse/PWX-36509
=> [cherry-pick] PWX-36509 : StorageCluster schema changes to support parallel portworx upgrades

pkg/util/test/util.go, test/integration_test/bluegreen_test.go, test/integration_test/node_pdb_test.go, test/integration_test/pdb_test.go, test/integration_test/utils/k8s.go, test/integration_test/utils/px_operator.go, test/integration_test/utils/storagecluster.go, test/integration_test/utils/utils.go
**What this PR does / why we need it**: This PR adds integration tests to validate Node PDBs as a part of Smart and Parallel Upgrades in 24.2.0
Closes # PWX-36514, PWX-37561
**Special notes for your reviewer**: The tests covered by this PR are mentioned in this [testrail](https://portworx.testrail.net/index.php?/suites/view/1&group_by=cases:section_id&group_id=31616&group_order=asc&display_deleted_cases=0) link 
[This](https://jenkins.pwx.dev.purestorage.com/job/Users/job/svijaykumar/job/dev-nodePDB-test/6/) is the link for jenkins job of the test
=> PWX-36514: Integration test to validate node pdb

pkg/util/test/util.go, test/integration_test/basic_test.go
Move token verification, that the token inside px runc container is the same as in the created secret, to storage cluster verification.
Verify that the token is refreshed stays in the integration test.
=> PWX-37884 Refactor px serviceaccount token integration test

test/integration_test/basic_test.go
Skip PX ServiceAccount token refresh integration test if operator version prior to 24.2.0
=> Skip px sa token refresh integration test if version prior to 24.2

drivers/storage/portworx/component/disruption_budget.go, drivers/storage/portworx/portworx.go, drivers/storage/portworx/portworx_test.go, drivers/storage/portworx/util/util.go, drivers/storage/storage.go, pkg/apis/core/v1/storagecluster.go, pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/storagecluster.go, pkg/controller/storagecluster/update.go, pkg/mock/storagedriver.mock.go
**What this PR does / why we need it**: This PR uses the `FilterNonOverlappingNodes` API for portworx versions greater than or equal px versions 3.1.2 to perform portworx upgrades without disrupting the volume quorum. Currently we randomly choose `maxUnavailable` nodes and upgrade them together. With this change we will first filter nodes such that volumes are not disrupted and pick `maxUnavailable` from that list to upgrade together.  
Note that by default this feature is enabled but will be useful only when maxUnavailable value is set in the rolling update strategy. To disable the feature, user will have to add the flag - 
`rollingUpdate:
disruption:
allow: true`
Closes # PWX-36510
=> PWX-36510: No disruption of volumes for portworx upgrades

drivers/storage/portworx/testspec/prometheusRule.yaml
Docs PR: https://github.com/pure-px/portworx-documentation/pull/977
Closes #
=> PWX-38379 [test-fix] change pool and volume resize alerts from warning to info

drivers/storage/portworx/component/plugin.go, drivers/storage/portworx/component/telemetry.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/ccmGoRegisterDeployment.yaml, pkg/util/k8s/k8s.go
Cherry-picks of "missed commits" 24.1.1 -> 24.2.0 :
* PWX-38007: Telemetry cert-secret refresh fix (#1603) (#1604) - Zoran Rajic, 4 weeks ago
* PWX-36928_24.1.1: telmetry SSL-cert validation (#1553) (#1594) - Zoran Rajic, 6 weeks ago
* PWX-37852_24.1.1: add APPLIANCE_ID env to px-telemetry-registration deployment (#1588) (#1591) - Zoran Rajic, 6 weeks ago
* PWX-36817_PWX-32899_op-24.1.1: Fixing .svc.cluster.local DNS domain (#1574) - Zoran Rajic, 7 weeks ago
Closes #
=> Zoran's cherry picks  (#1553) (#1574) (#1588) (#1591) (#1594) (#1603) (#1604)

drivers/storage/portworx/component/autopilot.go, drivers/storage/portworx/component/portworx_basic.go, drivers/storage/portworx/components_test.go, drivers/storage/portworx/testspec/autopilot-auth-token-secret_4_16.yaml, drivers/storage/portworx/testspec/autopilotDeployment_Openshift_4_14.yaml, drivers/storage/portworx/testspec/autopilotDeployment_Openshift_4_16.yaml, drivers/storage/portworx/testspec/autopilotPrometheusClusterRoleBinding.yaml, drivers/storage/portworx/util/util.go, drivers/storage/portworx/util/util_test.go, pkg/mock/mockcore/core.ops.mock.go
Cherrypicking following tickets into 24.2.0
- @nikita-bhatia
[PWX-37681](https://github.com/libopenstorage/operator/pull/1628/commits/e8abbd5d754e29dc5abca7eaa1df5efb50318eff)
- @nikita-bhatia
[PWX-38004](https://github.com/libopenstorage/operator/pull/1628/commits/1cc450d821991512e52d70064cb988c9f2ffebf4)
- @nikita-bhatia
PWX-38035 
- @nikita-bhatia
[[cherrypick] [24.1.1] PWX-38202](https://github.com/libopenstorage/operator/pull/1628/commits/d80609c77956a0b3f39b63913f861c5022509eb8)
=> Cherrypick commits from release 24.1.1 into 24.2.0 release branch

pkg/controller/storagecluster/controller_test.go, pkg/controller/storagecluster/update.go
for the same k8s node. If one healthy node is found then there is a PX node which is healthy on that k8s node. The unhealthy ones are present because they were previously running on that k8s node before. Such nodes will either find a new k8s node or will get auto-decommissioned in case of a storageless nodes.
Closes # https://purestorage.atlassian.net/browse/PWX-38103
- UTs added
- Manually tested with a local mode vsphere setup where storageless nodes become new storageless nodes on restart.
=> PWX-38103 Ignore unhealthy nodes if a healthy one is found

pkg/util/test/util.go
host-pid is required to run nsenter with runc. nsenter without runc is fine is the reason why other verifications are fine.
Closes PWX-38512
A full set of integration test is being run at https://jenkins.pwx.dev.purestorage.com/job/Operator/view/Operator%20Release%20Dashboard/job/op-basic-hotfix/
=> PWX-38512 Skip token refresh verification if host-pid not enabled

pkg/util/test/util.go
Cherry-pick fix for token refresh integration test
The corresponding change in master branch: https://github.com/libopenstorage/operator/commit/09fcd70d5bcce3ab8903709dab4fb6d994efd07e
=> PWX-38512 Cherry-pick skip token refresh verification if host-pid not enabled

pkg/apis/core/v1/storagecluster.go, pkg/controller/storagecluster/update.go
**What this PR does / why we need it**: Operator pod crashes with nil pointer dereference error while upgrading PX from 3.1.1 to 3.1.2 
because, cluster.Spec.UpdateStrategy.RollingUpdate.Disruption.Allow, becuase when Allow is *bool and the value was not set, it was nil and trying to dereference a nil pointer resulted in a nil pointer dereference error.
As a fix, changed  Allow  bool instead of *bool, since the value can be either true/false.
Closes # https://purestorage.atlassian.net/browse/PWX-38583
Verified on vanilla k8s
=> PWX-38583 : fix nil pointer derefernce in operator pod

drivers/storage/portworx/component/prometheus.go, drivers/storage/portworx/testspec/prometheusOperatorClusterRole.yaml
The AlertManager object creation started failing as soon as PrometheusOperator version is upgraded to 0.75.0.
Turns out Prometheus-operator team has updated the RBAC permissions required by the operator to manage CRDs. Because of this, the operator starts requiring permission "update" on resource "alertmanagers/status" and if users don't update the prometheus-operator SA RBAC, the controller starts but it wouldn't work fully.
https://github.com/prometheus-operator/prometheus-operator/pull/6351
Error in px-prometheus-operator pod 
`"missing permission on resource \"alertmanagers\" (group: \"monitoring.coreos.com/v1\")" reason="missing \"update\" permission on resource \"alertmanagers/status\" (group: \"monitoring.coreos.com\") for namespace …
=> PWX-38545 :  Failed to create AlertManager object with prometheus-operator v0.75.0
