drivers/storage/portworx/deployment.go
drivers/storage/portworx/testspec/openshift_runc.yaml
drivers/storage/portworx/testspec/pks.yaml
drivers/storage/portworx/testspec/runc.yaml

Add extra mounts for crio support in portworx driver

---

deploy/crds/core_v1alpha1_storagecluster_cr.yaml
drivers/storage/portworx/deployment.go
drivers/storage/portworx/testspec/openshift_runc.yaml
drivers/storage/portworx/testspec/runc.yaml

- Added all spec configs to CR example

Adding generic pre exec command for rhel coreos 

---

deploy/olm-catalog/portworx/1.0.0/portworxoperator.v1.0.0.clusterserviceversion.yaml
deploy/operator.yaml

Changing the default operator image version to 1.0.2

---

drivers/storage/portworx/deployment.go

Deploy pvc controller for openshift

---

Makefile
deploy/olm-catalog/portworx/1.0.3/core_v1alpha1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.0.3/portworxoperator.package.yaml
deploy/olm-catalog/portworx/1.0.3/portworxoperator.v1.0.3.clusterserviceversion.yaml

Also changed capabilities to "full lifecyle"

Adding portworx operator version 1.0.3 for catalog

---

deploy/crds/core_v1alpha1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.0.3/core_v1alpha1_storagecluster_crd.yaml

Correct validation for integer fields and add more validations

---

.travis.yml
Makefile
README.md

Adding code coverage

---

.travis.yml

Push image from travis when changes merge in a branch

---

drivers/storage/portworx/components.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go
pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/stork_test.go
pkg/util/k8s/k8s.go
pkg/util/k8s/k8s_test.go

Add default images for portworx, stork and lighthouse

---

build/Dockerfile

Update rhel-atomic base image for security fixes

---

deploy/olm-catalog/portworx/portworxoperator.v1.1.0.clusterserviceversion.yaml
manifests/portworx-releases.yaml

- Add more content to the description 
- Change docs URL
- Add UI descriptors for certain for better display in Openshift form view
- Disallow installing operator in all namespaces to avoid confusion. Now install the operator only in single namespace.
- Update the release manifest with new versions.

Change description for the operator

---

deploy/olm-catalog/portworx/portworxoperator.package.yaml
deploy/olm-catalog/portworx/portworxoperator.v1.2.0.clusterserviceversion.yaml

Adding portworx CSV for version 1.2.0

---

drivers/storage/portworx/components_test.go
drivers/storage/portworx/csi.go
drivers/storage/portworx/testspec/csiDeploymentWithResizerAndOldDriver_1.0.yaml
drivers/storage/portworx/testspec/csiDeploymentWithResizer_1.0.yaml
drivers/storage/portworx/testspec/csiDeployment_1.0.yaml
drivers/storage/portworx/testspec/csiStatefulSet_0.3.yaml

Use new CSI sidecar containers for security fix

---

deploy/crds/core_v1alpha1_storagecluster_crd.yaml
drivers/storage/portworx/portworx_test.go
pkg/apis/core/v1alpha1/storagecluster.go
pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/update.go
pkg/controller/storagecluster/util.go

Add other node-level configurations like network, rt_opts and env vars

---

test/integration_test/common_test.go

Delete validation should ensure StorageCluster is gone

---

pkg/util/test/util.go
test/integration_test/basic_test.go
test/integration_test/common_test.go

add ValidateStorageCluster

---

drivers/storage/portworx/components.go
drivers/storage/portworx/deployment.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/testspec/openshift_runc.yaml
drivers/storage/portworx/testspec/portworxAPIService.yaml
drivers/storage/portworx/testspec/portworxPodCustomPort.yaml
drivers/storage/portworx/testspec/portworxService.yaml

Also fixing the shifted port range which was incorrect previously.

Change the default start port when running in openshift

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/portworxoperator.package.yaml
deploy/olm-catalog/portworx/portworxoperator.v1.1.1.clusterserviceversion.yaml

Adding CSV for portworx version 1.1.1

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/testspec/pks.yaml

This is similar to the fix we did in px installer - https://github.com/portworx/px-installer/pull/441

Fix volume mount for PKS

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/testspec/openshift_runc.yaml
drivers/storage/portworx/testspec/portworxPodCustomPort.yaml

Fix OCI monitor pod readiness port

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/testspec/openshift_runc.yaml
drivers/storage/portworx/testspec/portworxPodCustomPort.yaml

Fix OCI monitor pod readiness port (cherry-pick)

---

drivers/storage/portworx/components.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/pvcControllerDeployment.yaml
drivers/storage/portworx/testspec/pvcControllerDeploymentOpenshift.yaml
pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/stork_test.go
pkg/controller/storagecluster/testspec/storkSchedDeployment.yaml

- Also do the same for image pull policy

Apply imagePullSecret to all components

---

drivers/storage/portworx/component/csi.go
drivers/storage/portworx/component/lighthouse.go
drivers/storage/portworx/component/portworx_api.go
drivers/storage/portworx/component/prometheus.go
drivers/storage/portworx/component/pvccontroller.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/prometheusOperatorDeployment.yaml
drivers/storage/portworx/testspec/pvcControllerDeployment.yaml
drivers/storage/portworx/testspec/pvcControllerDeploymentOpenshift.yaml
pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/stork_test.go
pkg/controller/storagecluster/testspec/storkSchedDeployment.yaml

- Also do the same for image pull policy

Apply imagePullSecret to all components (cherry-pick)

---

drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/uninstall.go

Add image pull secret to node wiper as well

---

drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/uninstall.go

Add image pull secret to node wiper as well (cherry-pick)

---

deploy/olm-catalog/portworx/portworxoperator.v1.1.1.clusterserviceversion.yaml

Change operator image to release version 1.1.1

---

deploy/olm-catalog/portworx/portworxoperator.v1.1.1.clusterserviceversion.yaml

Copy the portworx 1.1.1 CSV from release branch (cherrypick)

---

deploy/operator.yaml

Remove deprecated initializers

---

Makefile

Change release version 1.3 in Makefile

---

deploy/olm-catalog/portworx/portworxoperator.v1.2.0.clusterserviceversion.yaml
deploy/operator.yaml

Updated the CSV to use release 1.2.0 image

---

cmd/operator.go

Remove glog flags as no dependent package uses glog

---

Gopkg.lock
pkg/util/test/util.go
vendor/github.com/portworx/sched-ops/k8s/apps/apps.go
vendor/github.com/portworx/sched-ops/k8s/apps/daemonsets.go
vendor/github.com/portworx/sched-ops/k8s/apps/deployments.go
vendor/github.com/portworx/sched-ops/k8s/apps/statefulsets.go

PTX-2254 Validate components: stork, lighthouse, autopilot and pvc controller

---

deploy/olm-catalog/portworx/portworxoperator.package.yaml
deploy/olm-catalog/portworx/portworxoperator.v1.2.0.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworxoperator.v1.3.0.clusterserviceversion.yaml

Merge the latest 1.2 CSV in master

---

drivers/storage/portworx/component/prometheus.go
drivers/storage/portworx/testspec/prometheusOperatorClusterRole.yaml
drivers/storage/portworx/testspec/prometheusOperatorDeployment.yaml

Check for prometheus instances only in cluster's namespace

---

.travis.yml

Update travis to push image with 1.2.1 tag

---

drivers/storage/portworx/component/prometheus.go
drivers/storage/portworx/testspec/prometheusOperatorClusterRole.yaml
drivers/storage/portworx/testspec/prometheusOperatorDeployment.yaml

Cherrypick: Check for prometheus instances only in cluster's namespace 

---

drivers/storage/portworx/component/csi.go
drivers/storage/portworx/component/pvccontroller.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment.go
drivers/storage/portworx/testspec/csiClusterRole_k8s_1.11.yaml
drivers/storage/portworx/testspec/csiClusterRole_k8s_1.13.yaml
drivers/storage/portworx/testspec/csiClusterRole_k8s_1.14.yaml
drivers/storage/portworx/testspec/csiDeploymentAlphaDisabledK8s_1_14.yaml
drivers/storage/portworx/testspec/csiDeploymentAlphaDisabledK8s_1_16.yaml
drivers/storage/portworx/testspec/csiDeploymentWithResizerAndOldDriver_1.0.yaml
drivers/storage/portworx/testspec/pvcControllerClusterRole.yaml
drivers/storage/portworx/util/csi_generator.go
drivers/storage/portworx/util/util.go

- Add extra permissions to pvc controller for k8s 1.17
- Disable CSI alpha features if an env PORTWORX_DISABLE_CSI_ALPHA is set

Add SCC for CSI pod

---

drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment.go
drivers/storage/portworx/testspec/csiDeploymentWithResizerAndOldDriver_1.0.yaml
drivers/storage/portworx/testspec/csiDeploymentWithResizer_1.0.yaml
drivers/storage/portworx/testspec/csiDeployment_1.0.yaml
drivers/storage/portworx/testspec/px_csi_0.3.yaml
drivers/storage/portworx/testspec/px_csi_1.0.yaml
drivers/storage/portworx/util/csi_generator.go
pkg/util/util.go

https://github.com/libopenstorage/operator/pull/119

Cherry picks from master #119

---

drivers/storage/portworx/component/portworx_basic.go
drivers/storage/portworx/testspec/portworxClusterRole.yaml

Add event:patch permission to px cluster role

---

drivers/storage/portworx/component/portworx_api.go
drivers/storage/portworx/component/portworx_proxy.go
drivers/storage/portworx/component/prometheus.go
drivers/storage/portworx/components_test.go
pkg/controller/storagecluster/stork_test.go

Redeploy portworx api, proxy and prometheus on custom registry change

---

drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/util/util.go

- Pass PX_SERVICE_NAME env to stork

Pass portworx service name to stork

---

drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/uninstall.go

Use cluster's image pull policy even for node wiper

---

pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/stork_test.go

Set scheduler timeout for stork APIs to 5 minutes

---

pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/stork_test.go

Cherrypick: Set scheduler timeout for stork APIs to 5 minutes

---

drivers/storage/portworx/component/autopilot.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/autopilotDeployment.yaml

Pass PX_NAMESPACE to autopilot

---

deploy/olm-catalog/portworx/portworxoperator.v1.3.0.clusterserviceversion.yaml
deploy/operator.yaml

Add more links to description

---

drivers/storage/portworx/testspec/prometheusRule.yaml

Update prometheus rule

---

pkg/util/test/util.go

PTX-2438 fix issue validating pods with more than 1 container

---

drivers/storage/portworx/component/prometheus.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/prometheusInstance.yaml
drivers/storage/portworx/testspec/prometheusInstanceWithRemoteWriteEndpoint.yaml
drivers/storage/portworx/testspec/prometheusOperatorDeployment.yaml

Custom registry and image pull secret for prometheus instance

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go

Remove auto recovery timeout env for portworx 2.6

---

pkg/util/test/util.go

PTX-2480 nil pointer while validating monitoring

---

deploy/olm-catalog/portworx/portworxoperator.v1.4.0.clusterserviceversion.yaml

Disable lighthouse by default in openshift

---

pkg/util/test/util.go

PTX-2510 fix portworx-pvc-controller image validation

---

pkg/util/test/util.go

PTX-2510 fix k8sVersion format

---

drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/status.go
drivers/storage/portworx/status_test.go
drivers/storage/portworx/util/util.go
pkg/util/util.go

Add auth support to cluster status requests

---

drivers/storage/portworx/status.go

Remove extra line for gofmt

---

pkg/util/test/util.go

PTX-2527 fix image validation when using custom or private registry

---

deploy/olm-catalog/portworx/1.3.2/core_v1alpha1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.3.2/core_v1alpha1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.3.2/portworxoperator.v1.3.2.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml

Adding CSV for portworx operator 1.3.2

---

drivers/storage/portworx/component/security.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/status_test.go
drivers/storage/portworx/util/util.go

Add auto generation and refresh of admin/user tokens

---

drivers/storage/portworx/component/security.go
drivers/storage/portworx/util/util.go

Do not decode value read from k8s secrets

---

drivers/storage/portworx/component/security.go

Remove token cache for PX Security token checks

---

drivers/storage/portworx/component/security.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/util/util.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/update.go

Add support for stork and apps secrets

---

pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/testspec/storkService.yaml

- Fix frequent update of Stork deployment when stork.hostNetwork is nil

Add webhook port to stork service

---

drivers/storage/portworx/component/prometheus.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/testspec/prometheusInstance.yaml
drivers/storage/portworx/testspec/prometheusInstanceWithRemoteWriteEndpoint.yaml
drivers/storage/portworx/testspec/prometheusOperatorDeployment.yaml
pkg/apis/core/v1alpha1/storagecluster.go

Use prometheus images from version manifest

---

Makefile
drivers/storage/portworx/component/security.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/util/util.go
pkg/util/test/util.go

Refresh security tokens on issuer and shared-secret updates

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/testspec/px_k3s.yaml
drivers/storage/portworx/testspec/px_master.yaml
drivers/storage/portworx/util/util.go
pkg/util/k8s/k8s.go

- add extra mount for k3s
- enable csi

Detect k3s cluster and install portworx accordingly

---

Makefile

- Update mockgen make target to add storage driver

Lock operator-courier to fix the build

---

drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/testspec/csiDeploymentAlphaDisabledK8s_1_14.yaml
drivers/storage/portworx/testspec/csiDeploymentWithResizerAndOldDriver_1.0.yaml
drivers/storage/portworx/testspec/csiDeploymentWithResizer_1.0.yaml
drivers/storage/portworx/testspec/csiDeploymentWithResizer_1_17.yaml
drivers/storage/portworx/testspec/csiDeployment_1.0.yaml
drivers/storage/portworx/testspec/csiStatefulSet_0.3.yaml
drivers/storage/portworx/testspec/px_csi_0.3.yaml
drivers/storage/portworx/testspec/px_csi_1.0.yaml
drivers/storage/portworx/util/csi_generator.go

Use csi-plugins directory for pre 1.17 k8s

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/util/util.go

Add support for old stork issuer with newer versions of PX

---

drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/util/util.go

Make Stork JWT issuer depend on PX version

---

drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/storage.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/update.go
pkg/mock/controller.mock.go
pkg/mock/controllercache.mock.go
pkg/mock/controllermanager.mock.go
pkg/mock/storagedriver.mock.go

Also bounce on addition or update of misc args

Bounce portworx pods if switching between essentials and enterprise

---

licenses/LICENSE

Signed-off-by: Harsh Desai <harsh@portworx.com>

update copyright to 2020

---

drivers/storage/portworx/components_test.go
drivers/storage/portworx/portworx_test.go
pkg/util/util.go
pkg/util/util_test.go

Allow pulling images from registry directly without any repo/namespace

---

drivers/storage/portworx/component/csi.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/testspec/csiDeploymentWithPKS.yaml
drivers/storage/portworx/testspec/px_pks_with_csi.yaml
drivers/storage/portworx/util/csi_generator.go
drivers/storage/portworx/util/csi_generator_test.go
drivers/storage/portworx/util/util.go

Use correct kubelet path when deploying in PKS

---

drivers/storage/portworx/testspec/prometheusRule.yaml

Update prometheus rules

---

drivers/storage/portworx/component/prometheus.go
drivers/storage/portworx/testspec/prometheusOperatorClusterRole.yaml

Add anyuid SCC for prometheus operator

---

drivers/storage/portworx/component/pvccontroller.go
drivers/storage/portworx/components_test.go
pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/stork_test.go
pkg/util/k8s/k8s.go

Using new repository for k8s images

---

Makefile
deploy/olm-catalog/portworx/1.5.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.5.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.5.0/portworxoperator.v1.5.0.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml

Adding CSV for portworx 1.5.0 operator

---

drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go

Expose env var to configure manifest refresh interval for testing

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/util/util.go

Adding POD_IP env for IKS environment

---

drivers/storage/portworx/component/portworx_basic.go
drivers/storage/portworx/testspec/portworxClusterRole.yaml

Add secrets watch permission for AWS marketplace

---

drivers/storage/portworx/component/security.go
drivers/storage/portworx/components_test.go
pkg/util/k8s/k8s.go

Security: fix an issue where existing secrets were overwritten

---

pkg/util/test/util.go

Taking images from list incase StorageCluster doesn't have images defined

PTX-2725 Taking images from list incase StorageCluster doesn't have images defined

---

pkg/constants/metadata.go
pkg/controller/storagecluster/stork_test.go
pkg/util/k8s/k8s.go

Disable reconciliation of stork config using annotation on it

---

pkg/constants/constants.go

Change the delay before restarting cordoned node pods to 15m

---

pkg/constants/metadata.go
pkg/controller/storagenode/storagenode.go
pkg/controller/storagenode/storagenode_test.go

Allow autoscaler to remove k8s node without storage and kvdb

---

.travis.yml
Makefile
test/integration_test/Dockerfile
test/integration_test/basic_test.go
test/integration_test/common_test.go

Adding bits to Make and Travis to be able to build integration test container.

PTX-2846 Add build for integration test container

---

test/integration_test/operator-test-pod.yaml
test/integration_test/test-deploy.sh

1) Add operator test pod yaml
2) Add deploy script for operator test pod yaml

PTX-2848, PTX-2847 Add operator test pod deployment

---

test/integration_test/Dockerfile
test/integration_test/common_test.go
test/integration_test/node_affinity_test.go
test/integration_test/operator-test-pod.yaml
test/integration_test/test-deploy.sh

Adding first initial node affinity test

PTX-2845 Adding first initial node affinity test

---

pkg/util/test/util.go
test/integration_test/basic_test.go
test/integration_test/common_test.go
test/integration_test/node_affinity_test.go

1) Add validation utils
2) Add validation for Node Affinity rules
3) Add more verbose output for Node Affinity test

PTX-2840 Add node affinity validation and utils

---

pkg/util/test/util.go
test/integration_test/basic_test.go
test/integration_test/common_test.go
test/integration_test/node_affinity_test.go
test/integration_test/operator-test-pod.yaml
test/integration_test/test-deploy.sh

Implement ability to deploy/validate PX version based on Spec Generator URL which is passed from the command line.

PTX-2858 Implement ability to deploy/validate PX version based on Spec Generator URL

---

test/integration_test/common_test.go
test/integration_test/operator-test-pod.yaml
test/integration_test/test-deploy.sh

Adding ability to set log level for logrus from command line

Adding ability to set log level for logrus

---

Gopkg.lock
vendor/github.com/portworx/sched-ops/LICENSE
vendor/github.com/portworx/sched-ops/k8s/apiextensions/crds.go
vendor/github.com/portworx/sched-ops/k8s/apps/deployments.go
vendor/github.com/portworx/sched-ops/k8s/apps/replicasets.go
vendor/github.com/portworx/sched-ops/k8s/core/endpoints.go
vendor/github.com/portworx/sched-ops/k8s/core/pods.go
vendor/github.com/portworx/sched-ops/k8s/core/services.go
vendor/github.com/portworx/sched-ops/k8s/doc.go

Update sched-ops package

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/testspec/openshift_runc.yaml
drivers/storage/portworx/testspec/pks.yaml
drivers/storage/portworx/testspec/portworxPodCustomPort.yaml
drivers/storage/portworx/testspec/portworxPodEnvOverride.yaml
drivers/storage/portworx/testspec/px_csi_0.3.yaml
drivers/storage/portworx/testspec/px_csi_1.0.yaml
drivers/storage/portworx/testspec/px_k3s.yaml
drivers/storage/portworx/testspec/px_kvdb_certs.yaml
drivers/storage/portworx/testspec/px_kvdb_certs_without_ca.yaml
drivers/storage/portworx/testspec/px_kvdb_certs_without_key.yaml
drivers/storage/portworx/testspec/px_kvdb_without_certs.yaml
drivers/storage/portworx/testspec/px_master.yaml
drivers/storage/portworx/testspec/px_pks_with_csi.yaml
drivers/storage/portworx/testspec/runc.yaml

Add NODE_NAME to the portworx pod env variables

---

pkg/util/test/util.go
test/integration_test/basic_test.go
test/integration_test/common_test.go
test/integration_test/node_affinity_test.go
test/integration_test/operator-test-pod.yaml
test/integration_test/test-deploy.sh
test/integration_test/upgrade_test.go

Implementing upgrade/validate methods and adding upgrade test.
1) Implement method for STC upgrade/validate
2) Add first test
3) Make a fix to sched-ops and merged it into operator

PTX-2860 Implement method for STC upgrade/validate and add first test

---

drivers/storage/portworx/component/pvccontroller.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/util/util.go

Allow using custom ports for pvc controller deployment

---

build/Dockerfile

Update base rhel-atomic image to 7.9

---

drivers/storage/portworx/component/lighthouse.go
drivers/storage/portworx/component/pvccontroller.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/lighthouseClusterRole.yaml
drivers/storage/portworx/testspec/pvcControllerClusterRole.yaml

Signed-off-by: Serhii Aheienko <serhii.aheienko@gmail.com>

OPERATOR-287: Use the privileged psp for pvc controller and lighthouse components

---

drivers/storage/portworx/component/podsecuritypolicies.go
drivers/storage/portworx/portworx_test.go

Do not delete PSPs as we need them for node-wiper

---

drivers/storage/portworx/component/csi.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/util/csi_generator.go

[CSI] Add support for ephemeral CSI driver

---

deploy/olm-catalog/portworx/1.4.2/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.4.2/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.4.2/portworxoperator.v1.4.2.clusterserviceversion.yaml
deploy/olm-catalog/portworx/1.4.3/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.4.3/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.4.3/portworxoperator.v1.4.3.clusterserviceversion.yaml
deploy/olm-catalog/portworx/1.4.4/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.4.4/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.4.4/portworxoperator.v1.4.4.clusterserviceversion.yaml
deploy/olm-catalog/portworx/1.4.5/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.4.5/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.4.5/portworxoperator.v1.4.5.clusterserviceversion.yaml

Add missing CSVs for 1.4.* releases

---

.github/labeler.yml
.github/workflows/cron-stale.yml
.github/workflows/on-pr.yml
.github/workflows/on-review-requested.yml

Add actions for stale-in-review, stale, size, and area labels

---

.github/workflows/cron-stale.yml

Fix typo in cron-stale.yaml

---

.gitignore
drivers/storage/portworx/component/autopilot.go
drivers/storage/portworx/component/portworx_sc.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/testspec/storageClassDb.yaml
drivers/storage/portworx/testspec/storageClassDbCloudSnapshot.yaml
drivers/storage/portworx/testspec/storageClassDbCloudSnapshotEncrypted.yaml
drivers/storage/portworx/testspec/storageClassDbEncrypted.yaml
drivers/storage/portworx/testspec/storageClassDbLocalSnapshot.yaml
drivers/storage/portworx/testspec/storageClassDbLocalSnapshotEncrypted.yaml
drivers/storage/portworx/testspec/storageClassReplicated.yaml
drivers/storage/portworx/testspec/storageClassReplicatedEncrypted.yaml

[OPERATOR-272,273,277] 1.4.5 issues

---

pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/testspec/storkSchedClusterRole.yaml

cherry pick: https://github.com/libopenstorage/operator/pull/278
to resolve this issue: https://portworx.atlassian.net/browse/OPERATOR-312

cherry-pick: Add cluster role changes to stoek-scheduler for k8s1.21 (#278)

---

deploy/olm-catalog/portworx/1.4.5/portworxoperator.v1.4.5.clusterserviceversion.yaml
deploy/operator.yaml

Px rel 1.4.5

---

Makefile

Adding default build env-variables into Makefile.
Also building the static-check tools only if they are missing.
Closes #

Makefile optimization

---

drivers/storage/portworx/components_test.go
drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go

OPERATOR-303 Add default telemetry image

---

.travis.yml
deploy/olm-catalog/portworx/1.5.0/portworxoperator.v1.5.0.clusterserviceversion.yaml
deploy/operator.yaml

Update travis to push to 1.5.0 tag

---

drivers/storage/portworx/component/csi.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/testspec/openshift_runc.yaml
drivers/storage/portworx/testspec/pks.yaml
drivers/storage/portworx/testspec/portworxPodCustomPort.yaml
drivers/storage/portworx/testspec/portworxPodEnvOverride.yaml
drivers/storage/portworx/testspec/px_kvdb_certs.yaml
drivers/storage/portworx/testspec/px_kvdb_certs_without_ca.yaml
drivers/storage/portworx/testspec/px_kvdb_certs_without_key.yaml
drivers/storage/portworx/testspec/px_kvdb_without_certs.yaml
drivers/storage/portworx/testspec/px_master.yaml
drivers/storage/portworx/testspec/runc.yaml
drivers/storage/portworx/util/feature.go
drivers/storage/portworx/util/util.go

[CSI] Install by default when Portworx is enabled (#292)

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/testspec/ccmconfig.yaml

1.5.0 telemetry cherry picks

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/testspec/px_disable_telemetry.yaml
drivers/storage/portworx/util/util.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/update.go

OPERATOR-329 Update pod spec on telemetry spec changes

---

pkg/controller/storagecluster/controller_test.go

OPERATOR-329 reintroduce commented UTs

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/testspec/px_disable_telemetry.yaml
drivers/storage/portworx/util/util.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/update.go

[cherry-pick] OPERATOR-329 Update pod spec on telemetry spec changes

---

drivers/storage/portworx/manifest/manifest.go

Update default images to latest recommended versions

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/testspec/px_telemetry-with-location.yaml
drivers/storage/portworx/testspec/px_telemetry.yaml
pkg/controller/storagecluster/storagecluster.go

OPERATOR-339 provide node name dynamically to telemetry container

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/testspec/px_telemetry-with-location.yaml
drivers/storage/portworx/testspec/px_telemetry.yaml
pkg/controller/storagecluster/storagecluster.go

[cherry-pick] OPERATOR-339 provide node name dynamically to telemetry container (#304)

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/testspec/ccmconfig.yaml

PWX-20088 Add pattern for phone homing auto diags

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/testspec/ccmconfig.yaml

[cherry-pick] PWX-20088 Add pattern for phone homing auto diags (#312)

---

build/Dockerfile

Fix DTR scan issues:
https://portworx.atlassian.net/browse/OPERATOR-322
Closes #

OPERATOR-322 fix DTR vulnerability scan issues

---

cmd/operator.go

Continue using configmaps for leaderelection

---

drivers/storage/portworx/component/csi.go
drivers/storage/portworx/components_test.go
pkg/util/k8s/k8s.go
pkg/util/k8s/k8s_test.go

[CSI] Update CSIDriver to v1 for k8s 1.18+ (#321)

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/testspec/ccmconfig.yaml

PWX-20342 disable array_info.json file creation

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/testspec/ccmconfig.yaml

[cherry-pick] PWX-20342 disable array_info.json file creation (#324)

---

build/Dockerfile

https://portworx.atlassian.net/browse/OPERATOR-317
Closes #

PERATOR-317 fix redhat scan issue

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/testspec/px_telemetry-with-location.yaml
drivers/storage/portworx/testspec/px_telemetry.yaml

This contains memory usage fixes
Closes #

PWX-20507 Bump telemetry image to rc3

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/testspec/px_telemetry-with-location.yaml
drivers/storage/portworx/testspec/px_telemetry.yaml

* PWX-20507 Bump telemetry image to rc3
This contains memory usage fixes
* PWX-20507 slow down readiness and liveness probes
Closes #

[cherry-pick] PWX-20507 Bump telemetry image to rc3 (#328)

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/components_test.go

[cherry-pick] PWX-20490 default to external location for arcus (#334)

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/testspec/px_telemetry.yaml

PWX-20490 fix config map volume mount to reference arcus location

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/testspec/px_telemetry.yaml

* PWX-20490 fix config map volume mount to reference arcus location
* fix UT
Closes #

[cherry-pick] PWX-20490 fix config map volume mount to reference arcus location (#337)

---

drivers/storage/portworx/manifest/manifest.go

This fixes https://jira.purestorage.com/browse/CLOUD-61346
Closes #

CLOUD-61346 Bump CCM to rc4

---

deploy/crds/core_v1_storagecluster_crd.yaml

https://portworx.atlassian.net/browse/OPERATOR-193
Closes #
schema validation in node section was missing

add cache devices in StorageCluster nodes schema

---

drivers/storage/portworx/manifest/manifest.go

This fixes https://jira.purestorage.com/browse/CLOUD-61346
Closes #

[cherry-pick] CLOUD-61346 Bump CCM to rc4 (#341)

---

pkg/util/test/util.go

Update prometheus statefulset name for test validation func()

PTX-3606 Update prometheus statefulset name

---

deploy/olm-catalog/portworx/1.5.0/portworxoperator.v1.5.0.clusterserviceversion.yaml
deploy/olm-catalog/portworx/2.0.0/portworxoperator.v2.0.0.clusterserviceversion.yaml

Closes # https://portworx.atlassian.net/browse/OPERATOR-381

OPERATOR-381 Simplify openshift create form

---

drivers/storage/portworx/manifest/manifest.go

This fixes https://jira.purestorage.com/browse/CLOUD-61491
Closes #

CLOUD-61491 Bump CCM to rc5

---

drivers/storage/portworx/manifest/manifest.go

This fixes https://jira.purestorage.com/browse/CLOUD-61491
Closes #

[cherry-pick] CLOUD-61491 Bump CCM to rc5

---

pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go

OPERATOR-268 Mark the cluster as failed if validation fails

---

Makefile
drivers/storage/portworx/manifest/manifest.go

Change default px image to 2.6.5

---

deploy/crds/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.5.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.5.0/portworxoperator.v1.5.0.clusterserviceversion.yaml
deploy/olm-catalog/portworx/2.0.0/core_v1_storagecluster_crd.yaml

Copy updated CRDs to bundle folders

---

drivers/storage/portworx/manifest/manifest.go

This fixes https://jira.purestorage.com/browse/CLOUD-61776
Closes #

CLOUD-61776 bump CCM to rc6

---

drivers/storage/portworx/manifest/manifest.go

[cherry-pick] CLOUD-61776 bump CCM to rc6 

---

drivers/storage/portworx/manifest/manifest.go

uses: https://github.dev.purestorage.com/CloudConnect/CCM/commit/bf953efbddea89465acf9e1dfcd56c52a4a6c61b
Closes #

change CCM to use official image instead of rc

---

drivers/storage/portworx/manifest/manifest.go

uses: https://github.dev.purestorage.com/CloudConnect/CCM/commit/bf953efbddea89465acf9e1dfcd56c52a4a6c61b
Closes #

[cherry-pick] change CCM to use official image instead of rc (#359)

---

deploy/olm-catalog/portworx/1.5.0/portworxoperator.v1.5.0.clusterserviceversion.yaml
deploy/operator.yaml

Operator 1.5.0 release
Closes #

PX rel 1.5.0

---

drivers/storage/portworx/component/csi.go
drivers/storage/portworx/deployment.go
drivers/storage/portworx/testspec/csiDeploymentAlphaDisabledK8s_1_14.yaml
drivers/storage/portworx/testspec/csiDeploymentAlphaDisabledK8s_1_16.yaml
drivers/storage/portworx/testspec/csiDeploymentWithPKS.yaml
drivers/storage/portworx/testspec/csiDeploymentWithResizerAndOldDriver_1.0.yaml
drivers/storage/portworx/testspec/csiDeploymentWithResizer_1.0.yaml
drivers/storage/portworx/testspec/csiDeploymentWithResizer_1_17.yaml
drivers/storage/portworx/testspec/csiDeployment_1.0.yaml
drivers/storage/portworx/testspec/csiDeployment_1.0_k8s120.yaml
drivers/storage/portworx/testspec/csiStatefulSet_0.3.yaml
drivers/storage/portworx/testspec/px_csi_0.3.yaml
drivers/storage/portworx/testspec/px_csi_1.0.yaml
drivers/storage/portworx/testspec/px_k3s.yaml
drivers/storage/portworx/testspec/px_master.yaml
drivers/storage/portworx/testspec/px_pks_with_csi.yaml

Removes privileged access from CSI sidecars. 
Closes #

[CSI] Remove privileged access from CSI sidecars

---

deploy/olm-catalog/portworx/1.5.0/portworxoperator.v1.5.0.clusterserviceversion.yaml

Updating CSV to use 1.5.0 released image

---

deploy/olm-catalog/portworx/1.6.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.6.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.6.0/portworxoperator.v1.6.0.clusterserviceversion.yaml

This was only added to 1.6.0 branch. Adding it to master as well for consistency.
Closes #

Adding CSV for 1.6.0 

---

drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/uninstall.go

Closes # https://portworx.atlassian.net/browse/OPERATOR-406

OP-406 Remove pure cloud drive config map during cleanup

---

drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/testspec/openshift_runc.yaml
drivers/storage/portworx/testspec/pks.yaml
drivers/storage/portworx/testspec/portworxPodCustomPort.yaml
drivers/storage/portworx/testspec/portworxPodEnvOverride.yaml
drivers/storage/portworx/testspec/px_kvdb_certs.yaml
drivers/storage/portworx/testspec/px_kvdb_certs_without_ca.yaml
drivers/storage/portworx/testspec/px_kvdb_certs_without_cert.yaml
drivers/storage/portworx/testspec/px_kvdb_certs_without_key.yaml
drivers/storage/portworx/testspec/px_kvdb_without_certs.yaml
drivers/storage/portworx/testspec/runc.yaml
drivers/storage/portworx/util/feature.go

Closes # https://portworx.atlassian.net/browse/OPERATOR-441

OP-441 Keep CSI disabled for existing cluster, enable for new install

---

drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go

OP-445 Disable telemetry by default on installs

---

deploy/olm-catalog/portworx/1.5.1/portworxoperator.v1.5.1.clusterserviceversion.yaml

Update CSV to 1.5.1 released images

---

deploy/crds/core_v1_storagecluster_crd.yaml
drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
pkg/apis/core/v1/storagecluster.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/update.go

**What this PR does / why we need it**: cherry-pick to px-rel-1.6.0
Closes # OPERATOR-378

[OPERATOR-378] Allow adding portworx container resources requirements

---

pkg/apis/core/v1/zz_generated.deepcopy.go

Updated the deepcopy file for recent StorageCluster API changes 
```
make codegen
```
Closes #

OP-378 Update deepcopy for Storagecluster API changes

---

deploy/crds/core_v1_storagenode_crd.yaml
deploy/crds/deprecated/core_v1_storagenode_crd.yaml
drivers/storage/portworx/status.go
drivers/storage/portworx/status_test.go

https://portworx.atlassian.net/browse/OPERATOR-415
Closes #
After the change, we will only look at the status in NodeInitCondition and NodeStateCondition and not look at timestamp.

OPERATOR-415 fix storage node stuck initializing

---

drivers/storage/portworx/component/portworx_proxy.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/util/util.go

OPERATOR-450 Disable portworx proxy using explicit annotation

---

deploy/olm-catalog/portworx/1.5.2/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.5.2/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.5.2/portworxoperator.v1.5.2.clusterserviceversion.yaml

This is the operator bundle for 1.5.2 operator.
Closes #

Adding CSV for 1.5.2

---

pkg/controller/storagecluster/controller_test.go

**What this PR does / why we need it**: Fix flaky test `TestStoragePodGetsScheduled`
Closes # [OPERATOR-451](https://portworx.atlassian.net/browse/OPERATOR-451)

[OPERATOR-451] Fix unit test TestStoragePodGetsScheduled elements out of order issue

---

deploy/olm-catalog/portworx/portworx.package.yaml

Point olm package channels to 1.5.2

---

drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
pkg/controller/storagecluster/update.go

Closes # https://portworx.atlassian.net/browse/OPERATOR-443

OPERATOR-443 Not raising warning events on initial GRPC errors

---

deploy/olm-catalog/portworx/1.5.2/portworxoperator.v1.5.2.clusterserviceversion.yaml

Update CSV to 1.5.2 released images

---

deploy/crds/core_v1_storagecluster_crd.yaml
deploy/crds/core_v1_storagenode_crd.yaml
deploy/crds/deprecated/core_v1_storagecluster_crd.yaml
pkg/util/k8s/k8s.go

Closes # https://portworx.atlassian.net/browse/OPERATOR-455

OPERATOR-455 Persist desired resizer image in the cluster status

---

Makefile
drivers/storage/portworx/component/csi.go
drivers/storage/portworx/component/prometheus.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/testspec/prometheusClusterRole.yaml
drivers/storage/portworx/testspec/prometheusOperatorClusterRole.yaml
drivers/storage/portworx/testspec/prometheusOperatorDeployment_v0.50.0.yaml
drivers/storage/portworx/testspec/prometheusRule.yaml
pkg/util/k8s/k8s.go
pkg/util/k8s/k8s_test.go

**What this PR does / why we need it**: Upgrade Prometheus operator on k8s 1.22+
Closes # [OPERATOR-454](https://portworx.atlassian.net/browse/OPERATOR-454)

[OPERATOR-454] Upgrade prometheus operator to a newer version

---

pkg/util/test/util.go
test/integration_test/basic_test.go
test/integration_test/common_test.go
test/integration_test/fafb_config_test.go
test/integration_test/fafb_matrix_test.go
test/integration_test/types.go

Closes # OPERATOR-487
**Special notes for your reviewer**: will refactor fa fb test cases as well once everyone agrees on this approach.

[OPERATOR-487] Test framework refactor and upgrade test requirements

---

test/integration_test/basic_test.go
test/integration_test/common_test.go
test/integration_test/fafb_config_test.go
test/integration_test/fafb_matrix_test.go
test/integration_test/types.go

**What this PR does / why we need it**: Refactor fa fb tests
Closes #

[OPERATOR-496] Refactor FA FB tests to follow the new format

---

deploy/crds/core_v1_storagecluster_crd.yaml
pkg/util/util.go

add metrics collector images to stc schema and deep equal volumes change

---

deploy/olm-catalog/portworx/1.7.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.7.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.7.0/portworx-certified.clusterserviceversion.yaml

Adding CSV for 1.7.0

---

deploy/olm-catalog/portworx/1.6.1/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.6.1/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.6.1/portworx-certified.clusterserviceversion.yaml

Adding CSV for 1.6.1

---

deploy/olm-catalog/portworx/1.6.1/portworx-certified.clusterserviceversion.yaml

Update CSV to 1.6.1 released images

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/metricsCollectorDeployment.yaml
drivers/storage/portworx/util/util.go

add resource request/limit to metrics collector pod

---

deploy/olm-catalog/portworx/1.6.1/portworx-certified.clusterserviceversion.yaml

Make 1.6.0 upgradable to 1.6.1 in openshift < 4.9

---

pkg/util/test/util.go
test/integration_test/basic_test.go
test/integration_test/utils/storagecluster.go

Fix Update StorageCluster methods to avoid getting stale version of StorageCluster.
**NOTE:** Also added an improvement to CSI and Stork validation, because it is needed to avoid race conditions

PTX-4547 Fix Update StorageCluster methods

---

pkg/util/test/util.go
test/integration_test/basic_test.go

Pass MANIFEST_URL env var in case of edge-install and add check for empty expected PX version

PTX-4560 Fix Upgrade hops test

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/testspec/openshift_runc.yaml
drivers/storage/portworx/testspec/pks.yaml
drivers/storage/portworx/testspec/portworxPodCustomPort.yaml
drivers/storage/portworx/testspec/portworxPodEnvOverride.yaml
drivers/storage/portworx/testspec/px_csi_0.3.yaml
drivers/storage/portworx/testspec/px_csi_1.0.yaml
drivers/storage/portworx/testspec/px_disable_telemetry.yaml
drivers/storage/portworx/testspec/px_k3s.yaml
drivers/storage/portworx/testspec/px_kvdb_certs.yaml
drivers/storage/portworx/testspec/px_kvdb_certs_without_ca.yaml
drivers/storage/portworx/testspec/px_kvdb_certs_without_cert.yaml
drivers/storage/portworx/testspec/px_kvdb_certs_without_key.yaml
drivers/storage/portworx/testspec/px_kvdb_without_certs.yaml
drivers/storage/portworx/testspec/px_master.yaml
drivers/storage/portworx/testspec/px_pks_with_csi.yaml
drivers/storage/portworx/testspec/px_telemetry-with-location.yaml
drivers/storage/portworx/testspec/px_telemetry.yaml
drivers/storage/portworx/testspec/runc.yaml

Closes # https://portworx.atlassian.net/browse/OPERATOR-519

OPERATOR-519 Making /var/lib/osd as bidirectional mount

---

pkg/util/test/util.go

Removing Lighthouse from validation, since we discontinued it

PTX-4602 Removing Lighthouse from validation

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/testspec/ccmconfig.yaml
drivers/storage/portworx/testspec/px_telemetry_with_proxy.yaml
drivers/storage/portworx/util/util.go

[OPERATOR-438] Add portworx proxy support for telemetry ccm container

---

pkg/util/test/util.go

Fix TODO in ConstructVersionURL() method

PTX-4615 Fix TODO in ConstructVersionURL() method

---

drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go
test/integration_test/testspec/migration/daemonset-with-all-components.yaml

Signed-off-by: pault84 <paul@portworx.com>
Co-authored-by: pault84 <paul@portworx.com>
Cherry-pick from master.

OPERATOR-529: Bump ccm service image (#465)

---

test/integration_test/migration_test.go

[OPERATOR-532] Skip migration tests on k8s 1.22+

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/testspec/metricsCollectorConfigMap.yaml

add missing spaces back in the collector proxy config

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/metricsCollectorClusterRole.yaml
drivers/storage/portworx/testspec/metricsCollectorClusterRoleBinding.yaml

add clusterRole and clusterRoleBinding for metrics collector

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/metricsCollectorClusterRole.yaml
drivers/storage/portworx/testspec/metricsCollectorClusterRoleBinding.yaml

[cherry-pick] add clusterRole and clusterRoleBinding for metrics collector (#474)

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/testspec/metricsCollectorDeployment.yaml
test/integration_test/testspec/metricsCollectorDeployment.yaml

[cherry-pick] fix kubectl logs permission issue of metrics collector container (#476)

---

drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go

Change default image versions

---

pkg/util/test/util.go

This PR is needed to avoid failing validation on k3s

PTX-4639 Add k3s support

---

pkg/util/test/util.go

This fixed default affinity and tolerations that gets set

PTX-4815 Fix default node affinity and tolerations

---

pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go

[OPERATOR-425] storage node label validation

---

drivers/storage/portworx/manifest/common.go
drivers/storage/portworx/manifest/multiple.go
drivers/storage/portworx/manifest/remote.go
drivers/storage/portworx/manifest/remote_test.go

OPERATOR-517: fetch manifest from proxy

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/components_test.go

[cherry-pick] do not remove pure-telemetry-certs when telemetry is disabled (#492)

---

cmd/operator.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go

Closes # https://portworx.atlassian.net/browse/OPERATOR-559

OPERATOR-559 Migrate only if the annotation is set to true

---

deploy/crds/core_v1_storagecluster_crd.yaml
drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/util/util.go
pkg/apis/core/v1/storagecluster.go

[OPERATOR-420] get px repo image from version websvc

---

deploy/olm-catalog/portworx/1.7.0/portworx-certified.clusterserviceversion.yaml

Use 1.7.0 released images

---

deploy/olm-catalog/portworx/1.7.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.7.0/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/2.0.0/core_v1_storagecluster_crd.yaml

Update crds under olm catalog folder

---

drivers/storage/portworx/component/csi.go
drivers/storage/portworx/components_test.go

OPERATOR-544: add default FSGroupPolicy to File for k8s 1.20+

---

drivers/storage/portworx/util/csi_generator.go

[CSI] Fix comment on CSI volume health version

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/util/util.go

OPERATOR-499: add flag to set hostpid

---

deploy/olm-catalog/portworx/1.8.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.8.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.8.0/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/2.0.0/portworx-certified.clusterserviceversion.yaml

CSV for operator 1.8.0

---

Makefile

Update base registry to px-operator-registry:1.7.0

---

drivers/storage/portworx/portworx.go

Closes #
It does not have functionality impact thus unit tests passed.

do not check metrics collector image when checking telemetry changed

---

drivers/storage/portworx/components_test.go
drivers/storage/portworx/portworx.go

[cherry-pick] OPERATOR-563 missing metrics collector image when telemetry is enable

---

pkg/controller/storagecluster/controller_test.go

fix unit test failure

---

deploy/crds/core_v1_storagecluster_crd.yaml
drivers/storage/portworx/component/portworx_api.go
drivers/storage/portworx/components_test.go
pkg/apis/core/v1/storagecluster.go
pkg/apis/core/v1/zz_generated.deepcopy.go
pkg/util/k8s/k8s.go
pkg/util/test/util.go
pkg/util/util.go
pkg/util/util_test.go
test/integration_test/basic_test.go
test/integration_test/utils/px_operator.go

[OPERATOR-543] Allow adding custom labels to portworx-api service

---

drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/util/feature.go
drivers/storage/portworx/util/util.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/update.go
pkg/migration/generate.go
pkg/migration/migration_test.go
test/integration_test/basic_test.go

[CSI] Deprecate CSI feature flag in favor of spec.CSI.Enabled

---

drivers/storage/portworx/component/csi.go
drivers/storage/portworx/component/pvccontroller.go
drivers/storage/portworx/components_test.go
pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/stork_test.go
pkg/util/k8s/node.go
pkg/util/k8s/node_test.go
pkg/util/test/util.go
pkg/util/util.go
pkg/util/util_test.go
test/integration_test/basic_test.go
test/integration_test/utils/node.go

[OPERATOR-560] Add pod topology spread constraints to stork, pvc and csi pods

---

pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/stork_test.go

Stork scheduler deployment was missing the name: stork-scheduler label from the
selector as well the pod template. As selector is an immutable field, we need to
create the stork scheduler deployment to add that label.
Closes # https://portworx.atlassian.net/browse/OPERATOR-596

OPERATOR-596 Recreate stork scheduler deployment to update labels

---

pkg/util/test/util.go

Fix alertManager image selection for k8s versions 1.21 and lesser and greater than 1.22

PTX-5454 Fix alertManager image selection for k8s versions 1.21 and lesser and greater than 1.22

---

drivers/storage/portworx/component/disruption_budget.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/util/util.go
pkg/controller/storagecluster/storagecluster.go
pkg/util/k8s/pod.go

[OPERATOR-562] Fix pod disruption budget spec issue when using Metro DR

---

pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/update.go

[CSI] Fix case where op 1.7.0 to 1.8.0 bounced PX pods (#535)

---

build/Dockerfile

**What this PR does / why we need it**: Use specific tag instead of latest to prevent from using stale images
Closes #

[OPERATOR-593] Fix DTR vulnerability issues

---

drivers/storage/portworx/components_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go

[CSI] Add desired snapshot controller image when empty (#540)

---

drivers/storage/portworx/manifest/manifest.go

PWX-22998 bump px-node-wiper to 2.10.0

---

cmd/operator.go

enabled migration by default

---

pkg/migration/backup.go
pkg/migration/backup_test.go
pkg/migration/migration.go

collect customer daemonset objs into configmap

---

test/integration_test/testspec/migration/simple-daemonset.yaml

Fix migration functional test where portworx ns is not deleted

---

pkg/migration/backup.go

backup portworx namespace

---

pkg/migration/generate.go

set px version in status during migration

---

test/integration_test/migration_test.go

Remove CSI feature gate flag from migration test

---

test/integration_test/migration_test.go

**What this PR does / why we need it**: We should update hardcoded daemonset component images from spec gen url
Closes #

[OPERATOR-634] Fix operator migration test component image validation

---

build/Dockerfile

**What this PR does / why we need it**: To pass the upcoming new RedHat container certification process
Closes #

[OPERATOR-653] Add a non-root default container user

---

pkg/controller/storagecluster/storagecluster.go
pkg/migration/backup_test.go
pkg/migration/migration.go
pkg/migration/migration_test.go
pkg/util/util.go

raise event when migration is completed

---

deploy/olm-catalog/portworx/1.8.0/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/2.0.0/portworx-certified.clusterserviceversion.yaml

Change the replaces version to 1.7.1 in CSV

---

Makefile

Change base registry image to latest released version 1.7.1

---

build/Dockerfile

Update Dockerfile base image tag to pass RedHat certification scan

---

deploy/olm-catalog/portworx/1.8.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.8.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.8.0/portworx-certified.clusterserviceversion.yaml

Update 1.8.0 CSV file and CRDs

---

deploy/olm-catalog/portworx/1.8.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.8.0/portworx-certified.clusterserviceversion.yaml

[CP to master]Update 1.8.0 CSV file and CRDs

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/1.9.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.9.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.9.0/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml
deploy/operator.yaml
test/integration_test/utils/px_operator.go

[OPERATOR-693] Create Operator 1.9.0 release branch

---

Makefile

[OPERATOR-693] Disable bundle validation for now due to v1alpha1 CRD issue

---

drivers/storage/portworx/util/util.go

[OPERATOR-616] Fix IPv6 endpoint format passed to PX gRPC server

---

go.mod
go.sum
vendor/golang.org/x/sys/plan9/syscall.go
vendor/golang.org/x/sys/plan9/syscall_plan9.go
vendor/golang.org/x/sys/unix/syscall_aix.go
vendor/golang.org/x/sys/unix/syscall_dragonfly.go
vendor/golang.org/x/sys/unix/syscall_linux.go
vendor/golang.org/x/sys/unix/syscall_openbsd.go
vendor/golang.org/x/sys/windows/exec_windows.go
vendor/modules.txt

fix build failure: sync vendor

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
pkg/migration/generate.go
pkg/migration/migration_test.go

[OPERATOR-509] Populate extra storage driver volumes in StorageCluster during DaemonSet migration

---

test/integration_test/Dockerfile
test/integration_test/main_test.go
test/integration_test/operator-test-pod-template.yaml
test/integration_test/test-deploy.sh
test/integration_test/utils/constants.go
test/integration_test/utils/storagecluster.go

PTX-2886 Add support for EKS

---

pkg/util/test/util.go
test/integration_test/basic_test.go
test/integration_test/utils/storagecluster.go

Add PX Security validation and basic P0 regression tests

PTX-2759 Add PX Security validation and basic regression test

---

deploy/olm-catalog/portworx/1.9.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/2.0.0/core_v1_storagecluster_crd.yaml

Revert some olm-catalog CRD changes.

---

test/integration_test/basic_test.go
test/integration_test/utils/px_operator.go

[OPERATOR-691] Add OP version check to CSI topology test case

---

deploy/olm-catalog/portworx/1.8.1/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.8.1/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.8.1/portworx-certified.clusterserviceversion.yaml
test/integration_test/utils/px_operator.go

Add 1.8.1 olm catalog

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/1.8.1/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.8.1/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.8.1/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml
deploy/operator.yaml
go.sum
test/integration_test/Dockerfile
test/integration_test/utils/px_operator.go

Create Operator 1.8.1 release branch

---

pkg/constants/constants.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go
pkg/controller/storagecluster/stork_test.go
pkg/controller/storagenode/storagenode.go
pkg/controller/storagenode/storagenode_test.go
pkg/util/k8s/node.go
pkg/util/k8s/node_test.go

[OPERATOR-633] Add exponential backoff to pod restart when nodes are cordoned

---

deploy/olm-catalog/portworx/1.8.1/portworx-certified.clusterserviceversion.yaml

Fix build validate-bundle

---

Makefile
deploy/olm-catalog/portworx/1.8.1/portworx-certified.clusterserviceversion.yaml

Revert bundle validation fixes

---

pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/testspec/storkSchedClusterRole.yaml

Signed-off-by: Luke Pitstick <lpitstick@purestorage.com>
Closes #

PWX-23693 Add update pvc permission to stork (#613) (#616)

---

pkg/migration/generate.go
pkg/migration/migration_test.go

[OPERATOR-696] Handle service type annotation migration

---

pkg/migration/generate.go
pkg/migration/migration_test.go

[OPERATOR-511] Migrate portworx pod custom annotations

---

drivers/storage/portworx/component/csi.go
drivers/storage/portworx/testspec/csiDeployment_1.0_k8s123.yaml

[CSI] Remove LivenessProbe for health monitor container

---

drivers/storage/portworx/component/csi.go
drivers/storage/portworx/testspec/csiDeployment_1.0_k8s123.yaml

[CSI] Remove LivenessProbe for health monitor container (#632)

---

pkg/migration/generate.go
pkg/migration/migration_test.go

[OPERATOR-651] Set PreserveFullCustomImageRegistry during migration

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
pkg/migration/generate.go
pkg/migration/migration_test.go

[OPERATOR-508] Migrate external kvdb auth secret

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
pkg/migration/generate.go
pkg/migration/migration_test.go

Closes #
**Special notes for your reviewer**: Waiting for rebase

[CP][OPERATOR-511] Migrate portworx pod custom annotations

---

drivers/storage/portworx/component/lighthouse.go
drivers/storage/portworx/component/portworx_api.go
drivers/storage/portworx/component/portworx_basic.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment.go
drivers/storage/portworx/util/util.go
drivers/storage/portworx/util/util_test.go
pkg/migration/generate.go
pkg/migration/migration_test.go
pkg/util/k8s/k8s_test.go

[OPERATOR-725] Add granular control over service types

---

drivers/storage/portworx/component/csi.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/testspec/csiDeployment_1.0_k8s116.yaml
drivers/storage/portworx/testspec/csiDeployment_1.0_k8s120_with_topology.yaml
drivers/storage/portworx/testspec/csiDeployment_1.0_k8s120_without_snapcontroller.yaml
drivers/storage/portworx/testspec/csiDeployment_1.0_k8s123.yaml
test/integration_test/basic_test.go
test/integration_test/utils/storagecluster.go

[OPERATOR-719] Enable CSI snapshot controller by default

---

pkg/migration/migration.go
pkg/migration/migration_test.go

**What this PR does / why we need it**: If set stc update strategy to OnDelete for migration, user needs to mark node migration label value to Starting to trigger the portworx pod migration. UpdateStrategy could be updated between RollingUpdate and OnDelete during the migration
Closes # OPERATOR-627
**Special notes for your reviewer**: manually verified some happy path cases.

[OPERATOR-627] DaemonSet migration using OnDelete update strategy

---

pkg/migration/migration.go
pkg/migration/migration_test.go

[CP][OPERATOR-627] DaemonSet migration using OnDelete update strategy

---

pkg/constants/metadata.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go
pkg/util/k8s/k8s.go

OPERATOR-752: cleanup px created configmaps

---

drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go

[PWX-23190] Update envoy image to latest

---

drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go

[CP-1.9.0][PWX-23190] Update envoy image to latest

---

drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go

[CP-1.8.1][PWX-23190] Update envoy image to latest

---

drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go

[OPERATOR-784] Downgrade envoy image version to v1.21.4

---

drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go

[op-1.8.1][OPERATOR-784] Downgrade envoy image version to v1.21.4

---

pkg/migration/dryrun_test.go
pkg/migration/generate.go
pkg/migration/migration_test.go

[OPERATOR-741] Ignore volumes with mouth path conflicts when migrating extra volumes

---

deploy/olm-catalog/portworx/1.8.1/portworx-certified.clusterserviceversion.yaml

Signed-off-by: HaibinMichaelXie <hxie@purestorage.com>
Closes #

Updating CSV to use 1.8.1 released image

---

deploy/olm-catalog/portworx/1.8.1/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.8.1/portworx-certified.clusterserviceversion.yaml

Signed-off-by: HaibinMichaelXie <hxie@purestorage.com>
Closes #

portworx operator 1.8.1

---

pkg/util/test/util.go

Add validation for Porworx ConfigMap deletion on wipe

PTX-7674 Add validation for Porworx ConfigMap deletion on wipe

---

pkg/controller/storagenode/storagenode.go
pkg/controller/storagenode/storagenode_test.go

Fixing the customer escalation. When kvdb runs into outofpods status, operator will keep creating more pods, as the controller client API does not return the kvdb in outOfPods status, so operator does not know the pod exists. switch to sched-ops API and delete the outofpods pods first.
https://portworx.atlassian.net/browse/CEE-400

OPERATOR-785: stop creating more kvdb pods when hitting outOfPods status

---

drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go

Change prometheus images to be consistent with spec gen

---

drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/uninstall.go
pkg/util/k8s/k8s.go

OPERATOR-789 delete px-essential secret on wipe

---

drivers/storage/portworx/manifest/manifest.go

Update the default image versions

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/status.go
drivers/storage/portworx/uninstall.go
drivers/storage/portworx/util/util.go
pkg/migration/generate.go
pkg/migration/migration.go
pkg/migration/migration_test.go

[OPERATOR-816] Handle clusterID with special characters during migration

---

drivers/storage/portworx/testspec/prometheusRule.yaml

update prometheusRule for unit test

---

deploy/olm-catalog/portworx/1.8.1/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.8.1/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.8.1/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/1.9.0/portworx-certified.clusterserviceversion.yaml

Updating CSV to use 1.9.0 released image

---

test/integration_test/utils/k8s.go

validate crd registration before creating crds

---

pkg/util/test/util.go

Implement method to determine Operator and PX versions for future new CCM testing and upgrades

PTX-12071 Implement method to determine Operator and PX versions

---

deploy/ccm/phonehome-cluster.yaml
drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/component/telemetry_java.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/util/util.go
pkg/util/k8s/k8s.go
pkg/util/util.go

Use DaemonSet instead of Deployment to create log uploader pods, stc node affinity applied.
Closes #

[PWX-26180][PWX-26188] Use DaemonSet to deploy telemetry phonehome pods

---

pkg/util/test/util.go

**What this PR does / why we need it**: We are removing csi health monitor from manifest due to a bug
Closes #

Remove csi health monitor validation from automation

---

drivers/storage/portworx/component/pvccontroller.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/pvcControllerDeployment_k8s_1.24.yaml
pkg/util/k8s/k8s.go

PWX-26006 - fix pvccontroller crash on k8s 1.24+

---

pkg/util/test/util.go
test/integration_test/basic_test.go
test/integration_test/utils/px_operator.go

Validate new Telemetry method and regression test changes

PTX-12097 Validate new Telemetry method and regression test changes

---

pkg/util/test/util.go

Copying function that determines master node from sched-ops to operator instead of updating sched-ops package due to huge vendor changes

PTX-11431 Fix master labels to support v1.24

---

pkg/util/test/util.go

* Fix validation for images when docker.io gets automatically pre-fixed by operator
* Quick fix for 2 years old prometheus code, ran into this issue, logic seemed wrong

PTX-12254 Fix validation for images when docker.io gets automatically pre-fixed by operator

---

deploy/ccm/registration-service.yaml

[PWX-26405] Remove telemetry register container port from spec template

---

Makefile
deploy/olm-catalog/portworx/1.9.1/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.9.1/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.9.1/portworx-certified.clusterserviceversion.yaml

create 1.9.1 catalog

---

deploy/olm-catalog/portworx/2.0.0/portworx-certified.clusterserviceversion.yaml

fix 2.0.0 catalog to use previous released version 1.9.0

---

drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/util/util.go
pkg/controller/storagecluster/controller_test.go
pkg/util/k8s/k8s.go
pkg/util/test/util.go

[PWX-25529] Adjust placement rule node labels for k8s 1.24+ support

---

pkg/util/test/util.go
pkg/util/util.go

Fix common registry issue for older then 1.9.1 operators

PTX-12493 Fix common registry issue for older operators

---

pkg/migration/generate.go

do not take docker.io as custom registry

---

test/script/simulate-high-mem.sh
test/script/testapp.yaml

add script to simulate operator high memory usage

---

pkg/util/test/util.go
test/integration_test/basic_test.go
test/integration_test/utils/storagecluster.go

* Test automation for csi snapshot controller
* During test found container images are not validated correctly
Closes #
test passed https://jenkins.pwx.dev.purestorage.com/view/Newstack%20Dashboard/job/Operator/job/operator-integration-basic-dev/2/console

[PWX-25487] Add CSI snapshot controller validation

---

pkg/migration/generate.go
pkg/migration/migration_test.go
pkg/util/test/util.go
test/integration_test/migration_test.go

[PWX-25380] Disable telemetry during DaemonSet migration if PX is 2.12+

---

drivers/storage/portworx/testspec/nodeWiper.yaml
drivers/storage/portworx/testspec/nodeWiperPKS.yaml
drivers/storage/portworx/testspec/nodeWiperWithWipe.yaml
drivers/storage/portworx/uninstall.go

Reverts libopenstorage/operator#739

Revert "PWX-24077: Add '/var/cores' to volume mounts for wiper.  Used for log…"

---

pkg/migration/cleanup.go
pkg/migration/migration_test.go
pkg/util/test/util.go
test/integration_test/migration_test.go
test/integration_test/utils/constants.go

[PWX-26683] Fix bug during updating migration test spec images

---

pkg/util/test/util.go

* Add retry loop for validation of all components
* Separate component validation functions into Disabled and Enabled

PTX-12616 Add retry loop for validation of all components

---

pkg/util/test/util.go

PTX-12740 Fix portworx proxy validation

---

build/Dockerfile

Update operator base image to latest

---

drivers/storage/portworx/manifest/common.go
drivers/storage/portworx/manifest/configmap.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
pkg/util/util.go

PWX-26230: fix portworx operator does not honor the PX version in the px-versions configmap

---

pkg/util/test/util.go
test/integration_test/basic_test.go
test/integration_test/testspec/storagecluster/storagecluster-with-all-components.yaml
test/integration_test/utils/k8s.go

Upgrade StorageCluster test with all components enabled

PTX-12273 Upgrade StorageCluster test with all components enabled

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/1.10.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.10.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.10.0/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml
deploy/operator.yaml

[PWX-26843] Create operator 1.10.0 branch

---

pkg/util/test/util.go

Check pure-telemetry-certs for owner reference before deleting StorageCluster

PTX-12868 Check pure-telemetry-certs for owner reference before deleting StorageCluster

---

pkg/util/test/util.go

[PWX-26326] Add telemetry secret validation in automation

---

pkg/util/test/util.go

Use sched-ops IsNodeMaster() func instead

PTX-12919 Use sched-ops IsNodeMaster() func instead

---

build/Dockerfile

[PWX-26962] Update operator base image

---

build/Dockerfile

[1.10.0][PWX-26962] Update operator base image

---

deploy/ccm/phonehome-cluster.yaml
drivers/storage/portworx/testspec/ccmGoPhonehomeDaemonSet.yaml

[PWX-27016] Fix ccm-go phonehome issue on ocp cluster

---

cmd/operator/operator.go

avoid log when the --disable-cache-for arg is empty

---

pkg/util/test/util.go

Add pxctl check for Telemetry status

PTX-12988 Add pxctl check for Telemetry status

---

drivers/storage/portworx/component/disruption_budget.go
drivers/storage/portworx/component/podsecuritypolicies.go
drivers/storage/portworx/components_test.go
pkg/util/k8s/k8s.go
pkg/util/k8s/k8s_test.go

[PWX-25676][PWX-26636][PWX-26640] k8s 1.25 support part1

---

pkg/util/test/util.go

Check Telemetry pxctl status on all PX nodes

PTX-13037 Check Telemetry pxctl status on all PX nodes

---

deploy/ccm/envoy-config-collector-custom-proxy.yaml
deploy/ccm/envoy-config-collector.yaml
deploy/ccm/envoy-config-register-custom-proxy.yaml
deploy/ccm/envoy-config-register.yaml
deploy/ccm/envoy-config-rest-custom-proxy.yaml
deploy/ccm/envoy-config-rest.yaml
drivers/storage/portworx/testspec/ccmGoCollectorProxyConfigMap.yaml
drivers/storage/portworx/testspec/ccmGoCollectorProxyConfigMap_proxy.yaml
drivers/storage/portworx/testspec/ccmGoPhonehomeProxyConfigMap.yaml
drivers/storage/portworx/testspec/ccmGoPhonehomeProxyConfigMap_proxy.yaml
drivers/storage/portworx/testspec/ccmGoRegisterProxyConfigMap.yaml
drivers/storage/portworx/testspec/ccmGoRegisterProxyConfigMap_proxy.yaml

[PWX-27142] Update ccm envoy config for cert validation

---

pkg/util/test/util.go
test/integration_test/basic_test.go

Run pxctl command with Security token if PX Security is enabled

PTX-13087 Run pxctl command with Security token if PX Security is enabled

---

pkg/util/test/util.go
test/integration_test/basic_test.go

Adding PX Auth validation on PX nodes

PTX-13089 Adding PX Auth validation on PX nodes

---

pkg/migration/generate.go
pkg/migration/migration_test.go

[PWX-27219] Truncate clusterID during migration if longer than 63 chars

---

drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/ccmGoPhonehomeConfigMap.yaml
drivers/storage/portworx/testspec/ccmGoPhonehomeDaemonSetDefaultPort.yaml

[PWX-27292] Change default phonehome listening port from 9090 to 9024

---

pkg/util/test/util.go

[PWX-27401] Skip metrics collector v1 deployment validation

---

go.mod
go.sum
vendor/modules.txt

didn't find a way to fix this properly, but we need the fix for release process next week.
Closes #

Fix build failure caused by golint dependency update

---

test/integration_test/migration_test.go

Fix migration automation storage cluster update issue

---

build/Dockerfile

Update latest base image

---

drivers/storage/portworx/component/auth.go
drivers/storage/portworx/component/disruption_budget.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/status.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go
pkg/preflight/utils.go
pkg/util/util.go

[PWX-27621] Fix cluster status issue after running preflight

---

drivers/storage/portworx/component/prometheus.go
drivers/storage/portworx/testspec/prometheusOperatorClusterRole.yaml

PWX-27756: update clusterRole for prometheus

---

build/Dockerfile
drivers/storage/portworx/manifest/manifest.go

Update base image and telemetry images

---

drivers/storage/portworx/component/pvccontroller.go
drivers/storage/portworx/testspec/pvcControllerDeployment.yaml
drivers/storage/portworx/testspec/pvcControllerDeploymentOpenshift.yaml
drivers/storage/portworx/testspec/pvcControllerDeployment_k8s_1.24.yaml

add pod affinity, so pvc controller pod will run on nodes with storage pod.

PWX-26656 add affinity to run pvc controller on storage nodes

---

Makefile

Removed interactive mode from verify-bundle-dir target to be able to build on Jenkins
Closes https://portworx.atlassian.net/browse/PTX-13940

PTX-13940 Removed interactive mode from verify-bundle-dir target

---

deploy/crds/core_v1_storagecluster_crd.yaml
drivers/storage/portworx/component/autopilot.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/autopilotConfigMap.yaml
pkg/apis/core/v1/storagecluster.go

to add autopilot gitops configuration support
Closes #PWX-26920

PWX-26920: add autopilot gitops configuration support

---

drivers/storage/portworx/components_test.go

* will update /etc/hosts "in-place"
Original unit-tests were updating `/etc/hosts` file by using a different temporary file, and then renaming it as `/etc/hosts`
ISSUE:
* renaming `/etc/hosts` file does not work inside containers, since containers "lock" this file and will not allow renaming/moving it -- thus, the unit-tests would fail when ran in "containerized" environments
- they do, however, allow appending/overwriting the file
As a fix, we're updating `/etc/hosts` file "in place" by overwriting it with the test-content
Closes # PWX-25288

PWX-25288-pt2: Unit-tests fix

---

Jenkinsfile

Added Jenkinsfile to enable Jenkins automation for each PR
Closes https://portworx.atlassian.net/browse/PTX-13944
After this commit is merged all new PRs will run Jenkins tests and update PR with the results.
Also it will block to merge a PR if it was any failures.

PTX-13944 Added Jenkinsfile to enable PR automation

---

deploy/crds/core_v1_storagecluster_crd.yaml
drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go

[PWX-26914][PWX-27865][PWX-27923] add resources limit/requests to oci-mon and runc args

---

pkg/migration/migration.go

* get the updated stc before updating the migration condition
Closes #
* automation passed

[PWX-27765] Fix migration status update issue

---

deploy/ccm/ccm.properties
drivers/storage/portworx/testspec/ccmGoPhonehomeConfigMap.yaml

Signed-off-by: Jose Rivera <jose@portworx.com>
Add PX information and  log files to push to Pure1
Closes #

Update ccm.properties to include PX incremental upload content.

---

drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
pkg/util/k8s/k8s.go
test/integration_test/utils/storagecluster.go

PWX-26156: enable csi by default on k8s 1.26

---

Makefile
deploy/olm-catalog/portworx/1.10.2/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.10.2/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.10.2/portworx-certified.clusterserviceversion.yaml

PWX-28289 Add CSV for 1.10.2

---

drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/status.go
pkg/constants/migration.go
pkg/migration/backup.go
pkg/migration/migration.go
pkg/migration/migration_test.go

* During migration always get live stc when updating
* Mark migration as completed in controller reconcile loop
Closes #

[PWX-27765] Fix stc object and migration condition update issues during migration

---

pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go
pkg/controller/storagecluster/update.go

[PWX-28349] Update STC status to Degraded when installation fails

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/portworx.package.yaml
deploy/operator.yaml

PWX-28289 Setup 1.10.2 release branch

---

deploy/ccm/ccm.properties
drivers/storage/portworx/testspec/ccmGoPhonehomeConfigMap.yaml

* Update ccm.properties to include PX incremental upload content.
Signed-off-by: Jose Rivera <jose@portworx.com>
* Update testspec to include PX incremental upload content.
Signed-off-by: Jose Rivera <jose@portworx.com>
* Replace tabs with space for proper indenting.
Signed-off-by: Jose Rivera <jose@portworx.com>
Signed-off-by: Jose Rivera <jose@portworx.com>
PX incremental upload content.
Closes #

Update ccm.properties to include PX incremental upload content. (#871)

---

Makefile
deploy/olm-catalog/portworx/1.11.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.11.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.11.0/portworx-certified.clusterserviceversion.yaml

There are two commits, the first commit copies from 1.10.2, the second commit has the changes for 1.11.0.
I will use the second commit as an example for the release process doc.

Setup 1.11.0 CSV and makefile on master

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/portworx.package.yaml
deploy/operator.yaml

PWX-28383 setup 1.11.0 branch

---

deploy/ccm/metrics-collector-deployment.yaml
drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/component/telemetry_java.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/testspec/ccmGoCollectorConfigMap.yaml
drivers/storage/portworx/testspec/metricsCollectorConfigMap.yaml
pkg/util/test/util.go

* revert previous changes which disables metrics collector by default
* update default metrics collector image and config
Closes #

[PWX-27920] Enable metrics collector batching to reduce memory usage

---

pkg/util/test/util.go

[PWX-27920] Only validate metrics collector on operator 1.11+

---

build/Dockerfile

Update base image to 8.7-1049 for operator 1.10.2 release

---

deploy/crds/core_v1_storagecluster_crd.yaml
drivers/storage/portworx/component/autopilot.go
drivers/storage/portworx/components_test.go
pkg/apis/core/v1/storagecluster.go
pkg/controller/storagecluster/stork.go
pkg/controller/storagecluster/stork_test.go
pkg/util/util.go

PWX-26914: Add resources config for stork, stork-scheduler and autopilot

---

deploy/ccm/metrics-collector-deployment.yaml
deploy/ccm/registration-service.yaml
drivers/storage/portworx/testspec/ccmGoCollectorDeployment.yaml
drivers/storage/portworx/testspec/ccmGoRegisterDeployment.yaml

Run multiple envoys on the same system
Closes # PWX-28184

PWX-28184: Add 'base-id' param to envoy startup to allow multiple envoys to run.

---

test/integration_test/utils/marketplace.go

Fix marketplace operator deployment for -dev images

PTX-15118 Fix marketplace operator deployment for -dev images

---

pkg/util/test/util.go
test/integration_test/utils/storagecluster.go

Seen this timeout and fail job, adding retry with timeout for deleting StorageCluster

PTX-15076 Add retry for deleting StorageCluster

---

pkg/util/test/util.go

Improve stc status messages to see what is expected and what are we getting for future debug purposes

PTX-15241 Improve stc status messages

---

pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go

Fix missing node name from the storage pod template

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/1.10.3/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.10.3/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.10.3/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml
deploy/operator.yaml

Add CSV and update travis to use 1.10.3 version

---

deploy/olm-catalog/portworx/1.10.3/portworx-certified.clusterserviceversion.yaml

Updating CSV to use 1.10.3 released image (#909)

---

pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go
pkg/controller/storagecluster/stork_test.go
pkg/controller/storagecluster/testspec/storkSchedDeployment.yaml

[Cherry-pick] Update k8s min version for PDB (#913)

---

drivers/storage/portworx/component/autopilot.go
drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/component/telemetry_java.go
drivers/storage/portworx/components_test.go
pkg/controller/storagecluster/stork.go
pkg/migration/backup.go
pkg/migration/migration.go
pkg/util/k8s/k8s.go

[1.11.0] cherry-pick 1.11.0 payloads

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/1.10.4/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.10.4/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.10.4/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml
deploy/operator.yaml

Setup 1.10.4 release branch

---

pkg/util/test/util.go

Disable validation for metrics-collector for 1.10+

PTX-PTX-15530 Disable validation for metrics-collector for 1.10+

---

deploy/crds/core_v1_storagecluster_crd.yaml
pkg/apis/core/v1/storagecluster.go
pkg/apis/core/v1/zz_generated.deepcopy.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/update.go

During rolling update, wait for minReadySeconds after pod is ready before rolling update next pod

PWX-28608 add minReadySeconds for rolling updates

---

test/integration_test/utils/storagecluster.go

PTX-15552 Fixing cluster creation if cluster already exists

---

Makefile

fix incorrect BASE_REGISTRY_IMG

---

build/Dockerfile

[pwx-28605] Update base image version

---

test/integration_test/cloud_disk_test.go

Jira Ticket : https://portworx.atlassian.net/browse/PWX-28722

PWX-28722 : Add Operator integration test for OKE disk encrpyption

---

build/Dockerfile
drivers/storage/portworx/alert_manager_component_test.go
drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/storage.go
pkg/controller/storagecluster/storagecluster.go
pkg/mock/storagedriver.mock.go
test/integration_test/basic_test.go
test/integration_test/utils/storagecluster.go

[PWX-26954] Enable telemetry by default on PX 2.12+

---

deploy/ccm/metrics-collector-deployment.yaml
deploy/ccm/registration-service.yaml
drivers/storage/portworx/testspec/ccmGoCollectorDeployment.yaml
drivers/storage/portworx/testspec/ccmGoRegisterDeployment.yaml

[pwx-28343] Add "Recreate" update strategy to telemetry deployments

---

Makefile
drivers/storage/portworx/components_test.go

[pwx-29485] update container build tests

---

pkg/util/test/util.go

Change fmt.Printf() to logrus.Infof() in ValidateTelemetry() for PX version

PTX-16142 Change fmt.Printf() to logrus.Infof() in ValidateTelemetry() for PX version

---

deploy/olm-catalog/portworx/1.10.5/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.10.5/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.10.5/portworx-certified.clusterserviceversion.yaml

Makefile is already 1.10.4 so no need to change

Catalog for 1.10.5 release

---

deploy/crds/core_v1_storagecluster_crd.yaml
drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go

This reverts commit 1a4a1f97b248a63ad2b34f960794d313b3dda7c2.
Closes #

Revert "add resources limit/requests to px pods (#865)"

---

deploy/olm-catalog/portworx/1.10.5/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/1.10.5/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/1.10.5/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/23.3.0/portworx-certified.clusterserviceversion.yaml

change previous version to 1.10.5 and copy 1.10.5 catalog

---

Makefile

change base registry image to 1.10.5

---

drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go

[pwx-29114] Update default release manifest images

---

deploy/ccm/envoy-config-rest-custom-proxy.yaml
drivers/storage/portworx/testspec/ccmGoPhonehomeProxyConfigMap_proxy.yaml

[pwx-29757] Update phonehome envoy proxy config

---

drivers/storage/portworx/component/securitycontextconstraints.go

Before this change, SCC will be updated on every reconciliation due to deepEqual evaluation to false on empty field/pointers.
After the change, SCC will only be updated once on updating operator. 
Ticket: https://portworx.atlassian.net/browse/PWX-29531
Previous PR: https://github.com/libopenstorage/operator/pull/967
**Test**:
Previous portworx scc: users field doesn't contain px-prometheus service account
After pulling the operator change, 
Confirmed 1. scc is updated only 1 time. 2.portworx scc contains px-prometheus service account. 3. px-prometheus pod up and running

Fix SCC update

---

drivers/storage/portworx/component/securitycontextconstraints.go

[cherry-pick] Fix SCC update (#977)

---

Makefile
deploy/olm-catalog/portworx/23.4.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.4.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.4.0/portworx-certified.clusterserviceversion.yaml

[pwx-29961] Setup 23.4.0 release branch

---

Makefile
deploy/olm-catalog/portworx/portworx.package.yaml

[pwx-29961] Fix 23.4.0 build

---

Makefile
deploy/olm-catalog/portworx/23.3.1/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.3.1/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.3.1/portworx-certified.clusterserviceversion.yaml

[23.4.0]Add 23.3.1 catalog

---

Makefile
deploy/olm-catalog/portworx/23.4.0/portworx-certified.clusterserviceversion.yaml

[master] Update for 23.3.1 release

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/23.5.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.5.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.5.0/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml

Sets up `23.5.0` branch.
Closes #
note: new PR recreated from https://github.com/libopenstorage/operator/pull/1022

Setting up `23.5.0` branch

---

Makefile
deploy/olm-catalog/portworx/23.5.0/portworx-certified.clusterserviceversion.yaml

- We need to change the base registry to a released version and create the new test catalog on top of that released catalog.
- Update the `replaces` to use a released version.
Closes #

Use 23.4.0 as the previous version

---

Makefile
deploy/olm-catalog/portworx/23.5.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.5.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.5.0/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/99.9.9/portworx-certified.clusterserviceversion.yaml

Add missing CSV changes to master

---

pkg/util/test/util.go

Skip reference validation for tel secret for operators below 1.10

PTX-17968 Skip reference validation for tel secret for operators below 1.10

---

drivers/storage/portworx/portworx.go

Operator was excessively logging the following events:
```
$ kubectl describe stc
...
Events:
Type     Reason            Age                   From                       Message
----     ------            ----                  ----                       -------
Normal   SuccessfulCreate  5m23s                 storagecluster-controller  Created pod: koka123-mhkbj
Warning  FailedComponent   18s (x23 over 5m30s)  storagecluster-controller  Failed to cleanup PodSecurityPolicies. no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
```
* note the component `PodSecurityPolicy` was never deployed since this was K8s v1.26.4 --
- yet we kept sending `FailedComponent` warning event approximately every 30 seconds or so
As a fix, we'll check if …

PWX-30386: Skip sending warn-event when component not found

---

deploy/ccm/config_properties_px.yaml
drivers/storage/portworx/testspec/ccmGoRegisterConfigMap.yaml

cherry-pick from approved [master merge](https://github.com/libopenstorage/operator/pull/1064)
Closes #

PWX-31585: added new certStoreType kv pair to accommodate changes in latest ccm-go image

---

pkg/controller/storagecluster/storagecluster.go

Fix error msg.   Should not begin with lowercase.
Closes #

PWX-31739: Lower case error message.

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/23.6.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.6.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.6.0/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml

Sets up 23.6.0 branch
This PR sets up the metadata and build for `px-rel-23.6.0` branch
Closes #

Sets up 23.6.0 branch

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/23.5.1/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.5.1/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.5.1/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml

Setup 23.5.1 branch

---

pkg/controller/storagecluster/storagecluster.go

Preflight was being executed on upgrade and was changing the configuration from BTRSF to DMthin when it was not supposed to. Only execute pre-flight on fresh PX install.
Closes #
PWX-31931

Pwx 31931 preflight on fresh install only

---

drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/preflight.go
pkg/util/test/util.go

PWX-31959: Don't pass in '-T dmthin' use '-T PX-StoreV2'.

---

drivers/storage/portworx/preflight.go

Use lowercase chars for -T dmthin backend .   
Closes #
PWX-32037

PWX-31969: Use lowercase chars in -T param.

---

drivers/storage/portworx/preflight.go

make sure to use lower case cherry-pick from master:  https://github.com/libopenstorage/operator/pull/1097
Closes #
PWX-31969

PWX-31969: Use lowercase chars in -T param. (#1097)

---

drivers/storage/portworx/component/csi.go

cherry-pick of https://github.com/libopenstorage/operator/pull/1099

PWX-32073: Update csi-provisioner operation timeout from 10s to 5m

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/testspec/px_telemetry-with-location.yaml
drivers/storage/portworx/testspec/px_telemetry.yaml
drivers/storage/portworx/testspec/px_telemetry_with_proxy.yaml

cherry-picked from merged master [PR](https://github.com/libopenstorage/operator/pull/1111) that has been approved
Closes #

PWX-32127: Only add telemetry phonehome volume if px is at least 3.0

---

deploy/ccm/envoy-config-collector-custom-proxy.yaml
deploy/ccm/envoy-config-register-custom-proxy.yaml
deploy/ccm/envoy-config-rest-custom-proxy.yaml
drivers/storage/portworx/testspec/ccmGoCollectorProxyConfigMap_proxy.yaml
drivers/storage/portworx/testspec/ccmGoPhonehomeProxyConfigMap_proxy.yaml
drivers/storage/portworx/testspec/ccmGoRegisterProxyConfigMap_proxy.yaml

Those missing sections have been put in the config for envoy running without proxy but overlooked for the proxied environment. So adding them as fix for current issue
Closes #

PWX-32197: added missing http filters config for envoy running with proxy

---

deploy/ccm/envoy-config-collector-custom-proxy.yaml
deploy/ccm/envoy-config-register-custom-proxy.yaml
deploy/ccm/envoy-config-rest-custom-proxy.yaml
drivers/storage/portworx/testspec/ccmGoCollectorProxyConfigMap_proxy.yaml
drivers/storage/portworx/testspec/ccmGoPhonehomeProxyConfigMap_proxy.yaml
drivers/storage/portworx/testspec/ccmGoRegisterProxyConfigMap_proxy.yaml

Cherry-picked from approved master [PR](https://github.com/libopenstorage/operator/pull/1118) 
Closes #

added missing http filters config for envoy running with proxy (#1118)

---

.github/workflows/on-pr.yml

Removes github comment for xl PR size
Closes #

Update on-pr.yml to remove xl message

---

Makefile
deploy/olm-catalog/portworx/23.5.1/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.5.1/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.5.1/portworx-certified.clusterserviceversion.yaml

Setup 23.5.1 package in master

---

pkg/controller/portworxdiag/portworxdiag.go

If multiple PortworxDiag objects are created, we only want to run one at once as concurrent pxctl diags requests aren't yet supported.
Eventually we may make this more detailed to handle this on a node-level basis, but for now this is enough as multiple diag objects at once is probably pretty uncommon.
Also does a minor fix for me calling the k8s event function wrong.
PWX-29718

PWX-29718: Prevents multiple diags from running at once

---

drivers/storage/portworx/util/util.go
drivers/storage/portworx/util/util_test.go

* PWX-32297: Use version extracted from manifest URL.
* PWX-32297: Add unit test and check annotation and manifest URL even if the an image is not specified.
* PWX-32297: If pxVersion is found return right away.  Skip annotation check if pxVersion not nil.
---------
Merge from master...
Closes #

PWX-32297: Use version extracted from manifest URL. (#1133)

---

deploy/crds/core_v1_storagecluster_crd.yaml
drivers/storage/portworx/component/grafana.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/testspec/grafanaDeployment.yaml

Add grafana image to desired images CRD
Closes #

PWX-32080: Add grafana image to desired images CRD

---

deploy/olm-catalog/portworx/23.7.0/portworx-certified.clusterserviceversion.yaml

Fixing the "previous operator release" in the ClusterServiceVersion
Closes # (none)

Fixing 23.7.0 CSV

---

pkg/controller/portworxdiag/pod.go
pkg/util/test/util.go
test/integration_test/basic_dmthin_test.go
test/integration_test/cloud_provider/cloud_drive.go
test/integration_test/cloud_provider/vsphere.go
test/integration_test/utils/storagecluster.go
test/integration_test/utils/utils.go

Closes #
```
--- PASS: TestStorageClusterBasicDMthin (1472.68s)
--- PASS: TestStorageClusterBasicDMthin/BasicInstallDmthinWithMetadataDevice (768.89s)
--- PASS: TestStorageClusterBasicDMthin/BasicInstallDmthinWithMetadataAndKVDBDevice (703.78s)
PASS
==================================================
--- PASS:
BasicInstallDmthinWithMetadataDevice []
BasicInstallDmthinWithMetadataAndKVDBDevice []
--- SKIP:
--- FAIL:
==================================================
DONE 3 tests in 1472.953s
Tests passed
```

PWX-31962: Op-integration test for dmthin basic install and uninstall

---

deploy/crds/core_v1_storagecluster_crd.yaml
deploy/plugin/nginx-deployment.yaml
deploy/plugin/plugin-deployment.yaml
drivers/storage/portworx/component/plugin.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/testspec/nginx-deployment.yaml
drivers/storage/portworx/testspec/plugin-deployment.yaml
pkg/apis/core/v1/storagecluster.go
pkg/migration/generate.go

Cherrypick https://github.com/libopenstorage/operator/pull/1136

Cherrypick PWX-32147 : add custom image registry support for plugin pod

---

pkg/util/test/util.go

Fix Telemetry status regex for when we can have other debug lines in pxctl status output

PTX-18659 Fix Telemetry status regex

---

test/integration_test/basic_test.go

Add delete StorageCluster after each test

PTX-19249 Add delete StorageCluster after each test

---

pkg/util/test/util.go

Skip Telemetry validation if op less than 23.5.1 and PX higher than 3.0

PTX-19252 Skip Telemetry validation if op less than 23.5.1 and PX higher than 3.0

---

test/integration_test/main_test.go
test/integration_test/operator-test-pod-template.yaml
test/integration_test/test-deploy.sh
test/integration_test/utils/constants.go
test/integration_test/utils/storagecluster.go

Add flag to pass additional custom annotations to STC

PTX-19369 Add flag to pass additional custom annotations to STC

---

Makefile
drivers/storage/portworx/testspec/prometheusRule.yaml

Update the prometheus rules and catalog base registry

---

drivers/storage/portworx/testspec/prometheusRule.yaml

Update the prometheus rules

---

drivers/storage/portworx/util/util.go
drivers/storage/portworx/util/util_test.go

cherry-picked from master
Closes #

PWX-32800: proxy with http protocol also supports user/password

---

deploy/ccm/envoy-config-collector-custom-https-proxy.yaml
deploy/ccm/envoy-config-register-custom-https-proxy.yaml
deploy/ccm/envoy-config-rest-custom-https-proxy.yaml
drivers/storage/portworx/component/telemetry.go
drivers/storage/portworx/testspec/ccmGoCollectorProxyConfigMap_httpsproxy.yaml
drivers/storage/portworx/testspec/ccmGoPhonehomeProxyConfigMap_httpsproxy.yaml
drivers/storage/portworx/testspec/ccmGoRegisterProxyConfigMap_httpsproxy.yaml
drivers/storage/portworx/util/util.go

cherry-picked from master for removing wrong setup/check for https proxy using basic auth 
Closes #

fix for the https proxy with basic authn

---

pkg/util/test/util.go
test/integration_test/basic_test.go
test/integration_test/utils/storagecluster.go

Fix enabled/disabled Telemetry logic validation as per discussion with @ezhang-px

PTX-19576 Fix enabled/disabled Telemetry logic validation

---

drivers/storage/portworx/testspec/prometheusRule.yaml

Rules have changed in the portworx docs repo. Copied over the new version
of the file.
Closes #
Once I have an approval on this PR, I will merge the corresponding change in the docs repo. Then, the build should pass.

Update the prometheus rules used by the test

---

drivers/storage/portworx/testspec/prometheusRule.yaml

Rules have changed in the portworx docs repo. Copied over the new version of the file.
Closes #

cherry-pick: Update the prometheus rules used by the test

---

deploy/olm-catalog/portworx/23.4.1/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.4.1/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.4.1/portworx-certified.clusterserviceversion.yaml

This commit adds 23.4.1 catalogs to the `master`-branch
Closes # (none)
Cherry picks of..:
* https://github.com/libopenstorage/operator/pull/1236
* https://github.com/libopenstorage/operator/pull/1237

Add 23.4.1 catalogs (#1236) (#1237)

---

drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go

[cherry-pick] PWX-33418: Compensate for prox-branch renaming (#1247)

---

drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/testspec/px-csi-win-driver.yaml
drivers/storage/portworx/util/csi_generator.go

Cherrypick https://github.com/libopenstorage/operator/pull/1239

Cherrypick : Update px-windows-csi-driver tag to 23.8.0

---

deploy/crds/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.5.1/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/99.9.9/portworx-certified.clusterserviceversion.yaml
drivers/storage/portworx/component/windows.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/testspec/px-csi-node-win.yaml
drivers/storage/portworx/testspec/px-csi-win-driver.yaml
drivers/storage/portworx/util/csi_generator.go
pkg/apis/core/v1/storagecluster.go
pkg/migration/generate.go

Cherrypick following commit to master for WCS : 
https://github.com/libopenstorage/operator/pull/1239
https://github.com/libopenstorage/operator/pull/1231
https://github.com/libopenstorage/operator/pull/1224

Cherrypick windows changes to master

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/23.9.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.9.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.9.0/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml

Setting up boilerplate files for `operator 23.9.0` release
Closes # -

Setup 23.9.0 branch

---

drivers/storage/portworx/manifest/manifest.go
drivers/storage/portworx/manifest/manifest_test.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/testspec/nginx-deployment.yaml

Fixes Fixes https://portworx.atlassian.net/browse/PWX-32952
Cherrypick https://github.com/libopenstorage/operator/pull/1265

[Cherrypick] PWX-32952 : Update nginx image to v1.25 (#1265)

---

drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/status.go
drivers/storage/portworx/status_test.go
drivers/storage/storage.go
pkg/apis/core/v1/storagecluster.go
pkg/apis/core/v1/storagenode.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go
pkg/controller/storagecluster/update.go
pkg/controller/storagenode/storagenode.go
pkg/mock/storagedriver.mock.go
pkg/util/util.go
pkg/util/util_test.go

Closes # https://portworx.atlassian.net/browse/PWX-28655

[Cherrypick PWX-28655] Add Portworx Install and Update conditions to StorageCluster status

---

pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go
pkg/controller/storagecluster/update.go
pkg/controller/storagenode/storagenode.go
pkg/util/k8s/k8s.go
pkg/util/util.go

Closes #
https://portworx.atlassian.net/browse/PWX-28349
https://portworx.atlassian.net/browse/PWX-28659

[Cherrypick] Fix storage cluster status issues

---

drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/preflight.go
pkg/preflight/utils.go

Pxstore-v2 preflight should run on azure & >= PX 3.1.0
Closes #
PWX-34098
Unit test exists.  But pending Azure setup for more testing.

PWX-34098: Pxstore-v2 preflight should run on azure & >= PX 3.1.0

---

Makefile
build/Dockerfile

We should not be using a specific build of a baseeline image -- switching to the `baseline:LATEST` instead
Closes #  PWX-34393

PWX-34393: Updating baseline image

---

pkg/controller/storagenode/storagenode.go

After adding the managed-by label, we were checking for existing pods with that label. As the existing pods do not have that label, we were assuming that the pod doesn't exist and creating a new one.
Closes # https://portworx.atlassian.net/browse/PWX-34381

PWX-34381 Prevent creating multiple kvdb pods on same node

---

pkg/util/test/util.go

PTX-20774 Fix external KVDB validation

---

drivers/storage/portworx/portworx.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/preflight.go
pkg/preflight/utils.go

preflight check for dmthin gke
Torpedo run with preflight PASSED 
https://jenkins.pwx.dev.purestorage.com/job/Users/job/ChiaChun/job/gcp-dmthin/31/
Closes #

PWX-34185 preflight check for gce

---

drivers/storage/portworx/component/autopilot.go
drivers/storage/portworx/testspec/autopilotClusterRole.yaml
drivers/storage/portworx/testspec/autopilotClusterRole_k8s_1.24.yaml

cherry-pick from merged master [PR](https://github.com/libopenstorage/operator/pull/1313) 
Closes #

PWX-34650: allow autopilot to watch pvc (#1313)

---

drivers/storage/portworx/component/autopilot.go
drivers/storage/portworx/testspec/autopilotClusterRole.yaml
drivers/storage/portworx/testspec/autopilotClusterRole_k8s_1.24.yaml

cherry-picked from merged master [PR](https://github.com/libopenstorage/operator/pull/1315)
Closes #

PWX-34798: allow autopilot to watch configmap (#1315)

---

drivers/storage/portworx/manifest/manifest.go

drivers/storage/portworx/manifest/manifest.go
This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1319 into `px-rel-23.10.0` branch
Closes #  PWX-34824 (23.10.0)

PWX-34824 (23.10.0): updating default images (#1319)

---

drivers/storage/portworx/component/autopilot.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/autopilotClusterRole.yaml
drivers/storage/portworx/testspec/autopilotClusterRole_k8s_1.24.yaml
drivers/storage/portworx/testspec/autopilotDeployment.yaml

cherry-picked from merged master [PR](https://github.com/libopenstorage/operator/pull/1318)
Closes #

PWX-34796: added scc and vol mnt for autopilot(#1318)

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/23.12.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.12.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.12.0/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml

This PR sets up the boilerplate code for the `px-rel-23.12.0` release, based off of `23.10.0`
Closes #  n/a

Setup 23.12.0 branch

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/23.10.1/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.10.1/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.10.1/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml

Setup 23.10.1 branch

---

.travis.yml
Makefile
go.mod
test/integration_test/Dockerfile

This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1336 into `hk-rel-23.12.0` branch
Closes # PWX-34634 (23.12.0)

PWX-34634 (23.12.0): Upgrade build to golang-1.21 (#1336)

---

drivers/storage/portworx/preflight.go

Cherry-pick from master 
Closes #

PWX-33232: Save logging from pre-flight pod for diagnostics. (#1332)

---

Makefile
deploy/olm-catalog/portworx/23.12.0/portworx-certified.clusterserviceversion.yaml

Fixing `23.12.0` to refer to ~23.10.0~ `23.10.1` as "previous build"
Closes # -

Fixing Makefile/CSV to advance "previous build"

---

test/integration_test/Dockerfile

This is a cherry-pick of https://github.com/libopenstorage/operator/pull/1345 into `px-rel-23.12.0` branch
Closes #

Integration test build fix (23.12.0 cherry-pick) (#1345)

---

drivers/storage/portworx/testspec/prometheusRule.yaml

Cherrypick https://github.com/libopenstorage/operator/pull/1350

Modifying UTs for docs change in PWX-35016

---

pkg/controller/storagecluster/storagecluster.go

**What this PR does / why we need it**: The attempt to update which is throwing error initially while updating the status, because of this error, we see difference in cluster.Spec.version and cluster.status.version as cluster’s status is not updated. The changes include retrying again in case of status update failure.
Closes # https://portworx.atlassian.net/browse/PWX-35004
**Special notes for your reviewer**: Verified while installing portworx, operator tries to update status again and autopilot image is not reset to empty.

PWX-35004 : Operator reconciles and removes image param specified in the STC

---

pkg/controller/storagecluster/storagecluster.go

Cherrypick https://github.com/libopenstorage/operator/pull/1370

[cherry-pick] PWX-35004 : Retry to update storagecluster status if it fails (#1370)

---

pkg/util/test/util.go

Add check for plugin resource. This is needed for Dynamic Plugin validation decision.

PTX-21563 Add check for plugin resource

---

pkg/util/test/util.go

Set correct config.json path in case of PKS

PTX-21676 Set correct config.json path in case of PKS

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/23.10.3/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.10.3/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.10.3/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml
deploy/operator.yaml

Setup 23.10.3 branch

---

drivers/storage/portworx/components_test.go

**What this PR does / why we need it**: Removing code not belonging to release 23.10.3

Removing code not belonging to release 23.10.3

---

drivers/storage/portworx/component/autopilot.go

[cherrypick] PWX-35945 : Create autopilot deployment if secret is not created

---

drivers/storage/portworx/component/plugin.go
drivers/storage/portworx/components_test.go

[cherry-pick] Update plugin deployment Pull to Always regardless of STC's PullPolicy

---

pkg/util/test/util.go

Fixing validation for PX running on master nodes

PTX-22178 Fixing validation for PX running on master nodes

---

pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go
pkg/controller/storagenode/storagenode.go
pkg/controller/storagenode/storagenode_test.go
pkg/util/k8s/node.go
pkg/util/k8s/node_test.go

Closes # https://portworx.atlassian.net/browse/PWX-35282
Added few UTs. Adding more for the controllers.

PWX-35282 Don't restart px pods when cordoned after operator restart

---

deploy/olm-catalog/portworx/23.10.1/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.10.1/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.10.1/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/23.10.2/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.10.2/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.10.2/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/23.10.3/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/23.10.3/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/23.10.3/portworx-certified.clusterserviceversion.yaml

Add missing CSVs

---

deploy/olm-catalog/portworx/23.10.3/portworx-certified.clusterserviceversion.yaml

Updating CSV to use 23.10.3 released image

---

Makefile

Fix docker build make target

---

.travis.yml
Makefile
deploy/olm-catalog/portworx/24.1.0/core_v1_storagecluster_crd.yaml
deploy/olm-catalog/portworx/24.1.0/core_v1_storagenode_crd.yaml
deploy/olm-catalog/portworx/24.1.0/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/portworx.package.yaml
deploy/operator.yaml

Setup branch for 24.1.0

---

drivers/storage/portworx/component/autopilot.go
drivers/storage/portworx/testspec/autopilotDeployment_Openshift_4_14.yaml

Cherrypick https://github.com/libopenstorage/operator/pull/1432 to 23.10.4

[Cherrypick] PWX-36029 : Update certificate's mountpath in autopilot pod 

---

drivers/storage/portworx/components_test.go

cherrypick https://github.com/libopenstorage/operator/pull/1450

[Cherrypick 23.10.3] Add UTs for openshift prometheus on OCP 4.14

---

Makefile

Changed default release version to 99.9.9

Changed default release version to 99.9.9

---

pkg/util/test/util.go

Adding a method to check if fresh PX installation, this will be eventually used for validating components that behave different based on if its fresh install or not. For now just doing a print

PTX-22712 Add method to check if fresh PX installation

---

drivers/storage/portworx/component/autopilot.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/util/util.go
drivers/storage/portworx/util/util_test.go

Closes # https://portworx.atlassian.net/browse/PWX-35994

[cherrypick] Support Openshift Prometheus on OCP 4.15

---

Makefile

Fix for operator version
Closes [PWX-36455](https://portworx.atlassian.net/browse/PWX-36455)
[PWX-36455]: https://portworx.atlassian.net/browse/PWX-36455?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PWX-36455 Fix for operator version

---

pkg/controller/storagecluster/storagecluster.go

Use proper api's to update the status and cluster to ensure the commits happen and resourceVersions are updated correctly.
Closes #
PWX-36321
Testing:  https://jenkins.pwx.dev.purestorage.com/job/Users/job/Jose/job/Hose-OCP-Preflight-allCombinations/6/

PWX-36321: Use client to update status and cluster preserving the resourceVersion

---

deploy/olm-catalog/portworx/23.10.5/portworx-certified.clusterserviceversion.yaml
deploy/olm-catalog/portworx/24.1.0/portworx-certified.clusterserviceversion.yaml

PWX-36428 Add metadata annotations in CSV for openshift catalog

---

drivers/storage/portworx/component/disruption_budget.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/util/util.go
pkg/util/k8s/k8s.go

**What this PR does / why we need it**: cherry pick of [1488](https://github.com/libopenstorage/operator/pull/1488)

[Cherry-pick] : Of ticket - PWX-36389 into release-24.1.0

---

pkg/util/test/util.go

Add validation for safe-to-evict annotation

PTX-22900 Add validation for safe-to-evict annotation

---

pkg/util/test/util.go

Increase timeout to check PX pods annotations

PTX-23039 Increase timeout to check PX pods annotations

---

drivers/storage/portworx/component/securitycontextconstraints.go
pkg/constants/metadata.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go
pkg/controller/storagecluster/update.go

[cherrypicks] required-scc changes to support ocp 4.15

---

drivers/storage/portworx/component/portworx_basic.go
drivers/storage/portworx/testspec/portworxClusterRole.yaml

Cherrypick https://github.com/libopenstorage/operator/pull/1506 to 23.10.5

[23.10.5] PWX-36730 : Add namespace resource access permission to Portworx clusterrole 

---

pkg/util/test/util.go

Add validation for Telemetry ports

PTX-19629 Add validation for Telemetry ports

---

pkg/util/test/util.go

Change PVC controller validation logic for 24.1.0+, we are now not deploying PVC controller on OCP for 24.1+

PTX-23278 Change PVC controller validation logic for 24.1.0+

---

deploy/olm-catalog/portworx/24.1.0/portworx-certified.clusterserviceversion.yaml

Change the previous version in 24.1.0 CSV

---

pkg/util/test/util.go

Fix Telemetry validation command with Security and Debug mode enabled

PTX-23346 Fix Telemetry validation command with Security and Debug mode enabled

---

pkg/util/test/util.go

Some `storageNode.Status.NodeAttributes` like `nodeAttributes` were introduced in op 23.10.0
This PR is to check for these attributes only when opVersion is higher than expected. 
Closes # PTX-23350

PTX-23350 validatePxPodsAnnotations for StorageNode should be called when op >= 23.10.0

---

test/integration_test/utils/marketplace.go

PTX-23508 Ability to pass secrets to PX Operator CatalogSource object

PTX-23508 Ability to pass secrets to PX Operator CatalogSource object

---

test/integration_test/main_test.go
test/integration_test/operator-test-pod-template.yaml
test/integration_test/test-deploy.sh
test/integration_test/utils/constants.go
test/integration_test/utils/marketplace.go

Add method to specify PX Operator registry image in the CatalogSource

PTX-23488 Add method to specify PX Operator registry image in the CatalogSource

---

drivers/storage/portworx/component/securitycontextconstraints.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/testspec/portworxSCC.yaml
drivers/storage/portworx/testspec/portworxSCC_Openshift.yaml

cherrypick https://github.com/libopenstorage/operator/pull/1514 to 24.1.0

[cherrypick 24.1.0] PWX-36663 : Remove px-prometheus user from Portworx SCC for OCP 4.12+

---

drivers/storage/portworx/component/security.go
drivers/storage/portworx/portworx.go
drivers/storage/portworx/status.go
drivers/storage/portworx/status_test.go
drivers/storage/portworx/util/util.go

[cherrypick] [24.1.0] PWX-37153 : Skip security check while fetching KVDB members

---

pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/update.go

**What this PR does / why we need it**: Cherry pick of [#1542](https://github.com/libopenstorage/operator/pull/1542)

[Cherry-pick] - Cp of PWX-37204 and PWX- 37178

---

drivers/storage/portworx/util/util.go
pkg/controller/storagenode/storagenode.go
pkg/controller/storagenode/storagenode_test.go

Cherry-pick PR https://github.com/libopenstorage/operator/pull/1552 to 24.1.0

[cherry-pick] [24.1.0] PWX-37266 : Upgrade should not continue when PDB value is set to 1 and there is already a PX node down

---

go.mod
go.sum
pkg/migration/migration_test.go
pkg/mock/mockcore/core.ops.mock.go
vendor/github.com/portworx/sched-ops/k8s/core/core.go
vendor/github.com/portworx/sched-ops/k8s/core/events.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/kubevirt.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstance.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstancemigration.go
vendor/modules.txt

Need to pick up the change to virtualmachineinstancemigration.go.
PWX-37466

PWX-37466: vendor in the latest sched-ops

---

drivers/storage/portworx/portworx.go
drivers/storage/portworx/preflight.go
drivers/storage/portworx/util/util.go

Operator changes to detect Anthos with vSphere and default to dmthin
Closes # PWX-37199

PWX-37199: Enable dmthin preflight checks for anthos vsphere

---

go.mod
go.sum
pkg/mock/mockcore/core.ops.mock.go
vendor/github.com/portworx/sched-ops/k8s/core/serviceaccounts.go
vendor/modules.txt

Operator needs to create service account token with the help from sched-ops. Thus vendor in the latest sched ops.
Corresponding sched PR: https://github.com/portworx/sched-ops/pull/394

PWX-37620 Vendor in latest sched ops

---

drivers/storage/portworx/portworx.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go

**What this PR does / why we need it**: Cherry-pick of PR [#1275 ](https://github.com/libopenstorage/operator/pull/1275) for ticket - PWX-32229 into release-24.1.1

[Cherry-pick ]: Cherry-pick of PR #1275

---

deploy/ccm/config_properties_px.yaml
drivers/storage/portworx/testspec/ccmGoRegisterConfigMap.yaml

- Added `internalHostnameLookupRetryCount:3` in configmap/px-telemetry-register for the Telemetry
Closes https://purestorage.atlassian.net/browse/PWX-37634

PWX-37634 : Added internalHostnameLookupRetryCount in px-telemetry-register configmap

---

deploy/ccm/config_properties_px.yaml
drivers/storage/portworx/testspec/ccmGoRegisterConfigMap.yaml

- cherry pick changes of PR https://github.com/libopenstorage/operator/pull/1584 for release-24.1.1 
- Added `internalHostnameLookupRetryCount:3` in configmap/px-telemetry-register for the Telemetry
Closes https://purestorage.atlassian.net/browse/PWX-37634

[cherry-pick] PWX-37634 : Added internalHostnameLookupRetryCount in px-telemetry-register configmap

---

drivers/storage/portworx/portworx.go
drivers/storage/portworx/preflight.go
drivers/storage/portworx/util/util.go

Dont default to dmthin on OCP-FACD
Closes # PWX-37881

Dont default to dmthin on OCP-FACD

---

deploy/crds/core_v1_storagecluster_crd.yaml
drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
pkg/apis/core/v1/storagecluster.go
pkg/controller/storagecluster/controller_test.go

**What this PR does / why we need it**: Cherry-pick of [#1355 ](https://github.com/libopenstorage/operator/pull/1355) into release-24.1.1

[Cherry-pick]: Cherry-pick of  PR #1355 into 24.1.1

---

drivers/storage/portworx/preflight.go
drivers/storage/portworx/preflight_test.go

https://purestorage.atlassian.net/browse/PWX-37733
Along with https://github.com/pure-px/porx/pull/13643 I successfully run a px cluster with dmthin with ocp facd

PWX-37733 Add pod name in system metadata device for dmthin on ocp facd

---

drivers/storage/portworx/component/telemetry.go

* the telemetry needs to force-delete the invalid pure-telemetry-certs secret  (no owner's check)
This is a follow-up fix for #1553
**ISSUE**:
* it turns out the `secret/pure-telemetry-certs` may be stored _WITHOUT_ the `metatata.ownerReference`
* note that the px-operator's "normal"  `DeleteSecret()` will remove the secret _only_ if it has required object owners
- this is not a problem for most of operator-created secrets, since it's the operator itself that creates the `secret` object, and it'll populate the correct `ownerReference`
- however, with `secret/pure-telemetry-certs` the secret is created by telemetry POD (`ccm-go` container), but owner gets populated at later point in time  (i.e. this particular secret follows 2-step-creation process) …

PWX-38007: Telemetry cert-secret refresh fix

---

pkg/util/test/util.go
test/integration_test/basic_test.go

Add an integrartion test to verify the serviceaccount token refresh mechanism for portworx. 
PWX-37884

PWX-37884 Add portworx serviceaccount token refresh integration test

---

drivers/storage/portworx/components_test.go
drivers/storage/portworx/util/util.go
drivers/storage/portworx/util/util_test.go

Cherrypick https://github.com/libopenstorage/operator/pull/1610 to 24.1.1

[cherrypick] [24.1.1] PWX-38202 : Fix NTP server issue by setting token issue time in past

---

drivers/storage/portworx/portworx.go

Dont default to dmthin for OCP-Vsphere
Closes # PWX-38279

PWX-38279: Dont default to dmthin for OCP-Vsphere

---

drivers/storage/portworx/alert_manager_component_test.go
drivers/storage/portworx/component/portworx_basic.go
drivers/storage/portworx/components_test.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/portworx_test.go
drivers/storage/portworx/status_test.go
drivers/storage/portworx/testspec/portworxServiceAccountTokenSecret.yaml
drivers/storage/portworx/util/util.go
go.mod
go.sum
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go
pkg/mock/mockcore/core.ops.mock.go
pkg/util/k8s/k8s.go
pkg/util/test/util.go
test/integration_test/basic_test.go
vendor/github.com/portworx/sched-ops/k8s/core/serviceaccounts.go
vendor/modules.txt

Cherry pick all the token refresh changes into 24.2.0
https://purestorage.atlassian.net/browse/PWX-37995

PWX-37995 Cherry pick token refresh changes into release branch 24.2.0

---

drivers/storage/portworx/testspec/prometheusRule.yaml

Docs PR: https://github.com/pure-px/portworx-documentation/pull/977
Closes #

[ cherry-pick ] PWX-38379 change pool and volume resize alerts from warning to info

---

deploy/crds/core_v1_storagecluster_crd.yaml
drivers/storage/portworx/deployment.go
drivers/storage/portworx/deployment_test.go
drivers/storage/portworx/portworx.go
pkg/apis/core/v1/storagecluster.go
pkg/controller/storagecluster/controller_test.go
pkg/controller/storagecluster/storagecluster.go

**What this PR does / why we need it**: CP of missing 24.1.1 commits

[Cherry-pick] - Cherrypick Of 24.1.1 commits 

---

go.mod
go.sum
vendor/github.com/portworx/sched-ops/k8s/core/core.go
vendor/github.com/portworx/sched-ops/k8s/core/persistentvolumeclaims.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/kubevirt.go
vendor/github.com/portworx/sched-ops/k8s/kubevirt-dynamic/virtualmachineinstance.go
vendor/modules.txt

This is to pull in the fix for kubevirt GetVirtualMachineInstance.
PWX-38509

PWX-38509: vendor in sched-ops

---

go.mod
vendor/modules.txt

Fix go.mod to be in sync with go.sum file for 24.2.0 release branch.
Closes #

PWX-38590 : fix go.mod for 24.2.0

---

pkg/util/test/util.go

Add retry loop for validating AlertManager

PTX-25622 Add retry loop for validating AlertManager
